import { StyleSheet } from 'react-native';
import type { AppPalette } from '../../theme/useAppTheme';

export const createActivityFeedStyles = (colors: AppPalette) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      minHeight: 56,
      paddingHorizontal: 4,
      flexDirection: 'row',
      alignItems: 'center',
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
      backgroundColor: colors.header,
    },
    headerButton: {
      width: 48,
      height: 48,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      color: colors.text,
      fontSize: 18,
      fontWeight: '600',
      lineHeight: 24,
      textAlign: 'center',
    },
    intro: {
      color: colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 10,
    },
    filterScroll: { flexGrow: 0 },
    filterContent: { paddingHorizontal: 12, paddingBottom: 12, gap: 8 },
    filterChip: {
      minHeight: 48,
      paddingHorizontal: 14,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
    },
    filterChipSelected: {
      borderColor: colors.primary,
      backgroundColor: colors.primarySoft,
    },
    filterText: { color: colors.textSecondary, fontSize: 14, fontWeight: '600' },
    filterTextSelected: { color: colors.primary },
    filterCount: {
      minWidth: 22,
      minHeight: 22,
      paddingHorizontal: 6,
      borderRadius: 11,
      overflow: 'hidden',
      color: colors.textSecondary,
      backgroundColor: colors.surfaceAlt,
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 22,
      textAlign: 'center',
    },
    filterCountSelected: { color: colors.primary, backgroundColor: colors.surface },
    listContent: { paddingHorizontal: 12, paddingBottom: 28, gap: 10 },
    listContentEmpty: { flexGrow: 1, paddingHorizontal: 12, paddingBottom: 28 },
    row: {
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      borderRadius: 14,
      backgroundColor: colors.surface,
      overflow: 'hidden',
      flexDirection: 'row',
      alignItems: 'stretch',
    },
    rowMain: {
      minHeight: 88,
      flex: 1,
      paddingHorizontal: 12,
      paddingVertical: 12,
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 11,
    },
    iconWrap: {
      width: 38,
      height: 38,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySoft,
    },
    rowCopy: { flex: 1, minWidth: 0 },
    rowTopLine: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
    rowTitle: {
      flex: 1,
      color: colors.text,
      fontSize: 15,
      fontWeight: '600',
      lineHeight: 20,
    },
    statusPill: {
      minHeight: 24,
      paddingHorizontal: 8,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    statusText: { fontSize: 11, fontWeight: '700', lineHeight: 15 },
    detail: { color: colors.textSecondary, fontSize: 13, lineHeight: 18, marginTop: 4 },
    metadata: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: 5,
      marginTop: 7,
    },
    metadataText: { color: colors.textTertiary, fontSize: 12, lineHeight: 16 },
    nextOccurrence: { color: colors.textSecondary, fontSize: 12, lineHeight: 16, marginTop: 4 },
    rowChevron: { alignSelf: 'center', marginLeft: 2 },
    artifactAction: {
      width: 48,
      minHeight: 88,
      alignItems: 'center',
      justifyContent: 'center',
      borderLeftWidth: StyleSheet.hairlineWidth,
      borderLeftColor: colors.border,
    },
    emptyState: {
      flex: 1,
      minHeight: 280,
      paddingHorizontal: 28,
      alignItems: 'center',
      justifyContent: 'center',
    },
    emptyIcon: {
      width: 56,
      height: 56,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySoft,
      marginBottom: 14,
    },
    emptyTitle: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '700',
      lineHeight: 24,
      textAlign: 'center',
    },
    emptyHint: {
      color: colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      textAlign: 'center',
      marginTop: 6,
      marginBottom: 18,
    },
    primaryButton: {
      minHeight: 48,
      paddingHorizontal: 18,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
    },
    primaryButtonText: { color: colors.onPrimary, fontSize: 15, fontWeight: '700' },
    advancedButton: {
      minHeight: 56,
      marginTop: 6,
      paddingHorizontal: 12,
      borderRadius: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    advancedCopy: { flex: 1 },
    advancedTitle: { color: colors.text, fontSize: 14, fontWeight: '600', lineHeight: 19 },
    advancedHint: { color: colors.textSecondary, fontSize: 12, lineHeight: 17, marginTop: 2 },
  });

export type ActivityFeedStyles = ReturnType<typeof createActivityFeedStyles>;
