/** Credential semantics that are unambiguous in prose across every app locale. */
export const CREDENTIAL_TEXT_PHRASES = [
  // English
  'access key',
  'access token',
  'api key',
  'api secret',
  'auth token',
  'authentication token',
  'backup code',
  'bearer token',
  'client secret',
  'one time password',
  'password',
  'passwords',
  'passwd',
  'passcode',
  'passphrase',
  'private key',
  'recovery code',
  'refresh token',
  'seed phrase',
  'session cookie',
  'signing key',
  'verification code',
  // Arabic
  'كلمة المرور',
  'رمز المرور',
  'عبارة المرور',
  'مفتاح api',
  'مفتاح واجهة برمجة التطبيقات',
  'رمز الوصول',
  'رمز المصادقة',
  'مفتاح خاص',
  'رمز الاسترداد',
  'العبارة الأولية',
  'رمز التحقق',
  'رمز لمرة واحدة',
  // German
  'api schlüssel',
  'authentifizierungstoken',
  'einmalpasswort',
  'passwort',
  'passphrase',
  'privater schlüssel',
  'sitzungscookie',
  'verifizierungscode',
  'wiederherstellungscode',
  'zugriffstoken',
  // Spanish
  'clave api',
  'clave privada',
  'código de recuperación',
  'código de verificación',
  'contraseña',
  'contraseña de un solo uso',
  'cookie de sesión',
  'frase de contraseña',
  'frase semilla',
  'token de acceso',
  'token de autenticación',
  // French
  'clé api',
  'clé privée',
  'code à usage unique',
  'code de récupération',
  'code de vérification',
  'cookie de session',
  'jeton d accès',
  'jeton d authentification',
  'mot de passe',
  'phrase de récupération',
  // Japanese
  'apiキー',
  'アクセストークン',
  'シードフレーズ',
  'セッションクッキー',
  'パスコード',
  'パスフレーズ',
  'パスワード',
  'リカバリーコード',
  'ワンタイムパスワード',
  '復旧コード',
  '秘密鍵',
  '認証コード',
  '認証トークン',
  // Portuguese (Brazil)
  'chave api',
  'chave privada',
  'código de recuperação',
  'código de verificação',
  'cookie de sessão',
  'frase semente',
  'senha',
  'senha de uso único',
  'token de acesso',
  'token de autenticação',
  // Chinese (Simplified and Traditional)
  'api密钥',
  'api密鑰',
  'api金鑰',
  '会话cookie',
  '工作階段cookie',
  '动态口令',
  '動態密碼',
  '助记词',
  '助記詞',
  '口令',
  '密码',
  '密碼',
  '恢复代码',
  '復原碼',
  '私钥',
  '私鑰',
  '种子短语',
  '種子片語',
  '访问令牌',
  '存取權杖',
  '认证令牌',
  '驗證權杖',
  '验证码',
  '驗證碼',
] as const;

/** Intimate, contact, medical, identity, and financial prose semantics. */
export const SENSITIVE_TEXT_PHRASES = [
  // English
  'account number',
  'allergy',
  'authentication method',
  'bank account',
  'billing address',
  'blood type',
  'card number',
  'credit card',
  'criminal record',
  'debit card',
  'diagnosis',
  'driver license',
  'emergency contact',
  'financial account',
  'gender identity',
  'health condition',
  'home address',
  'medical condition',
  'medical history',
  'medical information',
  'medical status',
  'medication',
  'medicine',
  'national id',
  'passport number',
  'phone number',
  'precise location',
  'prescription',
  'religious belief',
  'sexual orientation',
  'shipping address',
  'social security number',
  'tax id',
  '2 fa method',
  'two factor method',
  // Arabic
  'الحساب المصرفي',
  'الحالة الطبية',
  'التاريخ الطبي',
  'العنوان المنزلي',
  'بطاقة ائتمان',
  'تشخيص',
  'جواز السفر',
  'حساسية طبية',
  'راتب',
  'رقم الحساب',
  'رقم الهوية',
  'رقم الهاتف',
  'رقم ضريبي',
  'دواء',
  // German
  'allergie',
  'bankkonto',
  'diagnose',
  'gehalt',
  'gesundheitszustand',
  'kreditkarte',
  'krankengeschichte',
  'medikament',
  'personalausweisnummer',
  'privatadresse',
  'reisepassnummer',
  'steuer id',
  'telefonnummer',
  'wohnadresse',
  // Spanish
  'alergia',
  'condición médica',
  'cuenta bancaria',
  'diagnóstico',
  'dirección de casa',
  'historial médico',
  'medicación',
  'número de cuenta',
  'número de identidad',
  'número de pasaporte',
  'número de teléfono',
  'salario',
  'tarjeta de crédito',
  // French
  'adresse personnelle',
  'allergie',
  'antécédents médicaux',
  'carte de crédit',
  'compte bancaire',
  'diagnostic',
  'état de santé',
  'médicament',
  'numéro de compte',
  'numéro de passeport',
  'numéro de téléphone',
  'numéro fiscal',
  'salaire',
  // Japanese
  'アレルギー',
  'クレジットカード',
  'パスポート番号',
  '健康状態',
  '医療履歴',
  '口座番号',
  '投薬',
  '携帯電話番号',
  '自宅住所',
  '診断',
  '銀行口座',
  // Portuguese (Brazil)
  'alergia',
  'cartão de crédito',
  'condição médica',
  'conta bancária',
  'diagnóstico',
  'endereço residencial',
  'histórico médico',
  'medicação',
  'número da conta',
  'número de identidade',
  'número de passaporte',
  'número de telefone',
  'salário',
  // Chinese (Simplified and Traditional)
  '信用卡',
  '健康状况',
  '健康狀況',
  '医疗记录',
  '醫療紀錄',
  '家庭住址',
  '居住地址',
  '护照号码',
  '護照號碼',
  '电话号码',
  '電話號碼',
  '用药',
  '用藥',
  '诊断',
  '診斷',
  '账户号码',
  '帳戶號碼',
  '身份证号码',
  '身分證號碼',
  '银行账户',
  '銀行帳戶',
] as const;

/** Exact field labels that imply a credential even without a structured value. */
export const CREDENTIAL_FIELD_NAMES = [
  'credential',
  'credentials',
  'mnemonic',
  'otp',
  'pin',
  'passwd',
  'password',
  'passcode',
  'passphrase',
  'secret',
  'token',
  'totp',
  'الرقم السري',
  'رمز سري',
  'geheimnis',
  'pin code',
  'secreto',
  'código pin',
  'code pin',
  'secret',
  '暗証番号',
  '秘密',
  'segredo',
  'código pin',
  '密钥',
  '密鑰',
] as const;

/** Exact sensitive field labels; broad words such as card and address are omitted. */
export const SENSITIVE_FIELD_NAMES = [
  'allergy',
  'allergies',
  'blood type',
  'bsn',
  'diagnosis',
  'finance',
  'financial',
  'health',
  'iban',
  'medication',
  'medical',
  'medicine',
  'passport',
  'prescription',
  'religion',
  'salary',
  'ssn',
  'tax number',
  'تشخيص',
  'حساسية',
  'راتب',
  'رقم الهوية',
  'allergie',
  'diagnose',
  'gehalt',
  'steuer id',
  'alergia',
  'diagnóstico',
  'salario',
  'diagnostic',
  'salaire',
  'アレルギー',
  '診断',
  'alergia',
  'diagnóstico',
  'salário',
  '诊断',
  '診斷',
] as const;

/** Personal profile fields, applied only to self/person subjects. */
export const PERSONAL_FIELD_NAMES = [
  'age',
  'birthday',
  'birthdate',
  'child',
  'children',
  'citizenship',
  'city',
  'family',
  'hometown',
  'language',
  'marital status',
  'nationality',
  'occupation',
  'pet',
  'profession',
  'pronoun',
  'pronouns',
  'residence',
  'العمر',
  'الجنسية',
  'المهنة',
  'تاريخ الميلاد',
  'alter',
  'beruf',
  'geburtsdatum',
  'staatsangehörigkeit',
  'edad',
  'fecha de nacimiento',
  'nacionalidad',
  'ocupación',
  'âge',
  'date de naissance',
  'nationalité',
  'profession',
  '年齢',
  '生年月日',
  '職業',
  'idade',
  'data de nascimento',
  'nacionalidade',
  'ocupação',
  '年龄',
  '年齡',
  '出生日期',
  '职业',
  '職業',
] as const;

/** Contact/address fields that are sensitive when they describe a person. */
export const SELF_SENSITIVE_FIELD_NAMES = [
  'address',
  'email address',
  'home address',
  'phone',
  'phone number',
  'عنوان المنزل',
  'رقم الهاتف',
  'adresse',
  'telefonnummer',
  'dirección',
  'número de teléfono',
  'adresse personnelle',
  'numéro de téléphone',
  '住所',
  '電話番号',
  'endereço',
  'número de telefone',
  '地址',
  '电话号码',
  '電話號碼',
] as const;
