export const CLEARED_STRUCTURED_MEMORY_TABLES = [
  'memory_verified_procedure_run_invalidations',
  'memory_verified_procedure_observations',
  'memory_verified_procedure_state',
  'memory_retrieval_outcomes',
  'memory_fact_observations',
  'memory_fact_evidence',
  'memory_fact_contribution_supersessions',
  'memory_fact_contribution_sources',
  'memory_fact_contributions',
  'memory_fact_terms',
  'memory_fact_term_stats',
  'memory_episode_terms',
  'memory_episode_access_policies',
  'memory_episodes',
  'memory_facts',
  'memory_working_blocks',
  'memory_consolidation_state',
  'memory_migration_state',
  'memory_ingestion_receipts',
  'memory_ingestion_jobs',
  'memory_ingestion_source_snapshots',
  'memory_tasks',
  'memory_reflections',
  'memory_retrieval_events',
  'memory_retired_sources',
  'memory_source_retirement_groups',
  'memory_withdrawal_facts',
  'memory_withdrawals',
  'memory_entities',
] as const;

export const PRESERVED_STRUCTURED_MEMORY_TABLES = [
  'memory_vault_identity',
  'memory_episode_retrieval_index_meta',
] as const;
