version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: deps
      include: scope
    groups:
      npm-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      time: "07:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 3
    labels:
      - dependencies
    commit-message:
      prefix: deps
      include: scope
    groups:
      github-actions-minor-and-patch:
        update-types:
          - minor
          - patch
