import { StyleSheet } from 'react-native';
import type { AppPalette } from '../../theme/useAppTheme';

export const createAssistantBubbleStyles = (colors: AppPalette) =>
  StyleSheet.create({
    wrapper: {
      paddingHorizontal: 12,
      paddingVertical: 4,
    },
    assistantWrapper: {
      alignItems: 'flex-start',
    },
    bubble: {
      borderRadius: 16,
      padding: 12,
      overflow: 'hidden',
      minWidth: 0,
      flexGrow: 0,
      flexShrink: 1,
    },
    assistantBubble: {
      backgroundColor: colors.assistantBubble,
      borderWidth: 1,
      borderColor: colors.border,
      borderBottomLeftRadius: 8,
      minWidth: '78%',
      maxWidth: '96%',
      shadowColor: colors.mode === 'dark' ? '#000000' : colors.text,
      shadowOpacity: colors.mode === 'dark' ? 0.22 : 0.08,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 6 },
      elevation: 3,
    },
    assistantContentContainer: {
      minWidth: 0,
      alignSelf: 'stretch',
      gap: 8,
    },
    responseGroup: {
      gap: 4,
      minWidth: 0,
      alignSelf: 'stretch',
    },
    responseSegment: {
      minWidth: 0,
      alignSelf: 'stretch',
    },
    responseSegmentSpaced: {
      marginTop: 8,
      paddingTop: 8,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.subtleBorder,
    },
    assistantChrome: {
      marginHorizontal: -12,
      marginTop: -12,
      marginBottom: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      backgroundColor: colors.surfaceAlt,
      borderBottomWidth: 1,
      borderBottomColor: colors.subtleBorder,
    },
    assistantChromeIdentity: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      minWidth: 0,
      flexShrink: 1,
    },
    assistantChromeDot: {
      width: 8,
      height: 8,
      borderRadius: 999,
      backgroundColor: colors.primary,
      opacity: 0.8,
    },
    assistantChromeDotStreaming: {
      opacity: 1,
    },
    assistantChromeLabel: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.6,
      textTransform: 'uppercase',
      color: colors.textSecondary,
    },
    assistantStatusPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      minWidth: 0,
      maxWidth: '72%',
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.subtleBorder,
      backgroundColor: colors.primarySoft,
    },
    assistantStatusPillText: {
      flexShrink: 1,
      color: colors.text,
      fontSize: 12,
      fontWeight: '600',
    },
    contentNotice: {
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginBottom: 8,
      backgroundColor: colors.surfaceAlt,
      borderWidth: 1,
      borderColor: colors.subtleBorder,
    },
    contentNoticeText: {
      color: colors.textSecondary,
      fontSize: 13,
      lineHeight: 18,
    },
    reviewFooter: {
      marginTop: 12,
      paddingTop: 10,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.subtleBorder,
    },
    reviewPill: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      gap: 8,
      minWidth: 0,
      paddingHorizontal: 10,
      paddingVertical: 7,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.subtleBorder,
      backgroundColor: colors.surfaceAlt,
    },
    reviewPillText: {
      flexShrink: 1,
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: '600',
    },
    effectDot: {
      position: 'absolute',
      top: 0,
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    effectBalloon: {
      position: 'absolute',
      bottom: -4,
      width: 16,
      height: 20,
      borderRadius: 10,
    },
    effectSpotlight: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: colors.primarySoft,
      borderRadius: 16,
    },
    errorBadge: {
      backgroundColor: colors.dangerSoft,
      borderRadius: 4,
      paddingHorizontal: 6,
      paddingVertical: 2,
      marginTop: 6,
      alignSelf: 'flex-start',
    },
    errorText: {
      color: colors.danger,
      fontSize: 11,
      fontWeight: '600',
    },
    actions: {
      flexDirection: 'row',
      gap: 2,
      marginTop: 2,
      paddingHorizontal: 0,
    },
    actionsLeft: {
      justifyContent: 'flex-start',
    },
  });

export type AssistantBubbleStyles = ReturnType<typeof createAssistantBubbleStyles>;
