export const CHAT_VOICE_CANCEL_GESTURE_DISTANCE_PX = 56;
export const CHAT_VOICE_MIN_RECORDING_DURATION_MS = 300;
export const CHAT_VOICE_MIN_RECORDING_FILE_SIZE_BYTES = 1024;
export const CHAT_VOICE_FILE_FLUSH_TIMEOUT_MS = 1500;

export const CHAT_VOICE_PRESS_RETENTION_OFFSET = {
  top: CHAT_VOICE_CANCEL_GESTURE_DISTANCE_PX + 24,
  right: 32,
  bottom: 32,
  left: 32,
} as const;
