import { StyleSheet } from 'react-native';
import type { AppPalette } from '../../theme/useAppTheme';

export const createModelSelectorStyles = (colors: AppPalette) =>
  StyleSheet.create({
    selector: {
      alignItems: 'center',
      alignSelf: 'flex-start',
      backgroundColor: colors.surfaceAlt,
      borderRadius: 16,
      flexDirection: 'row',
      flexGrow: 0,
      flexShrink: 1,
      gap: 4,
      maxWidth: '100%',
      minHeight: 44,
      minWidth: 0,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    selectorText: {
      color: colors.text,
      flexShrink: 1,
      fontSize: 13,
      minWidth: 0,
    },
    selectorTextFull: {
      flex: 1,
      fontSize: 15,
      fontWeight: '600',
    },
    selectorFull: {
      alignSelf: 'stretch',
      borderColor: colors.border,
      borderRadius: 12,
      borderWidth: 1,
      minHeight: 52,
      paddingHorizontal: 14,
      paddingVertical: 10,
      width: '100%',
    },
    selectorDisabled: {
      opacity: 0.5,
    },
    modalOverlay: {
      backgroundColor: colors.overlay,
      flex: 1,
      justifyContent: 'flex-end',
    },
    backdropDismiss: {
      ...StyleSheet.absoluteFillObject,
    },
    modal: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      maxHeight: '82%',
      paddingTop: 16,
    },
    modalHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingBottom: 12,
      paddingHorizontal: 16,
    },
    modalTitle: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '700',
    },
    headerAction: {
      alignItems: 'center',
      height: 44,
      justifyContent: 'center',
      width: 44,
    },
    providerTabs: {
      flexGrow: 0,
      height: 52,
      marginBottom: 4,
      paddingHorizontal: 16,
    },
    providerTab: {
      alignItems: 'center',
      backgroundColor: colors.surfaceAlt,
      borderRadius: 16,
      justifyContent: 'center',
      marginRight: 8,
      minHeight: 44,
      paddingHorizontal: 14,
      paddingVertical: 8,
    },
    providerTabActive: {
      backgroundColor: colors.primarySoft,
    },
    providerTabText: {
      color: colors.textSecondary,
      fontSize: 13,
    },
    providerTabTextActive: {
      color: colors.primary,
      fontWeight: '600',
    },
    searchRow: {
      alignItems: 'center',
      backgroundColor: colors.surfaceAlt,
      borderColor: colors.border,
      borderRadius: 12,
      borderWidth: 1,
      flexDirection: 'row',
      marginBottom: 10,
      marginHorizontal: 16,
      minHeight: 48,
      paddingLeft: 12,
    },
    searchInput: {
      color: colors.text,
      flex: 1,
      fontSize: 15,
      minHeight: 46,
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    searchClear: {
      alignItems: 'center',
      height: 44,
      justifyContent: 'center',
      width: 44,
    },
    loadingState: {
      alignItems: 'center',
      gap: 12,
      padding: 40,
    },
    loadingText: {
      color: colors.textSecondary,
      fontSize: 14,
    },
    errorState: {
      alignItems: 'center',
      gap: 12,
      padding: 20,
    },
    retryButton: {
      alignItems: 'center',
      backgroundColor: colors.primarySoft,
      borderRadius: 12,
      justifyContent: 'center',
      minHeight: 44,
      paddingHorizontal: 18,
    },
    retryButtonText: {
      color: colors.primary,
      fontSize: 14,
      fontWeight: '700',
    },
    modelList: {
      flexShrink: 1,
      paddingHorizontal: 16,
    },
    modelItem: {
      alignItems: 'center',
      borderRadius: 10,
      flexDirection: 'row',
      gap: 10,
      justifyContent: 'space-between',
      minHeight: 64,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    modelItemSelected: {
      backgroundColor: colors.primarySoft,
    },
    modelCopy: {
      flex: 1,
      gap: 6,
      minWidth: 0,
    },
    modelTitleRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 8,
    },
    modelName: {
      color: colors.text,
      flex: 1,
      fontSize: 14,
      minWidth: 0,
    },
    modelNameSelected: {
      color: colors.primary,
      fontWeight: '600',
    },
    statusBadge: {
      backgroundColor: colors.primarySoft,
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    statusBadgeText: {
      color: colors.primary,
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 0.2,
      textTransform: 'uppercase',
    },
    capabilityRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 5,
    },
    capabilityBadge: {
      backgroundColor: colors.surfaceAlt,
      borderRadius: 999,
      paddingHorizontal: 7,
      paddingVertical: 2,
    },
    capabilityBadgeText: {
      color: colors.textSecondary,
      fontSize: 10,
      fontWeight: '600',
    },
    emptyText: {
      color: colors.textTertiary,
      fontSize: 14,
      padding: 40,
      textAlign: 'center',
    },
    closeBtn: {
      alignItems: 'center',
      borderTopColor: colors.border,
      borderTopWidth: 1,
      justifyContent: 'center',
      minHeight: 52,
      paddingHorizontal: 16,
    },
    closeBtnText: {
      color: colors.primary,
      fontSize: 16,
      fontWeight: '600',
    },
  });
