export const NATIVE_HTTP_BRIDGE_WORKER_SOURCE = [
  'function normalizeNativeHttpTimeout(timeoutMs) {',
  '  if (typeof timeoutMs !== "number" || !isFinite(timeoutMs) || timeoutMs <= 0) {',
  '    return 30000;',
  '  }',
  '  return Math.max(250, Math.min(120000, Math.trunc(timeoutMs)));',
  '}',
  '',
  'function wrapNativeHttpResponse(response, metadata) {',
  '  return {',
  '    get ok() { return response.ok; },',
  '    get status() { return response.status; },',
  '    get statusText() { return response.statusText; },',
  '    get headers() { return response.headers; },',
  '    get type() { return response.type; },',
  '    get body() { return response.body; },',
  '    get bodyUsed() { return response.bodyUsed; },',
  '    get url() { return metadata.url || ""; },',
  '    get redirected() { return Boolean(metadata.redirected); },',
  '    arrayBuffer: function() { return response.arrayBuffer(); },',
  '    blob: function() { return response.blob(); },',
  '    formData: function() { return response.formData(); },',
  '    json: function() { return response.json(); },',
  '    text: function() { return response.text(); },',
  '    clone: function() { return wrapNativeHttpResponse(response.clone(), metadata); },',
  '  };',
  '}',
  '',
  'function createNativeHttpResponse(message) {',
  '  var response = new Response(message.bodyBase64 ? decodeBase64(message.bodyBase64) : new Uint8Array(0), {',
  '    status: typeof message.status === "number" ? message.status : 200,',
  '    statusText: typeof message.statusText === "string" ? message.statusText : "",',
  '    headers: message.headers && typeof message.headers === "object" ? message.headers : {},',
  '  });',
  '  return wrapNativeHttpResponse(response, {',
  '    url: typeof message.url === "string" ? message.url : "",',
  '    redirected: Boolean(message.redirected),',
  '  });',
  '}',
  '',
  'function handleNativeHttpResponse(message) {',
  '  var pending = message && message.requestId ? pendingNativeHttpRequests[message.requestId] : null;',
  '  if (!pending) {',
  '    return;',
  '  }',
  '  if (message.error) {',
  '    pending.reject(new Error(String(message.error)));',
  '    return;',
  '  }',
  '  pending.resolve(message);',
  '}',
  '',
  'async function bridgeNativeHttpRequest(request, options) {',
  '  if (!request || typeof request.url !== "string" || !request.url) {',
  '    throw new Error("Native HTTP bridge expected a Request object.");',
  '  }',
  '',
  '  var headers = {};',
  '  if (request.headers && typeof request.headers.forEach === "function") {',
  '    request.headers.forEach(function(value, key) {',
  '      headers[String(key)] = String(value);',
  '    });',
  '  }',
  '',
  '  var bodyBase64;',
  '  if (request.method !== "GET" && request.method !== "HEAD") {',
  '    try {',
  '      var clonedRequest = typeof request.clone === "function" ? request.clone() : request;',
  '      var bodyBuffer = await clonedRequest.arrayBuffer();',
  '      if (bodyBuffer && bodyBuffer.byteLength > 0) {',
  '        bodyBase64 = encodeBase64(new Uint8Array(bodyBuffer));',
  '      }',
  '    } catch (error) {}',
  '  }',
  '',
  '  var signal = options && options.signal ? options.signal : (request.signal || null);',
  '  var timeoutMs = normalizeNativeHttpTimeout(options && typeof options.timeout_ms === "number" ? options.timeout_ms : undefined);',
  '  var requestId = "py-http-" + (++nativeHttpRequestCounter) + "-" + Math.random().toString(36).slice(2);',
  '',
  '  return await new Promise(function(resolve, reject) {',
  '    var abortListener = null;',
  '',
  '    function cleanup() {',
  '      if (signal && abortListener && typeof signal.removeEventListener === "function") {',
  '        signal.removeEventListener("abort", abortListener);',
  '      }',
  '      delete pendingNativeHttpRequests[requestId];',
  '    }',
  '',
  '    if (signal && signal.aborted) {',
  '      reject(new Error("Python HTTP request was aborted."));',
  '      return;',
  '    }',
  '',
  '    abortListener = function() {',
  '      cleanup();',
  '      self.postMessage({',
  '        type: "python-http-abort",',
  '        requestId: requestId,',
  '        reason: signal && "reason" in signal ? signal.reason : undefined,',
  '      });',
  '      reject(new Error("Python HTTP request was aborted."));',
  '    };',
  '',
  '    if (signal && typeof signal.addEventListener === "function") {',
  '      signal.addEventListener("abort", abortListener, { once: true });',
  '    }',
  '',
  '    pendingNativeHttpRequests[requestId] = {',
  '      resolve: function(message) {',
  '        cleanup();',
  '        resolve(createNativeHttpResponse(message));',
  '      },',
  '      reject: function(error) {',
  '        cleanup();',
  '        reject(error instanceof Error ? error : new Error(formatError(error)));',
  '      },',
  '    };',
  '',
  '    self.postMessage({',
  '      type: "python-http-request",',
  '      requestId: requestId,',
  '      url: request.url,',
  '      method: request.method || "GET",',
  '      headers: headers,',
  '      bodyBase64: bodyBase64,',
  '      timeoutMs: timeoutMs,',
  '    });',
  '  });',
  '}',
  '',
  'self.__kavi_native_http__ = {',
  '  is_available: function() {',
  '    return true;',
  '  },',
  '  fetch: bridgeNativeHttpRequest,',
  '};',
  '',
];
