export const NATIVE_HTTP_BRIDGE_WORKER_SOURCE = [
  /**
   * Pyodide downloads its own wheels with `fetch`, and `installControlledNetworkPrimitives`
   * replaces `self.fetch` with the user-space native bridge. From that point the package
   * loader is talking to a bridge built for Python's HTTP helpers — it cannot deliver a
   * binary wheel — so every package resolution fails, including the automatic one
   * `loadPackagesFromImports` performs for a bare `import numpy`.
   *
   * Traced on-device: five delegated workers in one run each died after three attempts at
   * `ModuleNotFoundError: No module named 'numpy'`, having tried a direct import, micropip
   * and the `packages` argument in turn. The tool description promises numpy, pandas,
   * scipy and micropip; none of them could ever load.
   *
   * Keeping the untouched `fetch` for the loader's own use fixes it. This widens nothing
   * for Python code: the escape is only open while the runtime is resolving packages,
   * before any user statement executes, and every primitive Python itself can reach still
   * goes through the bridge and its allowNetwork gate.
   */
  'var pyodidePackageLoaderFetch = null;',
  'var pyodidePackageResolutionDepth = 0;',
  '',
  'function beginPyodidePackageResolution() {',
  '  pyodidePackageResolutionDepth += 1;',
  '}',
  '',
  'function endPyodidePackageResolution() {',
  '  pyodidePackageResolutionDepth = Math.max(0, pyodidePackageResolutionDepth - 1);',
  '}',
  '',
  'function isResolvingPyodidePackages() {',
  '  return pyodidePackageResolutionDepth > 0 && typeof pyodidePackageLoaderFetch === "function";',
  '}',
  '',
  'function setPythonNetworkAccessAllowed(allowed) {',
  '  activePythonNetworkAccessAllowed = allowed === true;',
  '}',
  '',
  'function beginPythonNetworkObservation(allowNetwork) {',
  '  activePythonNetworkAccessAllowed = allowNetwork === true;',
  '  activePythonNetworkObservation = {',
  '    state: activePythonNetworkAccessAllowed ? "enabled" : "blocked",',
  '    mutationState: "none_observed",',
  '    requestCount: 0,',
  '  };',
  '}',
  '',
  'function finishPythonNetworkObservation() {',
  '  var observation = activePythonNetworkObservation || { state: "unknown", mutationState: "unknown", requestCount: 0 };',
  '  activePythonNetworkObservation = null;',
  '  activePythonNetworkAccessAllowed = false;',
  '  return observation;',
  '}',
  '',
  'function requirePythonNetworkAccess() {',
  '  if (!activePythonNetworkAccessAllowed) {',
  '    throw new Error("Python network access is disabled for this invocation. Set allowNetwork to true only when the task requires remote access.");',
  '  }',
  '}',
  '',
  'function requireInternalPythonNetworkPrimitive(name) {',
  '  requirePythonNetworkAccess();',
  '  if (activePythonNetworkObservation) {',
  '    throw new Error(String(name || "Network primitive") + " is unavailable to Python code. Use kavi.http or pyodide.http.pyfetch.");',
  '  }',
  '}',
  '',
  'function normalizeNativeHttpTimeout(timeoutMs) {',
  '  if (typeof timeoutMs !== "number" || !isFinite(timeoutMs) || timeoutMs <= 0) {',
  '    return 30000;',
  '  }',
  '  return Math.max(250, Math.min(120000, Math.trunc(timeoutMs)));',
  '}',
  '',
  'function wrapNativeHttpResponse(response, metadata) {',
  '  return {',
  '    get ok() { return response.ok; },',
  '    get status() { return response.status; },',
  '    get statusText() { return response.statusText; },',
  '    get headers() { return response.headers; },',
  '    get type() { return response.type; },',
  '    get body() { return response.body; },',
  '    get bodyUsed() { return response.bodyUsed; },',
  '    get url() { return metadata.url || ""; },',
  '    get redirected() { return Boolean(metadata.redirected); },',
  '    arrayBuffer: function() { return response.arrayBuffer(); },',
  '    blob: function() { return response.blob(); },',
  '    formData: function() { return response.formData(); },',
  '    json: function() { return response.json(); },',
  '    text: function() { return response.text(); },',
  '    clone: function() { return wrapNativeHttpResponse(response.clone(), metadata); },',
  '  };',
  '}',
  '',
  'function createNativeHttpResponse(message) {',
  '  var response = new Response(message.bodyBase64 ? decodeBase64(message.bodyBase64) : new Uint8Array(0), {',
  '    status: typeof message.status === "number" ? message.status : 200,',
  '    statusText: typeof message.statusText === "string" ? message.statusText : "",',
  '    headers: message.headers && typeof message.headers === "object" ? message.headers : {},',
  '  });',
  '  return wrapNativeHttpResponse(response, {',
  '    url: typeof message.url === "string" ? message.url : "",',
  '    redirected: Boolean(message.redirected),',
  '  });',
  '}',
  '',
  'function handleNativeHttpResponse(message) {',
  '  var pending = message && message.requestId ? pendingNativeHttpRequests[message.requestId] : null;',
  '  if (!pending) {',
  '    return;',
  '  }',
  '  if (message.error) {',
  '    pending.reject(new Error(String(message.error)));',
  '    return;',
  '  }',
  '  pending.resolve(message);',
  '}',
  '',
  'async function bridgeNativeHttpRequest(requestInput, options) {',
  '  // The runtime resolving its own wheels is not a Python network call.',
  '  if (isResolvingPyodidePackages()) {',
  '    return pyodidePackageLoaderFetch(requestInput, options);',
  '  }',
  '  requirePythonNetworkAccess();',
  '  if (activePythonNetworkObservation) {',
  '    activePythonNetworkObservation.requestCount += 1;',
  '  }',
  '',
  '  var request = requestInput;',
  '  if (!request || typeof request.url !== "string" || !request.url) {',
  '    try {',
  '      request = new Request(String(requestInput || ""), options || {});',
  '    } catch (error) {',
  '      throw new Error("Native HTTP bridge expected a valid URL or Request object.");',
  '    }',
  '  }',
  '  if (!request.url) {',
  '    throw new Error("Native HTTP bridge expected a non-empty request URL.");',
  '  }',
  '  var requestMethod = String(request.method || "GET").toUpperCase();',
  '  if (activePythonNetworkObservation && ["GET", "HEAD", "OPTIONS"].indexOf(requestMethod) === -1) {',
  '    activePythonNetworkObservation.mutationState = "possible";',
  '  }',
  '',
  '  var headers = {};',
  '  if (request.headers && typeof request.headers.forEach === "function") {',
  '    request.headers.forEach(function(value, key) {',
  '      headers[String(key)] = String(value);',
  '    });',
  '  }',
  '',
  '  var bodyBase64;',
  '  if (request.method !== "GET" && request.method !== "HEAD") {',
  '    try {',
  '      var clonedRequest = typeof request.clone === "function" ? request.clone() : request;',
  '      var bodyBuffer = await clonedRequest.arrayBuffer();',
  '      if (bodyBuffer && bodyBuffer.byteLength > 0) {',
  '        bodyBase64 = encodeBase64(new Uint8Array(bodyBuffer));',
  '      }',
  '    } catch (error) {}',
  '  }',
  '',
  '  var signal = options && options.signal ? options.signal : (request.signal || null);',
  '  var timeoutMs = normalizeNativeHttpTimeout(options && typeof options.timeout_ms === "number" ? options.timeout_ms : undefined);',
  '  var requestId = "py-http-" + (++nativeHttpRequestCounter) + "-" + Math.random().toString(36).slice(2);',
  '',
  '  return await new Promise(function(resolve, reject) {',
  '    var abortListener = null;',
  '',
  '    function cleanup() {',
  '      if (signal && abortListener && typeof signal.removeEventListener === "function") {',
  '        signal.removeEventListener("abort", abortListener);',
  '      }',
  '      delete pendingNativeHttpRequests[requestId];',
  '    }',
  '',
  '    if (signal && signal.aborted) {',
  '      reject(new Error("Python HTTP request was aborted."));',
  '      return;',
  '    }',
  '',
  '    abortListener = function() {',
  '      cleanup();',
  '      self.postMessage({',
  '        type: "python-http-abort",',
  '        requestId: requestId,',
  '        reason: signal && "reason" in signal ? signal.reason : undefined,',
  '      });',
  '      reject(new Error("Python HTTP request was aborted."));',
  '    };',
  '',
  '    if (signal && typeof signal.addEventListener === "function") {',
  '      signal.addEventListener("abort", abortListener, { once: true });',
  '    }',
  '',
  '    pendingNativeHttpRequests[requestId] = {',
  '      resolve: function(message) {',
  '        cleanup();',
  '        resolve(createNativeHttpResponse(message));',
  '      },',
  '      reject: function(error) {',
  '        cleanup();',
  '        reject(error instanceof Error ? error : new Error(formatError(error)));',
  '      },',
  '    };',
  '',
  '    self.postMessage({',
  '      type: "python-http-request",',
  '      requestId: requestId,',
  '      url: request.url,',
  '      method: requestMethod,',
  '      headers: headers,',
  '      bodyBase64: bodyBase64,',
  '      timeoutMs: timeoutMs,',
  '    });',
  '  });',
  '}',
  '',
  'function createControlledNetworkConstructor(name, originalConstructor) {',
  '  return function() {',
  '    requireInternalPythonNetworkPrimitive(name);',
  '    return Reflect.construct(originalConstructor, Array.prototype.slice.call(arguments));',
  '  };',
  '}',
  '',
  'function installControlledNetworkPrimitives() {',
  '  if (controlledNetworkPrimitivesInstalled) {',
  '    return;',
  '  }',
  '  controlledNetworkPrimitivesInstalled = true;',
  '  pyodidePackageLoaderFetch = typeof self.fetch === "function" ? self.fetch.bind(self) : null;',
  '  self.fetch = bridgeNativeHttpRequest;',
  '',
  '  ["XMLHttpRequest", "WebSocket", "EventSource", "WebTransport", "Worker", "SharedWorker", "RTCPeerConnection", "webkitRTCPeerConnection"].forEach(function(name) {',
  '    var originalConstructor = self[name];',
  '    if (typeof originalConstructor !== "function") {',
  '      return;',
  '    }',
  '    try {',
  '      self[name] = createControlledNetworkConstructor(name, originalConstructor);',
  '    } catch (error) {}',
  '  });',
  '',
  '  if (typeof self.importScripts === "function") {',
  '    var originalImportScripts = self.importScripts.bind(self);',
  '    try {',
  '      self.importScripts = function() {',
  '        requireInternalPythonNetworkPrimitive("importScripts");',
  '        return originalImportScripts.apply(self, arguments);',
  '      };',
  '    } catch (error) {}',
  '  }',
  '}',
  '',
  'self.__kavi_native_http__ = {',
  '  is_available: function() {',
  '    return activePythonNetworkAccessAllowed;',
  '  },',
  '  fetch: bridgeNativeHttpRequest,',
  '};',
  '',
];
