export const PYTHON_RUNTIME_ENVIRONMENT_HELPER_SOURCE = [
  'import importlib',
  'import json as _kavi_json',
  'import os',
  'import builtins',
  'import pyodide.http as _kavi_pyodide_http',
  'import sys',
  'import types as _kavi_types',
  'import traceback',
  'import warnings',
  'from js import __kavi_native_http__, __kavi_workflow_bridge__',
  'from pyodide.code import eval_code_async',
  'from pyodide.http import pyfetch as _kavi_browser_pyfetch',
  'from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit',
  '',
  'def _kavi_stringify_result(value):',
  '    if value is None:',
  '        return None',
  '    rendered = str(value)',
  '    if not rendered or rendered == "None":',
  '        return None',
  '    return rendered',
  '',
  'def _kavi_serialize_execution(result_value=None, error=None):',
  '    return _kavi_json.dumps({',
  '        "result_text": _kavi_stringify_result(result_value),',
  '        "error": error,',
  '    }, ensure_ascii=False)',
  '',
  'def _kavi_clear_workspace_modules(workspace_root: str) -> None:',
  '    normalized_root = os.path.normpath(workspace_root)',
  '    prefix = normalized_root + os.sep',
  '    for module_name, module in list(sys.modules.items()):',
  '        module_path = getattr(module, "__file__", None)',
  '        if not module_path:',
  '            continue',
  '        try:',
  '            normalized_path = os.path.normpath(module_path)',
  '        except Exception:',
  '            continue',
  '        if normalized_path == normalized_root or normalized_path.startswith(prefix):',
  '            del sys.modules[module_name]',
  '',
  'def _kavi_prepare_execution(workspace_root: str) -> None:',
  '    _kavi_clear_workspace_modules(workspace_root)',
  '    importlib.invalidate_caches()',
  '',
  'def _kavi_prepare_sys_path(workspace_root: str, working_directory: str, script_dir: str | None = None) -> None:',
  '    for candidate in (workspace_root, working_directory, script_dir):',
  '        if not candidate:',
  '            continue',
  '        normalized = os.path.normpath(candidate)',
  '        if normalized and normalized not in sys.path:',
  '            sys.path.insert(0, normalized)',
  '',
];

export const PYTHON_RUNTIME_EXECUTION_HELPER_SOURCE = [
  'async def _kavi_execute_inline(code: str, working_directory: str, workspace_root: str) -> str:',
  '    namespace = {',
  '        "__name__": "__main__",',
  '        "__file__": "<inline>",',
  '        "__package__": None,',
  '        "__builtins__": __builtins__,',
  '    }',
  '    previous_path = sys.path[:]',
  '    previous_cwd = os.getcwd()',
  '    try:',
  '        os.chdir(working_directory)',
  '        _kavi_prepare_execution(workspace_root)',
  '        _kavi_prepare_sys_path(workspace_root, working_directory)',
  '        with warnings.catch_warnings():',
  '            warnings.simplefilter("ignore", SyntaxWarning)',
  '            result_value = await eval_code_async(',
  '                code,',
  '                globals=namespace,',
  '                locals=namespace,',
  '                filename="<inline>",',
  '                return_mode="last_expr",',
  '            )',
  '        return _kavi_serialize_execution(result_value=result_value)',
  '    except BaseException:',
  '        return _kavi_serialize_execution(error=traceback.format_exc())',
  '    finally:',
  '        sys.path[:] = previous_path',
  '        os.chdir(previous_cwd)',
  '',
  'async def _kavi_execute_script(script_path: str, argv: list[str], working_directory: str, workspace_root: str) -> str:',
  '    previous_argv = sys.argv[:]',
  '    previous_path = sys.path[:]',
  '    previous_cwd = os.getcwd()',
  '    script_dir = os.path.dirname(script_path) or working_directory',
  '    namespace = {',
  '        "__name__": "__main__",',
  '        "__file__": script_path,',
  '        "__package__": None,',
  '        "__builtins__": __builtins__,',
  '    }',
  '    try:',
  '        os.chdir(working_directory)',
  '        _kavi_prepare_execution(workspace_root)',
  '        _kavi_prepare_sys_path(workspace_root, working_directory, script_dir)',
  '        sys.argv = [script_path, *argv]',
  '        with open(script_path, "r", encoding="utf-8") as handle:',
  '            source = handle.read()',
  '        with warnings.catch_warnings():',
  '            warnings.simplefilter("ignore", SyntaxWarning)',
  '            await eval_code_async(',
  '                source,',
  '                globals=namespace,',
  '                locals=namespace,',
  '                filename=script_path,',
  '                return_mode="none",',
  '            )',
  '        return _kavi_serialize_execution()',
  '    except BaseException:',
  '        return _kavi_serialize_execution(error=traceback.format_exc())',
  '    finally:',
  '        sys.argv = previous_argv',
  '        sys.path[:] = previous_path',
  '        os.chdir(previous_cwd)',
];
