export const PYTHON_HTTP_BRIDGE_HELPER_SOURCE = [
  'async def _kavi_native_pyfetch(request, /, *, fetcher=None, **kwargs):',
  '    resolved_fetcher = fetcher if fetcher is not None else getattr(__kavi_native_http__, "fetch", None)',
  '    if resolved_fetcher is None:',
  '        raise RuntimeError("Native HTTP bridge is not available.")',
  '    return await _kavi_browser_pyfetch(request, fetcher=resolved_fetcher, **kwargs)',
  '',
  'def _kavi_normalize_timeout_ms(timeout=None, timeout_ms=None, timeoutMs=None):',
  '    explicit_timeout_ms = timeout_ms if timeout_ms is not None else timeoutMs',
  '    if explicit_timeout_ms is not None:',
  '        return int(explicit_timeout_ms)',
  '    if timeout is None:',
  '        return None',
  '    return max(1, int(float(timeout) * 1000))',
  '',
  'def _kavi_normalize_query_params(params):',
  '    if params is None:',
  '        return []',
  '    if isinstance(params, dict):',
  '        items = params.items()',
  '    elif isinstance(params, (list, tuple)):',
  '        items = params',
  '    else:',
  '        raise TypeError("params must be a dict or a list of key/value pairs.")',
  '',
  '    normalized = []',
  '    for item in items:',
  '        try:',
  '            key, value = item',
  '        except Exception as exc:',
  '            raise TypeError("params must be a dict or a list of key/value pairs.") from exc',
  '        if value is None:',
  '            continue',
  '        if isinstance(value, (list, tuple)):',
  '            for inner in value:',
  '                if inner is None:',
  '                    continue',
  '                normalized.append((str(key), str(inner)))',
  '        else:',
  '            normalized.append((str(key), str(value)))',
  '    return normalized',
  '',
  'def _kavi_merge_query_params(url: str, params=None) -> str:',
  '    normalized = _kavi_normalize_query_params(params)',
  '    if not normalized:',
  '        return url',
  '    split = urlsplit(url)',
  '    combined = parse_qsl(split.query, keep_blank_values=True)',
  '    combined.extend(normalized)',
  '    return urlunsplit((split.scheme, split.netloc, split.path, urlencode(combined, doseq=True), split.fragment))',
  '',
  'class _KaviHttpResponse:',
  '    def __init__(self, response):',
  '        self._response = response',
  '',
  '    @property',
  '    def ok(self):',
  '        return bool(getattr(self._response, "ok", False))',
  '',
  '    @property',
  '    def status(self):',
  '        return int(getattr(self._response, "status", 0) or 0)',
  '',
  '    @property',
  '    def status_code(self):',
  '        return self.status',
  '',
  '    @property',
  '    def status_text(self):',
  '        return str(getattr(self._response, "statusText", "") or "")',
  '',
  '    @property',
  '    def headers(self):',
  '        return getattr(self._response, "headers", None)',
  '',
  '    @property',
  '    def url(self):',
  '        return str(getattr(self._response, "url", "") or "")',
  '',
  '    @property',
  '    def redirected(self):',
  '        return bool(getattr(self._response, "redirected", False))',
  '',
  '    async def text(self):',
  '        return await self._response.text()',
  '',
  '    async def json(self):',
  '        return await self._response.json()',
  '',
  '    async def array_buffer(self):',
  '        return await self._response.arrayBuffer()',
  '',
  '    def raise_for_status(self):',
  '        if self.ok:',
  '            return self',
  '        detail = f"HTTP {self.status_code}"',
  '        if self.status_text:',
  '            detail += f" {self.status_text}"',
  '        if self.url:',
  '            detail += f" for {self.url}"',
  '        raise RuntimeError(detail)',
  '',
  '    def require_success(self):',
  '        return self.raise_for_status()',
  '',
  'async def _kavi_http_request(',
  '    url: str,',
  '    *,',
  '    method: str = "GET",',
  '    headers=None,',
  '    data=None,',
  '    json=None,',
  '    params=None,',
  '    timeout=None,',
  '    timeout_ms: int | None = None,',
  '    timeoutMs: int | None = None,',
  '    **kwargs,',
  '):',
  '    request_url = _kavi_merge_query_params(url, params)',
  '    request_headers = {}',
  '    if headers:',
  '        request_headers = {str(key): str(value) for key, value in dict(headers).items()}',
  '    if json is not None and data is not None:',
  '        raise ValueError("Pass either data or json, not both.")',
  '    body = data',
  '    if json is not None:',
  '        body = _kavi_json.dumps(json, ensure_ascii=False)',
  '        request_headers.setdefault("Content-Type", "application/json")',
  '    request_kwargs = dict(kwargs)',
  '    request_kwargs["method"] = str(method or "GET")',
  '    if request_headers:',
  '        request_kwargs["headers"] = request_headers',
  '    if body is not None:',
  '        request_kwargs["body"] = body',
  '    timeout_value = _kavi_normalize_timeout_ms(timeout=timeout, timeout_ms=timeout_ms, timeoutMs=timeoutMs)',
  '    if timeout_value is not None:',
  '        request_kwargs["timeout_ms"] = int(timeout_value)',
  '    response = await _kavi_native_pyfetch(request_url, **request_kwargs)',
  '    return _KaviHttpResponse(response)',
  '',
  'class _KaviHttpClient:',
  '    def is_available(self) -> bool:',
  '        try:',
  '            return bool(getattr(__kavi_native_http__, "is_available", lambda: False)())',
  '        except Exception:',
  '            return False',
  '',
  '    async def fetch(self, url: str, **kwargs):',
  '        return await _kavi_http_request(url, **kwargs)',
  '',
  '    async def request(self, url: str, **kwargs):',
  '        return await _kavi_http_request(url, **kwargs)',
  '',
  '    async def get(self, url: str, **kwargs):',
  '        return await _kavi_http_request(url, method="GET", **kwargs)',
  '',
  '    async def post(self, url: str, **kwargs):',
  '        return await _kavi_http_request(url, method="POST", **kwargs)',
  '',
  '    async def put(self, url: str, **kwargs):',
  '        return await _kavi_http_request(url, method="PUT", **kwargs)',
  '',
  '    async def patch(self, url: str, **kwargs):',
  '        return await _kavi_http_request(url, method="PATCH", **kwargs)',
  '',
  '    async def delete(self, url: str, **kwargs):',
  '        return await _kavi_http_request(url, method="DELETE", **kwargs)',
  '',
  '    async def head(self, url: str, **kwargs):',
  '        return await _kavi_http_request(url, method="HEAD", **kwargs)',
  '',
  '    async def options(self, url: str, **kwargs):',
  '        return await _kavi_http_request(url, method="OPTIONS", **kwargs)',
  '',
  '    async def get_text(self, url: str, **kwargs):',
  '        response = await self.get(url, **kwargs)',
  '        response.raise_for_status()',
  '        return await response.text()',
  '',
  '    async def get_json(self, url: str, **kwargs):',
  '        response = await self.get(url, **kwargs)',
  '        response.raise_for_status()',
  '        return await response.json()',
  '',
  '    async def post_text(self, url: str, **kwargs):',
  '        response = await self.post(url, **kwargs)',
  '        response.raise_for_status()',
  '        return await response.text()',
  '',
  '    async def post_json(self, url: str, **kwargs):',
  '        response = await self.post(url, **kwargs)',
  '        response.raise_for_status()',
  '        return await response.json()',
  '',
  '    async def request_text(self, url: str, **kwargs):',
  '        response = await self.request(url, **kwargs)',
  '        response.raise_for_status()',
  '        return await response.text()',
  '',
  '    async def request_json(self, url: str, **kwargs):',
  '        response = await self.request(url, **kwargs)',
  '        response.raise_for_status()',
  '        return await response.json()',
  '',
  '_kavi_pyodide_http.pyfetch = _kavi_native_pyfetch',
  '',
  'class _KaviBridge:',
  '    def __init__(self, http_module):',
  '        self.http = http_module',
  '',
  '_kavi_http_client = _KaviHttpClient()',
  '_kavi_http_module = _kavi_types.ModuleType("kavi.http")',
  '_kavi_http_module.__package__ = "kavi"',
  '_kavi_http_module.__all__ = ["Response", "fetch", "request", "get", "post", "put", "patch", "delete", "head", "options", "get_text", "get_json", "post_text", "post_json", "request_text", "request_json", "is_available"]',
  '_kavi_http_module.Response = _KaviHttpResponse',
  '_kavi_http_module.fetch = _kavi_http_client.fetch',
  '_kavi_http_module.request = _kavi_http_client.request',
  '_kavi_http_module.get = _kavi_http_client.get',
  '_kavi_http_module.post = _kavi_http_client.post',
  '_kavi_http_module.put = _kavi_http_client.put',
  '_kavi_http_module.patch = _kavi_http_client.patch',
  '_kavi_http_module.delete = _kavi_http_client.delete',
  '_kavi_http_module.head = _kavi_http_client.head',
  '_kavi_http_module.options = _kavi_http_client.options',
  '_kavi_http_module.get_text = _kavi_http_client.get_text',
  '_kavi_http_module.get_json = _kavi_http_client.get_json',
  '_kavi_http_module.post_text = _kavi_http_client.post_text',
  '_kavi_http_module.post_json = _kavi_http_client.post_json',
  '_kavi_http_module.request_text = _kavi_http_client.request_text',
  '_kavi_http_module.request_json = _kavi_http_client.request_json',
  '_kavi_http_module.is_available = _kavi_http_client.is_available',
  '_kavi_bridge = _KaviBridge(_kavi_http_module)',
  '_kavi_module = _kavi_types.ModuleType("kavi")',
  '_kavi_module.__path__ = []',
  '_kavi_module.__all__ = ["http"]',
  '_kavi_module.http = _kavi_http_module',
  'sys.modules["kavi.http"] = _kavi_http_module',
  'sys.modules["kavi"] = _kavi_module',
  'builtins.kavi = _kavi_module',
  '',
];
