export const RUNTIME_ENVIRONMENT_WORKER_SOURCE = [
  'function formatError(error) {',
  '  return error && error.message ? error.message : String(error);',
  '}',
  '',
  'function appendSegment(base, segment) {',
  '  if (!segment) {',
  '    return base;',
  '  }',
  '  if (!base) {',
  '    return segment;',
  '  }',
  '  return base + (base.endsWith("\\n") ? "" : "\\n") + segment;',
  '}',
  '',
  'function beginCapture() {',
  "  activeCapture = { stdout: '', stderr: '' };",
  '  return activeCapture;',
  '}',
  '',
  'function finishCapture() {',
  "  var capture = activeCapture || { stdout: '', stderr: '' };",
  '  activeCapture = null;',
  '  return capture;',
  '}',
  '',
  'function combineExecutionOutput(capture, resultText, hasError) {',
  "  var output = '';",
  '  output = appendSegment(output, capture && capture.stdout ? capture.stdout : "");',
  '  output = appendSegment(output, capture && capture.stderr ? capture.stderr : "");',
  '  output = appendSegment(output, resultText || "");',
  '  if (!output && !hasError) {',
  '    return "(no output)";',
  '  }',
  '  return output;',
  '}',
  '',
  'function onStdout(value) {',
  '  if (!activeCapture) {',
  '    return;',
  '  }',
  '  activeCapture.stdout = appendSegment(activeCapture.stdout, String(value || ""));',
  '}',
  '',
  'function onStderr(value) {',
  '  if (!activeCapture) {',
  '    return;',
  '  }',
  '  activeCapture.stderr = appendSegment(activeCapture.stderr, String(value || ""));',
  '}',
  '',
  'function normalizeWorkspaceRelativePath(input) {',
  '  var normalized = String(input || "")',
  '    .replace(/\\\\/g, "/")',
  '    .replace(/^\\/+/, "");',
  '',
  '  var segments = [];',
  '  normalized.split("/").forEach(function(segment) {',
  '    var trimmed = segment.trim();',
  '    if (!trimmed || trimmed === ".") {',
  '      return;',
  '    }',
  '    if (trimmed === "..") {',
  '      throw new Error(\'Workspace paths must not contain ".." segments.\');',
  '    }',
  '    segments.push(trimmed);',
  '  });',
  '',
  '  return segments.join("/");',
  '}',
  '',
  'function toWorkspaceFsPath(relativePath) {',
  '  var normalized = normalizeWorkspaceRelativePath(relativePath);',
  '  return normalized ? WORKSPACE_ROOT + "/" + normalized : WORKSPACE_ROOT;',
  '}',
  '',
];
