export const WORKFLOW_BRIDGE_WORKER_SOURCE = [
  'function truncateBridgeText(value, maxChars) {',
  '  var normalized = typeof value === "string" ? value.trim() : "";',
  '  if (!normalized) {',
  '    return undefined;',
  '  }',
  '  if (normalized.length <= maxChars) {',
  '    return normalized;',
  '  }',
  '  return normalized.slice(0, Math.max(1, maxChars - 3)).trimEnd() + "...";',
  '}',
  '',
  'function normalizeBridgeEnum(value, allowedValues) {',
  '  var normalized = truncateBridgeText(value, 40);',
  '  if (!normalized) {',
  '    return undefined;',
  '  }',
  '  normalized = normalized.toLowerCase();',
  '  return allowedValues.indexOf(normalized) >= 0 ? normalized : undefined;',
  '}',
  '',
  'function normalizeBridgeWorkspacePath(value) {',
  '  if (typeof value !== "string") {',
  '    return undefined;',
  '  }',
  '  var normalized = String(value);',
  '  while (normalized.indexOf("\\\\") >= 0) {',
  '    normalized = normalized.replace("\\\\", "/");',
  '  }',
  '  while (normalized.charAt(0) === "/") {',
  '    normalized = normalized.slice(1);',
  '  }',
  '  var segments = [];',
  '  var invalid = false;',
  '  normalized.split("/").forEach(function(segment) {',
  '    var trimmed = segment.trim();',
  '    if (!trimmed || invalid) {',
  '      return;',
  '    }',
  '    if (trimmed === "." || trimmed === "..") {',
  '      invalid = true;',
  '      return;',
  '    }',
  '    segments.push(trimmed);',
  '  });',
  '  if (invalid || segments.length === 0) {',
  '    return undefined;',
  '  }',
  '  normalized = segments.join("/");',
  '  return normalized.length <= MAX_WORKFLOW_BRIDGE_OPTIONAL_TEXT_CHARS',
  '    ? normalized',
  '    : normalized.slice(0, Math.max(1, MAX_WORKFLOW_BRIDGE_OPTIONAL_TEXT_CHARS - 3)).trimEnd() + "...";',
  '}',
  '',
  'function normalizeBridgeTags(tags) {',
  '  if (!Array.isArray(tags)) {',
  '    return undefined;',
  '  }',
  '  var normalized = [];',
  '  var seen = Object.create(null);',
  '  for (var index = 0; index < tags.length; index++) {',
  '    var value = truncateBridgeText(tags[index], MAX_WORKFLOW_BRIDGE_OPTIONAL_TEXT_CHARS);',
  '    if (!value || seen[value]) {',
  '      continue;',
  '    }',
  '    seen[value] = true;',
  '    normalized.push(value);',
  '    if (normalized.length >= MAX_WORKFLOW_BRIDGE_TAGS) {',
  '      break;',
  '    }',
  '  }',
  '  return normalized.length > 0 ? normalized : undefined;',
  '}',
  '',
  'function normalizeWorkflowBridgeEntry(entry) {',
  '  if (!entry || typeof entry !== "object" || Array.isArray(entry)) {',
  '    return null;',
  '  }',
  '  var kind = normalizeBridgeEnum(entry.kind, ALLOWED_WORKFLOW_BRIDGE_KINDS);',
  '  var content = truncateBridgeText(entry.content, MAX_WORKFLOW_BRIDGE_CONTENT_CHARS);',
  '  if (!kind || !content) {',
  '    return null;',
  '  }',
  '  var normalized = { kind: kind, content: content };',
  '  var id = truncateBridgeText(entry.id, MAX_WORKFLOW_BRIDGE_OPTIONAL_TEXT_CHARS);',
  '  if (id) normalized.id = id;',
  '  var status = normalizeBridgeEnum(entry.status, ALLOWED_WORKFLOW_BRIDGE_STATUSES);',
  '  if (status) normalized.status = status;',
  '  var recorder = normalizeBridgeEnum(entry.recorder, ALLOWED_WORKFLOW_BRIDGE_RECORDERS);',
  '  if (recorder) normalized.recorder = recorder;',
  '  var title = truncateBridgeText(entry.title, MAX_WORKFLOW_BRIDGE_TITLE_CHARS);',
  '  if (title) normalized.title = title;',
  '  var dedupeKey = truncateBridgeText(entry.dedupeKey, MAX_WORKFLOW_BRIDGE_OPTIONAL_TEXT_CHARS);',
  '  if (dedupeKey) normalized.dedupeKey = dedupeKey;',
  '  var sourceName = truncateBridgeText(entry.sourceName, MAX_WORKFLOW_BRIDGE_OPTIONAL_TEXT_CHARS);',
  '  if (sourceName) normalized.sourceName = sourceName;',
  '  var sourceUri = truncateBridgeText(entry.sourceUri, MAX_WORKFLOW_BRIDGE_OPTIONAL_TEXT_CHARS);',
  '  if (sourceUri) normalized.sourceUri = sourceUri;',
  '  var toolName = truncateBridgeText(entry.toolName, MAX_WORKFLOW_BRIDGE_OPTIONAL_TEXT_CHARS);',
  '  if (toolName) normalized.toolName = toolName;',
  '  var workerSessionId = truncateBridgeText(entry.workerSessionId, MAX_WORKFLOW_BRIDGE_OPTIONAL_TEXT_CHARS);',
  '  if (workerSessionId) normalized.workerSessionId = workerSessionId;',
  '  var artifactWorkspacePath = normalizeBridgeWorkspacePath(entry.artifactWorkspacePath);',
  '  if (artifactWorkspacePath) normalized.artifactWorkspacePath = artifactWorkspacePath;',
  '  var tags = normalizeBridgeTags(entry.tags);',
  '  if (tags) normalized.tags = tags;',
  '  if (typeof entry.createdAt === "number" && isFinite(entry.createdAt)) normalized.createdAt = entry.createdAt;',
  '  if (typeof entry.updatedAt === "number" && isFinite(entry.updatedAt)) normalized.updatedAt = entry.updatedAt;',
  '  return normalized;',
  '}',
  '',
  'function normalizeWorkflowBridgeEntries(entries, maxEntries) {',
  '  if (!Array.isArray(entries)) {',
  '    return [];',
  '  }',
  '  return entries',
  '    .map(normalizeWorkflowBridgeEntry)',
  '    .filter(Boolean)',
  '    .slice(-Math.max(1, maxEntries || MAX_WORKFLOW_BRIDGE_ENTRIES));',
  '}',
  '',
  'function configureWorkflowBridge(config) {',
  '  var evidence = normalizeWorkflowBridgeEntries(config && Array.isArray(config.evidence) ? config.evidence : [], MAX_WORKFLOW_BRIDGE_ENTRIES);',
  '  activeWorkflowBridgeState = {',
  '    evidence: evidence.slice(),',
  '    emittedEvidence: [],',
  '  };',
  '}',
  '',
  'function collectWorkflowBridgeResult() {',
  '  if (!activeWorkflowBridgeState || activeWorkflowBridgeState.emittedEvidence.length === 0) {',
  '    return undefined;',
  '  }',
  '  return {',
  '    emittedEvidence: activeWorkflowBridgeState.emittedEvidence.slice(-MAX_WORKFLOW_BRIDGE_ENTRIES),',
  '  };',
  '}',
  '',
  'function resetWorkflowBridge() {',
  '  activeWorkflowBridgeState = null;',
  '}',
  '',
  'self.__kavi_workflow_bridge__ = {',
  '  is_enabled: function() {',
  '    return !!activeWorkflowBridgeState;',
  '  },',
  '  get_state_json: function() {',
  '    return JSON.stringify(activeWorkflowBridgeState ? activeWorkflowBridgeState.evidence : []);',
  '  },',
  '  record_entries_json: function(payload) {',
  '    if (!activeWorkflowBridgeState) {',
  '      return 0;',
  '    }',
  '    var parsed;',
  '    try {',
  '      parsed = JSON.parse(String(payload || "[]"));',
  '    } catch (error) {',
  '      return 0;',
  '    }',
  '    var entries = normalizeWorkflowBridgeEntries(Array.isArray(parsed) ? parsed : [parsed], MAX_WORKFLOW_BRIDGE_ENTRIES);',
  '    if (entries.length === 0) {',
  '      return 0;',
  '    }',
  '    Array.prototype.push.apply(activeWorkflowBridgeState.emittedEvidence, entries);',
  '    activeWorkflowBridgeState.emittedEvidence = activeWorkflowBridgeState.emittedEvidence.slice(-MAX_WORKFLOW_BRIDGE_ENTRIES);',
  '    Array.prototype.push.apply(activeWorkflowBridgeState.evidence, entries);',
  '    activeWorkflowBridgeState.evidence = activeWorkflowBridgeState.evidence.slice(-MAX_WORKFLOW_BRIDGE_ENTRIES);',
  '    return entries.length;',
  '  },',
  '};',
  '',
];
