export const WORKSPACE_ENVIRONMENT_WORKER_SOURCE = [
  'function parseExecutionResult(result) {',
  '  if (typeof result === "string") {',
  '    try {',
  '      return JSON.parse(result);',
  '    } catch (error) {',
  '      return { result_text: result || null, error: null };',
  '    }',
  '  }',
  '  return result && typeof result === "object"',
  '    ? result',
  '    : { result_text: null, error: null };',
  '}',
  '',
  'function ensureDir(fsPath) {',
  '  try {',
  '    pyodide.FS.mkdirTree(fsPath);',
  '  } catch (error) {',
  '    // mkdirTree is effectively idempotent for our usage.',
  '  }',
  '}',
  '',
  'function removeFsPath(fsPath) {',
  '  var stat;',
  '  try {',
  '    stat = pyodide.FS.stat(fsPath);',
  '  } catch (error) {',
  '    return;',
  '  }',
  '',
  '  if (pyodide.FS.isDir(stat.mode)) {',
  '    var entries = pyodide.FS.readdir(fsPath).filter(function(entry) {',
  '      return entry !== "." && entry !== "..";',
  '    });',
  '    for (var index = 0; index < entries.length; index++) {',
  '      removeFsPath(fsPath + "/" + entries[index]);',
  '    }',
  '    pyodide.FS.rmdir(fsPath);',
  '    return;',
  '  }',
  '',
  '  pyodide.FS.unlink(fsPath);',
  '}',
  '',
  'function resetWorkspaceRoot() {',
  '  ensureDir(WORKSPACE_ROOT);',
  '  var entries = pyodide.FS.readdir(WORKSPACE_ROOT).filter(function(entry) {',
  '    return entry !== "." && entry !== "..";',
  '  });',
  '  for (var index = 0; index < entries.length; index++) {',
  '    removeFsPath(WORKSPACE_ROOT + "/" + entries[index]);',
  '  }',
  '}',
  '',
  'function decodeBase64(base64) {',
  '  var normalized = String(base64 || "").replace(/\\s+/g, "");',
  '  var binary = atob(normalized);',
  '  var bytes = new Uint8Array(binary.length);',
  '  for (var index = 0; index < binary.length; index++) {',
  '    bytes[index] = binary.charCodeAt(index);',
  '  }',
  '  return bytes;',
  '}',
  '',
  'function encodeBase64(bytes) {',
  "  var binary = '';",
  '  var chunkSize = 0x8000;',
  '  for (var index = 0; index < bytes.length; index += chunkSize) {',
  '    var chunk = bytes.subarray(index, Math.min(index + chunkSize, bytes.length));',
  '    binary += String.fromCharCode.apply(null, Array.prototype.slice.call(chunk));',
  '  }',
  '  return btoa(binary);',
  '}',
  '',
];

export const WORKSPACE_MOUNT_WORKER_SOURCE = [
  'function mountWorkspaceFiles(files) {',
  '  resetWorkspaceRoot();',
  '',
  '  for (var index = 0; index < files.length; index++) {',
  '    var file = files[index];',
  '    var fullPath = toWorkspaceFsPath(file.path);',
  '    var lastSlash = fullPath.lastIndexOf("/");',
  '    var parent = lastSlash > 0 ? fullPath.slice(0, lastSlash) : WORKSPACE_ROOT;',
  '    ensureDir(parent);',
  '    pyodide.FS.writeFile(fullPath, decodeBase64(file.contentBase64), { encoding: "binary" });',
  '  }',
  '}',
  '',
  'function collectWorkspaceFiles(fsPath, prefix) {',
  '  var collected = [];',
  '  var entries = pyodide.FS.readdir(fsPath).filter(function(entry) {',
  '    return entry !== "." && entry !== "..";',
  '  });',
  '',
  '  for (var index = 0; index < entries.length; index++) {',
  '    var name = entries[index];',
  '    var childPath = fsPath + "/" + name;',
  '    var relativePath = prefix ? prefix + "/" + name : name;',
  '    var stat = pyodide.FS.stat(childPath);',
  '',
  '    if (pyodide.FS.isDir(stat.mode)) {',
  '      collected = collected.concat(collectWorkspaceFiles(childPath, relativePath));',
  '      continue;',
  '    }',
  '',
  '    collected.push({',
  '      path: relativePath,',
  '      contentBase64: encodeBase64(pyodide.FS.readFile(childPath, { encoding: "binary" })),',
  '    });',
  '  }',
  '',
  '  return collected;',
  '}',
  '',
  'function indexWorkspaceFiles(files) {',
  '  var indexed = {};',
  '  for (var index = 0; index < files.length; index++) {',
  '    indexed[files[index].path] = files[index].contentBase64;',
  '  }',
  '  return indexed;',
  '}',
  '',
  'function clearInjectedEnv() {',
  '  if (injectedEnvKeys.length === 0) {',
  '    return;',
  '  }',
  '',
  "  var resetLines = ['import os'];",
  '  for (var index = 0; index < injectedEnvKeys.length; index++) {',
  '    resetLines.push("os.environ.pop(" + JSON.stringify(injectedEnvKeys[index]) + ", None)");',
  '  }',
  '  pyodide.runPython(resetLines.join("\\n"));',
  '  injectedEnvKeys = [];',
  '}',
  '',
];
