import { StyleSheet } from 'react-native';
import type { AppPalette } from '../../theme/useAppTheme';

export const createMcpStatusStyles = (colors: AppPalette) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: colors.header,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.text,
    },
    tabRow: {
      flexDirection: 'row',
      paddingHorizontal: 16,
      paddingTop: 12,
      gap: 8,
    },
    tabBtn: {
      flex: 1,
      borderRadius: 10,
      paddingVertical: 10,
      alignItems: 'center',
      backgroundColor: colors.surfaceAlt,
      borderWidth: 1,
      borderColor: colors.border,
    },
    tabBtnActive: {
      backgroundColor: colors.primarySoft,
      borderColor: colors.primary,
    },
    tabText: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    tabTextActive: {
      color: colors.primary,
    },
    installingBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginHorizontal: 16,
      marginTop: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.primary,
      backgroundColor: colors.primarySoft,
    },
    installingBannerText: {
      flex: 1,
      fontSize: 13,
      fontWeight: '600',
      color: colors.text,
    },
    list: {
      padding: 16,
      flexGrow: 1,
    },
    browseContainer: {
      flex: 1,
    },
    searchRow: {
      flexDirection: 'row',
      gap: 8,
      paddingHorizontal: 16,
      paddingTop: 16,
    },
    searchInput: {
      backgroundColor: colors.inputBackground,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 10,
      paddingHorizontal: 14,
      paddingVertical: 10,
      fontSize: 15,
      color: colors.text,
    },
    searchBtn: {
      width: 44,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySoft,
      borderWidth: 1,
      borderColor: colors.primary,
    },
    card: {
      backgroundColor: colors.surface,
      borderRadius: 12,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    serverName: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.text,
      flex: 1,
    },
    stateBadge: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 8,
    },
    stateText: {
      fontSize: 11,
      fontWeight: '600',
      textTransform: 'capitalize',
    },
    errorText: {
      fontSize: 12,
      color: colors.danger,
      marginTop: 8,
    },
    description: {
      fontSize: 13,
      color: colors.textSecondary,
      marginTop: 10,
      lineHeight: 18,
    },
    metaChipRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      marginTop: 10,
    },
    metaChip: {
      backgroundColor: colors.surfaceAlt,
      borderWidth: 1,
      borderColor: colors.subtleBorder,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 999,
    },
    metaChipText: {
      fontSize: 11,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    metadataText: {
      fontSize: 12,
      color: colors.textTertiary,
      marginTop: 8,
      lineHeight: 17,
    },
    toolsSection: {
      marginTop: 12,
    },
    toolsLabel: {
      fontSize: 12,
      color: colors.textTertiary,
      marginBottom: 6,
    },
    toolsList: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
    },
    toolChip: {
      backgroundColor: colors.surfaceAlt,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
    },
    toolChipText: {
      fontSize: 11,
      color: colors.textSecondary,
      fontFamily: 'monospace',
    },
    toolsMore: {
      fontSize: 11,
      color: colors.textTertiary,
      alignSelf: 'center',
    },
    installBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 8,
      backgroundColor: colors.primarySoft,
    },
    installBtnText: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.primary,
    },
    remoteMetaRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 12,
    },
    remoteMetaText: {
      fontSize: 12,
      color: colors.textTertiary,
    },
    reconnectBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 8,
      backgroundColor: colors.primarySoft,
    },
    reconnectText: {
      fontSize: 13,
      color: colors.primary,
      fontWeight: '500',
    },
    actionRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 12,
    },
    secondaryActionBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 8,
      backgroundColor: colors.surfaceAlt,
      borderWidth: 1,
      borderColor: colors.border,
    },
    secondaryActionText: {
      fontSize: 13,
      color: colors.textSecondary,
      fontWeight: '500',
    },
    empty: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 40,
      marginTop: 60,
    },
    emptyTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: colors.textSecondary,
      marginTop: 16,
    },
    emptyText: {
      fontSize: 14,
      color: colors.textTertiary,
      textAlign: 'center',
      marginTop: 8,
      lineHeight: 20,
    },
    settingsBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.primary,
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 10,
      marginTop: 20,
    },
    settingsBtnText: {
      color: '#fff',
      fontSize: 15,
      fontWeight: '600',
    },
    browseIntroCard: {
      backgroundColor: colors.surfaceAlt,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
      marginBottom: 12,
    },
    browseIntroTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 4,
    },
    browseIntroText: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 18,
    },
    listFooter: {
      paddingVertical: 18,
    },
    modalOverlay: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'rgba(0, 0, 0, 0.45)',
    },
    modalContent: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 18,
      borderTopRightRadius: 18,
      padding: 20,
      gap: 12,
      borderTopWidth: 1,
      borderColor: colors.border,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    modalTitle: {
      fontSize: 17,
      fontWeight: '700',
      color: colors.text,
    },
    modalHelp: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.text,
    },
    modalCaption: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 18,
    },
    fieldBlock: {
      gap: 6,
    },
    fieldLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    fieldHint: {
      fontSize: 12,
      color: colors.textTertiary,
      lineHeight: 17,
    },
    remotePickerRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    remotePickerChip: {
      paddingHorizontal: 10,
      paddingVertical: 8,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceAlt,
    },
    remotePickerChipActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primarySoft,
    },
    remotePickerChipText: {
      fontSize: 12,
      color: colors.textSecondary,
      fontWeight: '600',
    },
    remotePickerChipTextActive: {
      color: colors.primary,
    },
    primaryActionBtn: {
      marginTop: 4,
      borderRadius: 10,
      paddingVertical: 12,
      alignItems: 'center',
      backgroundColor: colors.primary,
    },
    primaryActionText: {
      color: colors.onPrimary,
      fontSize: 15,
      fontWeight: '700',
    },
  });
