import { StyleSheet } from 'react-native';
import type { AppPalette } from '../../theme/useAppTheme';

export const createSchedulerStyles = (colors: AppPalette) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      minHeight: 56,
      paddingHorizontal: 4,
      flexDirection: 'row',
      alignItems: 'center',
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
      backgroundColor: colors.header,
    },
    headerAction: {
      width: 48,
      height: 48,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      color: colors.text,
      fontSize: 18,
      fontWeight: '600',
      lineHeight: 24,
      textAlign: 'center',
    },
    listContent: { paddingHorizontal: 12, paddingBottom: 28 },
    listContentEmpty: { flexGrow: 1, paddingHorizontal: 12, paddingBottom: 28 },
    listHeader: { paddingTop: 14, paddingBottom: 12, gap: 12 },
    intro: { color: colors.textSecondary, fontSize: 14, lineHeight: 20, paddingHorizontal: 4 },
    permissionCard: {
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      borderRadius: 14,
      backgroundColor: colors.surface,
      padding: 14,
      gap: 12,
    },
    permissionTop: { flexDirection: 'row', alignItems: 'flex-start', gap: 11 },
    permissionIcon: {
      width: 38,
      height: 38,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySoft,
    },
    permissionCopy: { flex: 1, minWidth: 0 },
    permissionTitle: { color: colors.text, fontSize: 15, fontWeight: '700', lineHeight: 20 },
    permissionHint: { color: colors.textSecondary, fontSize: 13, lineHeight: 18, marginTop: 3 },
    permissionAction: {
      minHeight: 48,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 16,
    },
    permissionActionText: { color: colors.primary, fontSize: 14, fontWeight: '700' },
    notice: {
      minHeight: 44,
      borderRadius: 12,
      backgroundColor: colors.surfaceAlt,
      paddingHorizontal: 12,
      paddingVertical: 10,
      justifyContent: 'center',
    },
    noticeText: { color: colors.textSecondary, fontSize: 13, lineHeight: 18 },
    jobCard: {
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      borderRadius: 14,
      backgroundColor: colors.surface,
      padding: 14,
      marginBottom: 10,
      gap: 10,
    },
    jobCardSelected: { borderWidth: 2, borderColor: colors.primary },
    jobHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
    jobIcon: {
      width: 38,
      height: 38,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySoft,
    },
    jobHeading: { flex: 1, minWidth: 0 },
    jobTitle: { color: colors.text, fontSize: 16, fontWeight: '700', lineHeight: 21 },
    scheduleText: { color: colors.primary, fontSize: 13, fontWeight: '600', lineHeight: 18 },
    statusPill: {
      minHeight: 26,
      paddingHorizontal: 9,
      borderRadius: 13,
      alignItems: 'center',
      justifyContent: 'center',
    },
    statusText: { fontSize: 11, fontWeight: '700', lineHeight: 15 },
    prompt: { color: colors.textSecondary, fontSize: 14, lineHeight: 20 },
    metadataGroup: {
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.subtleBorder,
      paddingTop: 9,
      gap: 5,
    },
    metadataText: { color: colors.textTertiary, fontSize: 12, lineHeight: 17 },
    resultDetail: { color: colors.textSecondary, fontSize: 12, lineHeight: 17 },
    warningRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
      padding: 10,
      borderRadius: 10,
      backgroundColor: colors.warningBackground,
    },
    warningCopy: { flex: 1, minWidth: 0 },
    warningTitle: { color: colors.warning, fontSize: 13, fontWeight: '700', lineHeight: 18 },
    warningDetail: { color: colors.textSecondary, fontSize: 12, lineHeight: 17, marginTop: 2 },
    feedback: { minHeight: 36, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 8 },
    feedbackText: { fontSize: 12, lineHeight: 17, fontWeight: '600' },
    jobActions: {
      gap: 8,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.subtleBorder,
      paddingTop: 10,
    },
    secondaryActions: { flexDirection: 'row', alignItems: 'stretch', gap: 8 },
    secondaryAction: {
      flex: 1,
      minHeight: 48,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 7,
      paddingHorizontal: 10,
    },
    primaryAction: {
      width: '100%',
      minHeight: 48,
      borderRadius: 12,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 7,
      paddingHorizontal: 10,
    },
    destructiveAction: {
      width: 48,
      minHeight: 48,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    actionDisabled: { opacity: 0.45 },
    secondaryActionText: { color: colors.text, fontSize: 13, fontWeight: '700' },
    primaryActionText: { color: colors.onPrimary, fontSize: 13, fontWeight: '700' },
    emptyState: {
      flex: 1,
      minHeight: 300,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 28,
      paddingBottom: 32,
    },
    emptyIcon: {
      width: 58,
      height: 58,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySoft,
      marginBottom: 14,
    },
    emptyTitle: { color: colors.text, fontSize: 18, fontWeight: '700', textAlign: 'center' },
    emptyHint: {
      color: colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      textAlign: 'center',
      marginTop: 6,
      marginBottom: 18,
    },
    emptyAction: {
      minHeight: 48,
      borderRadius: 12,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 18,
    },
    emptyActionText: { color: colors.onPrimary, fontSize: 15, fontWeight: '700' },
    modalBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: colors.overlay },
    modalSheet: {
      maxHeight: '92%',
      backgroundColor: colors.background,
      borderTopLeftRadius: 22,
      borderTopRightRadius: 22,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      overflow: 'hidden',
    },
    modalHeader: {
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      paddingLeft: 18,
      paddingRight: 6,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    modalTitle: { flex: 1, color: colors.text, fontSize: 18, fontWeight: '700', lineHeight: 24 },
    modalClose: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center' },
    formContent: { paddingHorizontal: 18, paddingTop: 16, paddingBottom: 28, gap: 8 },
    fieldLabel: { color: colors.text, fontSize: 14, fontWeight: '700', lineHeight: 19 },
    fieldHint: { color: colors.textSecondary, fontSize: 12, lineHeight: 17, marginBottom: 2 },
    input: {
      minHeight: 48,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBackground,
      color: colors.text,
      fontSize: 16,
      paddingHorizontal: 12,
      paddingVertical: 11,
      marginBottom: 4,
    },
    multilineInput: { minHeight: 108, textAlignVertical: 'top' },
    inputError: { borderColor: colors.danger },
    fieldError: { color: colors.danger, fontSize: 12, lineHeight: 17, marginBottom: 3 },
    segmentRow: { flexDirection: 'row', gap: 8, marginBottom: 5 },
    segmentButton: {
      flex: 1,
      minHeight: 48,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 10,
    },
    segmentButtonSelected: { borderColor: colors.primary, backgroundColor: colors.primarySoft },
    segmentText: { color: colors.textSecondary, fontSize: 14, fontWeight: '600' },
    segmentTextSelected: { color: colors.primary, fontWeight: '700' },
    intervalRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    intervalInput: { flex: 1, marginBottom: 0 },
    unitRow: { flexDirection: 'row', gap: 5 },
    unitButton: {
      minWidth: 48,
      minHeight: 48,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 8,
    },
    unitButtonSelected: { borderColor: colors.primary, backgroundColor: colors.primarySoft },
    unitText: { color: colors.textSecondary, fontSize: 12, fontWeight: '600' },
    unitTextSelected: { color: colors.primary, fontWeight: '700' },
    inlinePermission: {
      borderRadius: 12,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      padding: 12,
      marginTop: 5,
      gap: 9,
    },
    inlinePermissionText: { color: colors.textSecondary, fontSize: 12, lineHeight: 17 },
    inlinePermissionAction: {
      minHeight: 48,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 14,
    },
    inlinePermissionActionText: { color: colors.primary, fontSize: 13, fontWeight: '700' },
    formError: {
      minHeight: 38,
      borderRadius: 10,
      paddingHorizontal: 10,
      paddingVertical: 8,
      color: colors.danger,
      backgroundColor: colors.dangerSoft,
      fontSize: 13,
      lineHeight: 18,
    },
    createButton: {
      minHeight: 50,
      borderRadius: 12,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 7,
      paddingHorizontal: 16,
    },
    createButtonDisabled: { opacity: 0.45 },
    createButtonText: { color: colors.onPrimary, fontSize: 15, fontWeight: '700' },
  });

export type SchedulerStyles = ReturnType<typeof createSchedulerStyles>;
