import { StyleSheet } from 'react-native';
import type { AppPalette } from '../../theme/useAppTheme';

export const createConversationFilesStyles = (colors: AppPalette) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    flex: { flex: 1 },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 8,
      gap: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.header,
    },
    headerTitleWrap: { flex: 1, minWidth: 0 },
    headerTitle: { fontSize: 17, fontWeight: '700', color: colors.text },
    headerSubtitle: { fontSize: 12, color: colors.textSecondary, marginTop: 1 },
    headerActions: { flexDirection: 'row', gap: 4 },
    headerIconButton: {
      width: 48,
      height: 48,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
    },
    headerIconButtonDisabled: { opacity: 0.45 },
    controls: {
      paddingHorizontal: 12,
      paddingTop: 10,
      paddingBottom: 8,
      gap: 8,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
      backgroundColor: colors.background,
    },
    searchBox: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.inputBackground,
      paddingLeft: 12,
      paddingRight: 4,
    },
    searchInput: { flex: 1, minWidth: 0, color: colors.text, fontSize: 15, paddingVertical: 10 },
    searchClearButton: {
      width: 48,
      height: 48,
      justifyContent: 'center',
      alignItems: 'center',
    },
    filterToolbar: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    filterScroll: { flex: 1, minWidth: 0 },
    filterContent: { gap: 8, paddingRight: 4 },
    filterChip: {
      minHeight: 48,
      justifyContent: 'center',
      paddingHorizontal: 14,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
    },
    filterChipSelected: { borderColor: colors.primary, backgroundColor: colors.primarySoft },
    filterChipText: { color: colors.textSecondary, fontSize: 13, fontWeight: '600' },
    filterChipTextSelected: { color: colors.primary, fontWeight: '700' },
    sortButton: {
      minHeight: 48,
      minWidth: 88,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
    },
    sortButtonText: { color: colors.text, fontSize: 12, fontWeight: '700' },
    listContent: { paddingVertical: 8, flexGrow: 1 },
    fileRow: {
      minHeight: 68,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    fileRowMain: {
      minHeight: 68,
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingVertical: 10,
    },
    fileTextWrap: { flex: 1, minWidth: 0, gap: 3 },
    fileName: { fontSize: 15, color: colors.text, fontWeight: '600' },
    fileMeta: { fontSize: 11, color: colors.textSecondary },
    fileRowAction: {
      width: 48,
      minHeight: 48,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
    },
    fileContentScroll: { flex: 1, backgroundColor: colors.codeBackground },
    fileContentContainer: { padding: 12 },
    fileContent: {
      fontFamily: 'monospace',
      fontSize: 13,
      lineHeight: 20,
      color: colors.text,
    },
    imagePreviewContainer: {
      flex: 1,
      padding: 16,
      backgroundColor: colors.codeBackground,
      justifyContent: 'center',
      alignItems: 'center',
    },
    imagePreview: {
      width: '100%',
      height: '100%',
      backgroundColor: colors.surfaceAlt,
      borderRadius: 12,
    },
    binaryState: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 32,
      backgroundColor: colors.codeBackground,
    },
    binaryStateTitle: { fontSize: 16, fontWeight: '600', color: colors.text },
    binaryStateHint: {
      fontSize: 13,
      color: colors.textSecondary,
      textAlign: 'center',
      lineHeight: 18,
    },
  });

export type ConversationFilesStyles = ReturnType<typeof createConversationFilesStyles>;
