const MAX_PUBLIC_ITEMS = 1024;

const ASSESSMENT_DIMENSIONS = new Set([
  'task_understanding',
  'task_completion',
  'tool_usage',
  'tool_discovery',
  'token_efficiency',
  'memory',
  'delegation',
  'outcome_validators',
  'control_graph',
  'mobile_native',
  'privacy_safety',
]);

const BENCHMARK_FAMILIES = new Set([
  'kavi-core',
  'gaia-adapted',
  'tau-bench-adapted',
  'agentbench-adapted',
  'memory-agent-bench-adapted',
  'state-bench-adapted',
  'tool-discovery-adapted',
  'bfcl-adapted',
  'longmem-adapted',
  'androidworld-adapted',
  'mobile-agent-bench-adapted',
  'mobileworld-adapted',
  'knowu-bench-adapted',
  'androidworld-direct',
  'mobileworld-direct',
  'spa-bench-direct',
  'bfcl-v4-direct',
  'longmemeval-v2-direct',
  'tau-bench-direct',
  'toolsandbox-direct',
  'agentdojo-direct',
  'locomo-direct',
  'beam-direct',
  'provider-prompt-cache-direct',
]);

const RUBRIC_KINDS = new Set([
  'workspace_file',
  'workspace_file_absent',
  'goals_bootstrapped',
  'goal_evidence_satisfied',
  'graph_status',
  'graph_terminal_success',
  'completion_gate_hold',
  'memory_fact',
  'memory_fact_absent',
  'token_budget',
  'cache_read_tokens',
  'cache_prefix_readiness',
  'cache_eligible_read_rate',
  'min_user_turns',
  'goal_status',
  'ingestion_job_completed',
  'memory_episode_count',
  'native_fixture_state',
  'file_hash',
  'goal_criterion',
  'working_block_token',
  'graph_audit_observed',
]);

const GRAPH_STATUSES = new Set([
  'ready',
  'model_turn',
  'awaiting_tool_results',
  'recovering',
  'waiting_async',
  'awaiting_review',
  'blocked',
  'finalized',
  'yielded',
  'cancelled',
  'failed',
]);

const FAILURE_CATEGORIES = new Set([
  'discovery_miss',
  'wrong_tool',
  'wrong_args',
  'missing_clarification',
  'permission_failure',
  'goal_state_bug',
  'memory_retrieval_miss',
  'tool_poisoning_vulnerability',
  'cache_prefix_drift',
  'token_budget_overrun',
  'loop_control',
  'native_side_effect_failure',
  'external_runner_required',
  'grader_quality',
  'unknown_structural_failure',
]);

module.exports = {
  ASSESSMENT_DIMENSIONS,
  BENCHMARK_FAMILIES,
  FAILURE_CATEGORIES,
  GRAPH_STATUSES,
  MAX_PUBLIC_ITEMS,
  RUBRIC_KINDS,
};
