export const STREAM_STORE_CHECKPOINT_INTERVAL_MS = 240;
export const STREAM_UI_DRAFT_PUBLISH_INTERVAL_MS = 48;
export const TOOL_RESULT_PERSISTENCE_CHECKPOINT_DELAY_MS = 750;
export const SUB_AGENT_PROGRESS_REFRESH_INTERVAL_MS = 400;
export const AUTO_SCROLL_BOTTOM_THRESHOLD_PX = 96;
export const USER_SCROLL_RELEASE_DELAY_MS = 64;
export const MAX_LOG_PANEL_HEIGHT = 260;
export const MAX_LOG_DETAIL_CHARS = 320;
