import type { AppPalette } from '../theme/useAppTheme';

export const createChatHeaderStyles = (colors: AppPalette) =>
  ({
    header: {
      minHeight: 56,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 8,
      backgroundColor: colors.header,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerButton: {
      width: 48,
      height: 48,
      flexShrink: 0,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 24,
    },
    headerCenter: {
      flex: 1,
      minWidth: 0,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 8,
    },
    headerTitle: {
      maxWidth: '100%',
      color: colors.text,
      fontSize: 16,
      fontWeight: '700',
      textAlign: 'center',
    },
    headerStatusRow: {
      minHeight: 18,
      maxWidth: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 5,
      marginTop: 1,
    },
    headerStatusDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.success,
    },
    headerStatusDotBusy: {
      backgroundColor: colors.primary,
    },
    headerStatusText: {
      flexShrink: 1,
      color: colors.textSecondary,
      fontSize: 11,
      fontWeight: '600',
      textAlign: 'center',
    },
    conversationMenuOverlay: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: colors.overlay,
    },
    conversationMenuSheet: {
      maxHeight: '80%',
      paddingTop: 8,
      paddingHorizontal: 12,
      paddingBottom: 8,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      backgroundColor: colors.surface,
    },
    conversationMenuHandle: {
      width: 36,
      height: 4,
      alignSelf: 'center',
      marginBottom: 8,
      borderRadius: 2,
      backgroundColor: colors.border,
    },
    conversationMenuHeader: {
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      paddingLeft: 8,
    },
    conversationMenuTitle: {
      flex: 1,
      color: colors.text,
      fontSize: 18,
      fontWeight: '700',
    },
    conversationMenuClose: {
      width: 48,
      height: 48,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 24,
    },
    conversationMenuDivider: {
      height: 1,
      marginVertical: 6,
      backgroundColor: colors.border,
    },
    conversationMenuRow: {
      minHeight: 56,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 14,
    },
    conversationMenuRowPressed: {
      backgroundColor: colors.surfaceAlt,
    },
    conversationMenuRowIcon: {
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 11,
      backgroundColor: colors.surfaceAlt,
    },
    conversationMenuRowText: {
      flex: 1,
      minWidth: 0,
      color: colors.text,
      fontSize: 15,
      fontWeight: '600',
    },
    conversationMenuRowDangerText: {
      color: colors.danger,
    },
  }) as const;
