import { StyleSheet } from 'react-native';
import type { AppPalette } from '../theme/useAppTheme';

export const createVoiceScreenStyles = (colors: AppPalette) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      minHeight: 56,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 8,
      backgroundColor: colors.header,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerAction: {
      width: 48,
      height: 48,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      fontSize: 18,
      fontWeight: '700',
      color: colors.text,
      textAlign: 'center',
    },
    scrollView: {
      flex: 1,
    },
    content: {
      flexGrow: 1,
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 24,
      gap: 16,
    },
    micSection: {
      alignItems: 'center',
      paddingVertical: 8,
    },
    stateLabel: {
      fontSize: 17,
      fontWeight: '700',
      marginTop: 16,
      textAlign: 'center',
    },
    hint: {
      maxWidth: 320,
      fontSize: 14,
      lineHeight: 20,
      color: colors.textSecondary,
      marginTop: 5,
      textAlign: 'center',
    },
    micButton: {
      width: 120,
      height: 120,
      borderRadius: 60,
      backgroundColor: colors.surface,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 3,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
    },
    micButtonActive: {
      backgroundColor: colors.primarySoft,
      shadowOpacity: 0.2,
      shadowRadius: 12,
    },
    micButtonError: {
      backgroundColor: colors.dangerSoft,
    },
    errorBox: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      backgroundColor: colors.dangerSoft,
      borderRadius: 12,
      padding: 14,
    },
    errorCopy: {
      flex: 1,
      gap: 3,
    },
    errorTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.danger,
    },
    errorText: {
      fontSize: 14,
      lineHeight: 20,
      color: colors.text,
    },
    actionRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'center',
      gap: 10,
    },
    secondaryButton: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: 16,
      backgroundColor: colors.surface,
    },
    secondaryButtonText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
    },
    primaryTextButton: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderRadius: 12,
      paddingHorizontal: 18,
      backgroundColor: colors.primary,
    },
    primaryTextButtonText: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.onPrimary,
    },
    privacyCard: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      padding: 14,
      borderRadius: 12,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    privacyCopy: {
      flex: 1,
      gap: 4,
    },
    privacyTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
    },
    privacyText: {
      fontSize: 13,
      lineHeight: 19,
      color: colors.textSecondary,
    },
    savedToChatText: {
      fontSize: 13,
      lineHeight: 19,
      fontWeight: '600',
      color: colors.text,
    },
    conversationSection: {
      gap: 12,
    },
    sectionTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.text,
    },
    turnGroup: {
      gap: 8,
    },
    transcriptBox: {
      backgroundColor: colors.surface,
      borderRadius: 12,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.border,
    },
    responseBox: {
      backgroundColor: colors.surface,
      borderRadius: 12,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.primarySoft,
    },
    boxLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.textTertiary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginBottom: 6,
    },
    transcriptText: {
      fontSize: 15,
      color: colors.text,
      lineHeight: 22,
    },
    responseText: {
      fontSize: 15,
      color: colors.text,
      lineHeight: 22,
    },
    placeholderText: {
      minHeight: 80,
      padding: 18,
      borderRadius: 12,
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: colors.border,
      fontSize: 14,
      lineHeight: 20,
      color: colors.textTertiary,
      textAlign: 'center',
      textAlignVertical: 'center',
    },
  });
