const mockAppThemeColors = {
  mode: 'dark',
  background: '#000',
  surface: '#111',
  surfaceAlt: '#222',
  panel: '#111',
  header: '#111',
  border: '#333',
  subtleBorder: '#444',
  text: '#fff',
  textSecondary: '#aaa',
  textTertiary: '#777',
  placeholder: '#555',
  primary: '#0f0',
  onPrimary: '#fff',
  primarySoft: '#030',
  danger: '#f00',
  onDanger: '#fff',
  dangerSoft: '#300',
  success: '#0f0',
  overlay: 'rgba(0,0,0,0.5)',
  userBubble: '#060',
  assistantBubble: '#111',
  inputBackground: '#222',
  inputBorder: '#444',
  toolCard: '#111',
  toolCardHeader: '#222',
  codeBackground: '#000',
  link: '#0f0',
  onPrimaryLink: '#dfd',
  warning: '#fc0',
  warningBackground: '#330',
  accent: '#0f0',
  info: '#6af',
} as const;

jest.mock('../../src/theme/useAppTheme', () => ({
  useAppTheme: () => ({
    themePreference: 'dark',
    resolvedTheme: 'dark',
    isDark: true,
    colors: mockAppThemeColors,
  }),
  AppPalette: {},
}));
