export function buildPackageNormalizationWorkerSource(): string[] {
  return [
    'function normalizePackageSpecs(packages) {',
    '  if (!Array.isArray(packages)) {',
    '    return [];',
    '  }',
    '',
    '  var normalized = [];',
    '  var seen = Object.create(null);',
    '  for (var index = 0; index < packages.length; index++) {',
    '    var spec = typeof packages[index] === "string" ? packages[index].trim() : "";',
    '    if (!spec || seen[spec]) {',
    '      continue;',
    '    }',
    '    seen[spec] = true;',
    '    normalized.push(spec);',
    '  }',
    '',
    '  return normalized;',
    '}',
    '',
    'function normalizeIndexUrls(indexUrls) {',
    '  if (!Array.isArray(indexUrls)) {',
    '    return [];',
    '  }',
    '',
    '  var normalized = [];',
    '  var seen = Object.create(null);',
    '  for (var index = 0; index < indexUrls.length; index++) {',
    '    var candidate = typeof indexUrls[index] === "string" ? indexUrls[index].trim() : "";',
    '    if (!candidate || seen[candidate] || !/^https?:\\/\\/\\S+$/i.test(candidate)) {',
    '      continue;',
    '    }',
    '    seen[candidate] = true;',
    '    normalized.push(candidate);',
    '  }',
    '',
    '  return normalized;',
    '}',
    '',
  ];
}

export function buildPackageInstallationWorkerSource(): string[] {
  return [
    'function buildMicropipInstallCode(packages, indexUrls) {',
    '  var call = "await micropip.install(" + JSON.stringify(packages);',
    '  if (indexUrls.length > 0) {',
    '    call += ", index_urls=" + JSON.stringify(indexUrls);',
    '  }',
    '  call += ")";',
    '  return ["import micropip", call].join("\\n");',
    '}',
    '',
    'function formatPackageInstallError(error, packages, indexUrls) {',
    '  var baseMessage = formatError(error);',
    '  var guidance = "Pyodide can install official Pyodide packages, pure-Python wheels, and wasm/emscripten-compatible wheels only.";',
    '  if (indexUrls.length > 0) {',
    '    guidance += " Custom indexes must expose compatible wheels over HTTP(S) with CORS enabled.";',
    '  } else if (packages.length > 0) {',
    '    guidance += " If PyPI does not provide a compatible wheel, supply a wheel URL or custom indexUrls.";',
    '  }',
    '  return baseMessage + " " + guidance;',
    '}',
    '',
  ];
}
