import {
  MAX_PYTHON_WORKFLOW_BRIDGE_CONTENT_CHARS,
  MAX_PYTHON_WORKFLOW_BRIDGE_ENTRIES,
  PYTHON_WORKFLOW_BRIDGE_KIND_VALUES,
  PYTHON_WORKFLOW_BRIDGE_RECORDER_VALUES,
  PYTHON_WORKFLOW_BRIDGE_STATUS_VALUES,
} from '../workflowBridge';
import {
  PYODIDE_RUNTIME_HELPERS,
  buildNativeHttpBridgeWorkerSource,
  buildWorkflowBridgeWorkerSource,
} from './bridge';
import {
  buildPackageInstallationWorkerSource,
  buildPackageNormalizationWorkerSource,
} from './packages';
import {
  buildPyodideBootWorkerSource,
  buildRuntimeEnvironmentWorkerSource,
  buildWorkspaceEnvironmentWorkerSource,
  buildWorkspaceMountWorkerSource,
} from './environment';

function buildWorkerGlobalPreludeSource(): string[] {
  return [
    'var pyodide = null;',
    'var bootError = null;',
    'var installedPackageSpecs = Object.create(null);',
    'var injectedEnvKeys = [];',
    'var activeCapture = null;',
    'var activeWorkflowBridgeState = null;',
    'var pendingNativeHttpRequests = Object.create(null);',
    'var nativeHttpRequestCounter = 0;',
    "var WORKSPACE_ROOT = '/workspace';",
    `var MAX_WORKFLOW_BRIDGE_ENTRIES = ${MAX_PYTHON_WORKFLOW_BRIDGE_ENTRIES};`,
    `var MAX_WORKFLOW_BRIDGE_CONTENT_CHARS = ${MAX_PYTHON_WORKFLOW_BRIDGE_CONTENT_CHARS};`,
    'var MAX_WORKFLOW_BRIDGE_TITLE_CHARS = 120;',
    'var MAX_WORKFLOW_BRIDGE_OPTIONAL_TEXT_CHARS = 240;',
    'var MAX_WORKFLOW_BRIDGE_TAGS = 8;',
    `var ALLOWED_WORKFLOW_BRIDGE_KINDS = ${JSON.stringify(PYTHON_WORKFLOW_BRIDGE_KIND_VALUES)};`,
    `var ALLOWED_WORKFLOW_BRIDGE_STATUSES = ${JSON.stringify(PYTHON_WORKFLOW_BRIDGE_STATUS_VALUES)};`,
    `var ALLOWED_WORKFLOW_BRIDGE_RECORDERS = ${JSON.stringify(PYTHON_WORKFLOW_BRIDGE_RECORDER_VALUES)};`,
    `var PYODIDE_RUNTIME_HELPERS = ${JSON.stringify(PYODIDE_RUNTIME_HELPERS)};`,
    '',
  ];
}

function buildWorkerCommunicationSource(): string[] {
  return [
    'async function runPythonRequest(message) {',
    '  try {',
    '    await pyodideReadyPromise;',
    '  } catch (error) {',
    '    throw new Error(formatError(bootError || error));',
    '  }',
    '',
    '  var start = Date.now();',
    '  beginCapture();',
    '  try {',
    '    configureWorkflowBridge(message.workflowBridge);',
    '    var packagesToInstall = normalizePackageSpecs(message.packages).filter(function(spec) {',
    '      return !installedPackageSpecs[spec];',
    '    });',
    '    var indexUrls = normalizeIndexUrls(message.indexUrls);',
    '',
    '    mountWorkspaceFiles(Array.isArray(message.files) ? message.files : []);',
    '    var initialFiles = indexWorkspaceFiles(collectWorkspaceFiles(WORKSPACE_ROOT, ""));',
    '',
    '    if (packagesToInstall.length > 0) {',
    '      try {',
    '        await pyodide.runPythonAsync(buildMicropipInstallCode(packagesToInstall, indexUrls));',
    '      } catch (packageError) {',
    '        throw new Error(formatPackageInstallError(packageError, packagesToInstall, indexUrls));',
    '      }',
    '      for (var packageIndex = 0; packageIndex < packagesToInstall.length; packageIndex++) {',
    '        installedPackageSpecs[packagesToInstall[packageIndex]] = true;',
    '      }',
    '    }',
    '',
    "    var sourceForImports = '';",
    '    if (message.scriptPath) {',
    '      sourceForImports = pyodide.FS.readFile(toWorkspaceFsPath(message.scriptPath), { encoding: "utf8" });',
    '    } else if (typeof message.code === "string") {',
    '      sourceForImports = message.code;',
    '    }',
    '',
    '    if (sourceForImports && sourceForImports.trim()) {',
    '      await pyodide.loadPackagesFromImports(sourceForImports);',
    '    }',
    '',
    '    clearInjectedEnv();',
    '    if (message.env && Object.keys(message.env).length > 0) {',
    '      var envEntries = Object.entries(message.env)',
    '        .map(function(entry) { return JSON.stringify(entry[0]) + ": " + JSON.stringify(entry[1]); })',
    '        .join(", ");',
    '      pyodide.runPython("import os; os.environ.update({" + envEntries + "})");',
    '      injectedEnvKeys = Object.keys(message.env);',
    '    }',
    '',
    '    var workingDirectory = message.workingDirectory ? toWorkspaceFsPath(message.workingDirectory) : WORKSPACE_ROOT;',
    '    var executionResult;',
    '    if (message.scriptPath) {',
    '      var scriptPath = toWorkspaceFsPath(message.scriptPath);',
    '      var argv = Array.isArray(message.argv) ? message.argv : [];',
    '      executionResult = parseExecutionResult(await pyodide.runPythonAsync(',
    '        "await _kavi_execute_script("',
    '        + JSON.stringify(scriptPath) + ", "',
    '        + JSON.stringify(argv) + ", "',
    '        + JSON.stringify(workingDirectory) + ", "',
    '        + JSON.stringify(WORKSPACE_ROOT)',
    '        + ")"',
    '      ));',
    '    } else {',
    '      executionResult = parseExecutionResult(await pyodide.runPythonAsync(',
    '        "await _kavi_execute_inline("',
    '        + JSON.stringify(message.code || "") + ", "',
    '        + JSON.stringify(workingDirectory) + ", "',
    '        + JSON.stringify(WORKSPACE_ROOT)',
    '        + ")"',
    '      ));',
    '    }',
    '',
    '    clearInjectedEnv();',
    '    var capture = finishCapture();',
    '    var errorMessage = executionResult.error || undefined;',
    '    var workflowBridgeResult = collectWorkflowBridgeResult();',
    '    var changedFiles = collectWorkspaceFiles(WORKSPACE_ROOT, "").filter(function(file) {',
    '      return initialFiles[file.path] !== file.contentBase64;',
    '    });',
    '',
    '    var successMessage = {',
    '      type: "python-result",',
    '      id: message.id,',
    '      output: combineExecutionOutput(capture, executionResult.result_text, Boolean(errorMessage)),',
    '      error: errorMessage,',
    '      durationMs: Date.now() - start,',
    '      files: errorMessage ? [] : changedFiles,',
    '    };',
    '    if (workflowBridgeResult) {',
    '      successMessage.workflowBridge = workflowBridgeResult;',
    '    }',
    '    resetWorkflowBridge();',
    '    self.postMessage(successMessage);',
    '  } catch (error) {',
    '    try { clearInjectedEnv(); } catch (cleanupError) {}',
    '    var capture = finishCapture();',
    '    var workflowBridgeResult = collectWorkflowBridgeResult();',
    '    var errorMessage = {',
    '      type: "python-result",',
    '      id: message.id,',
    '      output: combineExecutionOutput(capture, null, true),',
    '      error: formatError(error),',
    '      durationMs: Date.now() - start,',
    '    };',
    '    if (workflowBridgeResult) {',
    '      errorMessage.workflowBridge = workflowBridgeResult;',
    '    }',
    '    resetWorkflowBridge();',
    '    self.postMessage(errorMessage);',
    '  }',
    '}',
    '',
    'self.onmessage = function(event) {',
    '  var message = event && event.data ? event.data : {};',
    '  if (message.type === "python-http-response" && message.requestId) {',
    '    handleNativeHttpResponse(message);',
    '    return;',
    '  }',
    '  if (message.type !== "run-python" || !message.id) {',
    '    return;',
    '  }',
    '  void runPythonRequest(message);',
    '};',
  ];
}

export function buildPyodideWorkerSource(): string {
  return [
    ...buildWorkerGlobalPreludeSource(),
    ...buildRuntimeEnvironmentWorkerSource(),
    ...buildPackageNormalizationWorkerSource(),
    ...buildWorkflowBridgeWorkerSource(),
    ...buildWorkspaceEnvironmentWorkerSource(),
    ...buildNativeHttpBridgeWorkerSource(),
    ...buildWorkspaceMountWorkerSource(),
    ...buildPackageInstallationWorkerSource(),
    ...buildPyodideBootWorkerSource(),
    ...buildWorkerCommunicationSource(),
  ].join('\n');
}
