import type { AppPalette } from '../../theme/useAppTheme';

export const createRemoteWorkScreenOverviewStyleFragments = (colors: AppPalette) => ({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.header,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text,
    flexShrink: 1,
  },
  content: {
    flex: 1,
  },
  contentInner: {
    padding: 16,
    gap: 16,
  },
  infoCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    padding: 16,
    gap: 8,
  },
  surfaceOverviewCard: {
    flex: 1,
    minWidth: 170,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    padding: 14,
    gap: 10,
  },
  surfaceOverviewCopy: {
    gap: 4,
    flex: 1,
  },
  surfaceOverviewStatPill: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.primarySoft,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  surfaceOverviewValue: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.primary,
  },
  surfaceOverviewLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.primary,
  },
  heroCard: {
    gap: 14,
  },
  heroCardWide: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  heroCopy: {
    flex: 1,
    gap: 8,
  },
  heroStats: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  heroStatPill: {
    flex: 1,
    minWidth: 100,
    backgroundColor: colors.primarySoft,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 4,
  },
  heroStatPillMuted: {
    flex: 1,
    minWidth: 100,
    backgroundColor: colors.surfaceAlt,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 4,
  },
  heroStatValue: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.primary,
  },
  heroStatValueMuted: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.text,
  },
  heroStatLabel: {
    fontSize: 12,
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  infoTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
  },
  infoText: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
  },
  summaryGrid: {
    flexDirection: 'row',
    gap: 12,
    flexWrap: 'wrap',
  },
  summaryCard: {
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    padding: 14,
    gap: 8,
    flexShrink: 1,
    overflow: 'hidden',
  },
  summaryCardTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  summaryValue: {
    fontSize: 24,
    fontWeight: '800',
    color: colors.text,
  },
  summaryLabel: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  sectionHeaderText: {
    flex: 1,
    gap: 4,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
    flexShrink: 1,
  },
  sectionCaption: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  headerAction: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '600',
  },
  configStudioCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 20,
    padding: 16,
    gap: 16,
    overflow: 'hidden',
  },
  workspaceSurfacePanel: {
    gap: 14,
  },
  configSurfaceRow: {
    flexDirection: 'row',
    gap: 10,
    paddingRight: 4,
  },
  surfaceChip: {
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
  },
  surfaceChipActive: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
  },
  surfaceChipText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '600',
  },
  surfaceChipTextActive: {
    color: colors.primary,
  },
  configForm: {
    gap: 12,
  },
  configFormHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  configFormHeaderText: {
    flex: 1,
    gap: 4,
  },
  configInput: {
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: colors.text,
    fontSize: 14,
  },
  configTextArea: {
    minHeight: 96,
  },
  optionRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  horizontalChipRow: {
    gap: 8,
  },
  optionChip: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
  },
  optionChipActive: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
  },
  optionChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  optionChipTextActive: {
    color: colors.primary,
  },
  formHint: {
    fontSize: 12,
    color: colors.textSecondary,
    lineHeight: 17,
  },
});
