import type { ToolDefinition } from '../../../types/tool';
import {
  CALENDAR_CREATE_TOOL,
  CALENDAR_EVENTS_TOOL,
  CALENDAR_LIST_TOOL,
  CALENDAR_UPDATE_TOOL,
} from './calendar/definitions';
import { CLIPBOARD_READ_TOOL, CLIPBOARD_TOOL, CLIPBOARD_WRITE_TOOL } from './clipboard/definitions';
import {
  CONTACTS_CREATE_TOOL,
  CONTACTS_EDIT_TOOL,
  CONTACTS_FORM_TOOL,
  CONTACTS_GET_FULL_TOOL,
  CONTACTS_GET_TOOL,
  CONTACTS_MANAGE_ACCESS_TOOL,
  CONTACTS_PICK_TOOL,
  CONTACTS_SEARCH_FULL_TOOL,
  CONTACTS_SEARCH_TOOL,
  CONTACTS_SHARE_TOOL,
  CONTACTS_VIEW_TOOL,
} from './contacts/definitions';
import {
  EMAIL_COMPOSE_TOOL,
  MAPS_OPEN_TOOL,
  OPEN_URL_TOOL,
  PHONE_CALL_TOOL,
  SMS_COMPOSE_TOOL,
} from './communication/definitions';
import {
  DEVICE_HEALTH_TOOL,
  DEVICE_INFO_TOOL,
  DEVICE_PERMISSIONS_TOOL,
  DEVICE_QUERY_TOOL,
  DEVICE_STATUS_TOOL,
} from './device/definitions';
import { HAPTIC_FEEDBACK_TOOL } from './haptics/definitions';
import { LOCATION_CURRENT_TOOL } from './location/definitions';
import { CAMERA_CLIP_TOOL, PHOTOS_LATEST_TOOL, SCREEN_RECORD_TOOL } from './media/definitions';
import {
  NOTIFICATION_CANCEL_TOOL,
  NOTIFICATION_SCHEDULE_TOOL,
  NOTIFICATION_SEND_TOOL,
} from './notifications/definitions';
import {
  SHARE_CONTACT_TOOL,
  SHARE_FILE_TOOL,
  SHARE_TEXT_TOOL,
  SHARE_TOOL,
  SHARE_URL_TOOL,
} from './share/definitions';

export const ALL_NATIVE_TOOL_DEFINITIONS: ToolDefinition[] = [
  CALENDAR_LIST_TOOL,
  CALENDAR_EVENTS_TOOL,
  CALENDAR_CREATE_TOOL,
  CALENDAR_UPDATE_TOOL,
  EMAIL_COMPOSE_TOOL,
  SMS_COMPOSE_TOOL,
  PHONE_CALL_TOOL,
  MAPS_OPEN_TOOL,
  CONTACTS_PICK_TOOL,
  CONTACTS_MANAGE_ACCESS_TOOL,
  CONTACTS_VIEW_TOOL,
  CONTACTS_EDIT_TOOL,
  CONTACTS_CREATE_TOOL,
  CONTACTS_SEARCH_TOOL,
  CONTACTS_GET_TOOL,
  CONTACTS_FORM_TOOL,
  CONTACTS_SHARE_TOOL,
  CONTACTS_SEARCH_FULL_TOOL,
  CONTACTS_GET_FULL_TOOL,
  LOCATION_CURRENT_TOOL,
  CLIPBOARD_READ_TOOL,
  CLIPBOARD_WRITE_TOOL,
  CLIPBOARD_TOOL,
  SHARE_TEXT_TOOL,
  SHARE_URL_TOOL,
  SHARE_FILE_TOOL,
  SHARE_CONTACT_TOOL,
  SHARE_TOOL,
  OPEN_URL_TOOL,
  NOTIFICATION_SEND_TOOL,
  NOTIFICATION_SCHEDULE_TOOL,
  NOTIFICATION_CANCEL_TOOL,
  DEVICE_STATUS_TOOL,
  DEVICE_INFO_TOOL,
  DEVICE_PERMISSIONS_TOOL,
  DEVICE_HEALTH_TOOL,
  DEVICE_QUERY_TOOL,
  PHOTOS_LATEST_TOOL,
  CAMERA_CLIP_TOOL,
  SCREEN_RECORD_TOOL,
  HAPTIC_FEEDBACK_TOOL,
];
