import { StyleSheet } from 'react-native';
import type { AppPalette } from '../../theme/useAppTheme';

export const createCodeEditorScreenStyles = (colors: AppPalette) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    flex: { flex: 1 },
    sourceBar: {
      flexDirection: 'row',
      gap: 8,
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    sourceChip: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
    },
    sourceChipActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primarySoft,
    },
    sourceChipDisabled: {
      opacity: 0.45,
    },
    sourceChipText: {
      fontSize: 12,
      color: colors.textSecondary,
      fontWeight: '600',
    },
    sourceChipTextActive: {
      color: colors.primary,
    },
    sourceChipTextDisabled: {
      color: colors.textTertiary,
    },
    targetBar: {
      paddingHorizontal: 16,
      paddingTop: 10,
      gap: 8,
    },
    sectionLabel: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    targetChipsWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    targetChip: {
      maxWidth: '100%',
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
    },
    targetChipActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primarySoft,
    },
    targetChipText: {
      fontSize: 12,
      color: colors.textSecondary,
    },
    targetChipTextActive: {
      color: colors.primary,
      fontWeight: '600',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: colors.header,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerCenter: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginHorizontal: 12,
    },
    headerTitle: { fontSize: 15, fontWeight: '600', color: colors.text, flexShrink: 1 },
    dirtyDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.warning,
      marginLeft: 4,
    },
    headerActions: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    headerBtn: { padding: 4 },
    pathBar: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 16,
      paddingVertical: 6,
      backgroundColor: colors.surface,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    pathInput: {
      flex: 1,
      fontSize: 11,
      color: colors.textTertiary,
      fontFamily: 'monospace',
      paddingVertical: 0,
    },
    langBadge: {
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 4,
      backgroundColor: colors.primarySoft,
    },
    langBadgeText: { fontSize: 10, fontWeight: '600', color: colors.primary },
    contextBar: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      gap: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.background,
    },
    contextText: {
      fontSize: 12,
      color: colors.textSecondary,
      fontFamily: 'monospace',
    },
    contextActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    contextBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
    },
    contextBtnText: {
      fontSize: 12,
      color: colors.textSecondary,
      fontWeight: '500',
    },
    modeBanner: {
      marginHorizontal: 16,
      marginTop: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 10,
      borderWidth: 1,
      gap: 2,
    },
    modeBannerWarning: {
      backgroundColor: colors.warning + '15',
      borderColor: colors.warning,
    },
    modeBannerSuccess: {
      backgroundColor: colors.primarySoft,
      borderColor: colors.primary,
    },
    modeBannerText: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.text,
    },
    modeBannerSubtext: {
      fontSize: 11,
      color: colors.textSecondary,
    },
    browserPanel: {
      paddingHorizontal: 16,
      paddingTop: 12,
      gap: 8,
    },
    emptyState: {
      marginHorizontal: 16,
      marginTop: 12,
      padding: 16,
      borderRadius: 14,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 10,
    },
    emptyTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
    },
    emptyBody: {
      fontSize: 13,
      lineHeight: 20,
      color: colors.textSecondary,
    },
    primaryCta: {
      alignSelf: 'flex-start',
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: colors.primary,
    },
    primaryCtaText: {
      fontSize: 12,
      color: colors.onPrimary,
      fontWeight: '700',
    },
    loadingState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    loadingText: {
      fontSize: 13,
      color: colors.textSecondary,
    },
  });
