import { StyleSheet } from 'react-native';
import type { AppPalette } from '../../theme/useAppTheme';

export const createSettingsScreenConfigStyleFragments = (colors: AppPalette) => ({
  secureKeyBlock: {
    marginBottom: 12,
    padding: 12,
    borderRadius: 12,
    backgroundColor: colors.surface,
  },
  mcpMetadataCard: {
    marginBottom: 8,
    padding: 12,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  mcpChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  mcpOauthRow: {
    marginTop: 8,
    gap: 8,
  },
  secureKeyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 4,
  },
  secureKeyTitleWrap: {
    flex: 1,
  },
  secureKeyTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 4,
  },
  secureKeyMeta: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.primary,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  secureKeyHint: {
    fontSize: 12,
    color: colors.textTertiary,
    marginBottom: 6,
  },
  setupDetail: {
    fontSize: 12,
    color: colors.textSecondary,
    marginBottom: 4,
    lineHeight: 18,
  },
  setupLabel: {
    fontWeight: '700',
    color: colors.text,
  },
  inlineLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
    alignSelf: 'flex-start',
  },
  inlineLinkText: {
    fontSize: 13,
    color: colors.primary,
    fontWeight: '600',
  },
  statusPill: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
  },
  statusPillReady: {
    backgroundColor: colors.primarySoft,
  },
  statusPillMissing: {
    backgroundColor: colors.surfaceAlt,
  },
  statusPillText: {
    fontSize: 11,
    fontWeight: '700',
  },
  statusPillTextReady: {
    color: colors.primary,
  },
  statusPillTextMissing: {
    color: colors.textSecondary,
  },
  permissionGroup: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    marginBottom: 10,
    overflow: 'hidden',
  },
  permissionGroupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
  },
  permissionGroupHeaderText: {
    flex: 1,
  },
  permissionGroupTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
  },
  permissionGroupCount: {
    fontSize: 12,
    color: colors.textTertiary,
    marginTop: 2,
  },
  permissionGroupActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  permissionGroupDescription: {
    fontSize: 12,
    color: colors.textTertiary,
    marginBottom: 8,
    lineHeight: 18,
  },
  permissionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  permissionTextWrap: {
    flex: 1,
  },
  permissionToolName: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 2,
  },
  permissionToolDescription: {
    fontSize: 12,
    color: colors.textTertiary,
    lineHeight: 18,
  },
  personaCard: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  primaryButton: {
    marginTop: 12,
    backgroundColor: colors.primary,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.onPrimary,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    marginTop: 8,
  },
  secondaryBtn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingVertical: 12,
    backgroundColor: colors.surfaceAlt,
  },
  secondaryBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.primary,
  },
  emptyText: {
    fontSize: 14,
    color: colors.textTertiary,
    textAlign: 'center',
    padding: 20,
  },
  deleteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 24,
    paddingVertical: 12,
    justifyContent: 'center',
  },
  deleteBtnText: {
    fontSize: 15,
    color: colors.danger,
    fontWeight: '500',
  },
  dangerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    backgroundColor: colors.dangerSoft,
    borderRadius: 10,
  },
  dangerBtnText: {
    fontSize: 15,
    color: colors.danger,
    fontWeight: '500',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 40,
    maxHeight: '70%',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 16,
    textAlign: 'center',
  },
  langItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  langItemText: {
    fontSize: 16,
    color: colors.text,
  },
  modalCloseBtn: {
    marginTop: 16,
    alignItems: 'center',
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: colors.surfaceAlt,
  },
  modalCloseBtnText: {
    fontSize: 16,
    color: colors.textSecondary,
    fontWeight: '600',
  },
});
