import { StyleSheet } from 'react-native';
import type { AppPalette } from '../../theme/useAppTheme';

export const createSkillsScreenStyles = (colors: AppPalette) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: colors.header,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.text,
    },
    list: {
      padding: 16,
      flexGrow: 1,
    },
    card: {
      backgroundColor: colors.surface,
      borderRadius: 12,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    cardTitleSection: {
      flex: 1,
    },
    cardTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.text,
    },
    version: {
      fontSize: 11,
      color: colors.textTertiary,
      marginTop: 1,
    },
    description: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 18,
      marginTop: 8,
    },
    helperText: {
      fontSize: 12,
      color: colors.textTertiary,
      lineHeight: 17,
      marginTop: 8,
    },
    surfaceRow: {
      marginTop: 10,
      gap: 8,
    },
    surfaceLabel: {
      fontSize: 12,
      color: colors.textSecondary,
      fontWeight: '600',
    },
    surfaceChips: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    surfaceChip: {
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 999,
      backgroundColor: colors.surfaceAlt,
      borderWidth: 1,
      borderColor: colors.subtleBorder,
    },
    surfaceChipText: {
      fontSize: 11,
      color: colors.textSecondary,
      fontWeight: '600',
    },
    browseMetaRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 10,
    },
    metaText: {
      fontSize: 12,
      color: colors.textTertiary,
    },
    toolsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginTop: 8,
    },
    toolsText: {
      fontSize: 12,
      color: colors.textTertiary,
    },
    statusPill: {
      marginTop: 10,
      alignSelf: 'flex-start',
      backgroundColor: colors.primarySoft,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    statusPillText: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.warning || colors.primary,
    },
    setupRow: {
      marginTop: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    setupText: {
      flex: 1,
      fontSize: 12,
      color: colors.textSecondary,
    },
    setupButton: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 10,
      backgroundColor: colors.primarySoft,
      borderWidth: 1,
      borderColor: colors.primary,
    },
    setupButtonText: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.primary,
    },
    cardFooter: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 12,
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: colors.subtleBorder,
    },
    source: {
      fontSize: 11,
      color: colors.textTertiary,
      textTransform: 'capitalize',
    },
    empty: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 40,
      marginTop: 60,
    },
    emptyTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: colors.textSecondary,
      marginTop: 16,
    },
    emptyText: {
      fontSize: 14,
      color: colors.textTertiary,
      textAlign: 'center',
      marginTop: 8,
      lineHeight: 20,
    },
    modalOverlay: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'rgba(0,0,0,0.4)',
    },
    modalContent: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      padding: 20,
      paddingBottom: 40,
    },
    browseIntroCard: {
      marginBottom: 12,
      padding: 14,
      borderRadius: 12,
      backgroundColor: colors.surfaceAlt,
      borderWidth: 1,
      borderColor: colors.border,
    },
    browseIntroTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
    },
    browseIntroText: {
      marginTop: 6,
      fontSize: 13,
      lineHeight: 18,
      color: colors.textSecondary,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.text,
    },
    modalHelp: {
      fontSize: 13,
      lineHeight: 18,
      color: colors.textSecondary,
      marginBottom: 12,
    },
    modalCaption: {
      fontSize: 12,
      color: colors.textTertiary,
      marginBottom: 8,
    },
    modeRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 14,
    },
    modeBtn: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceAlt,
      alignItems: 'center',
    },
    modeBtnActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primarySoft,
    },
    modeBtnText: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    modeBtnTextActive: {
      color: colors.primary,
    },
    modalInput: {
      backgroundColor: colors.inputBackground,
      borderRadius: 10,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 15,
      color: colors.text,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      marginBottom: 12,
    },
    modalButton: {
      backgroundColor: colors.primary,
      borderRadius: 10,
      paddingVertical: 14,
      alignItems: 'center',
      marginTop: 4,
    },
    modalButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
    },
    secondaryButton: {
      flex: 1,
      borderRadius: 10,
      paddingVertical: 14,
      alignItems: 'center',
      backgroundColor: colors.surfaceAlt,
      borderWidth: 1,
      borderColor: colors.border,
    },
    secondaryButtonText: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    tabRow: {
      flexDirection: 'row',
      paddingHorizontal: 16,
      paddingVertical: 8,
      gap: 8,
      backgroundColor: colors.background,
    },
    tabBtn: {
      flex: 1,
      paddingVertical: 8,
      borderRadius: 8,
      alignItems: 'center',
      backgroundColor: colors.inputBackground,
    },
    tabBtnActive: {
      backgroundColor: colors.primarySoft || colors.primary + '22',
    },
    tabText: {
      fontSize: 14,
      color: colors.textSecondary,
      fontWeight: '500',
    },
    tabTextActive: {
      color: colors.primary,
      fontWeight: '600',
    },
    browseContainer: {
      flex: 1,
    },
    searchRow: {
      flexDirection: 'row',
      paddingHorizontal: 16,
      paddingVertical: 8,
      gap: 8,
      alignItems: 'center',
    },
    searchBtn: {
      padding: 10,
    },
    listFooter: {
      paddingVertical: 16,
      alignItems: 'center',
    },
    secretLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 4,
    },
    secretHint: {
      fontSize: 12,
      lineHeight: 17,
      color: colors.textTertiary,
      marginBottom: 8,
    },
    setupLoader: {
      paddingVertical: 24,
    },
    setupFooter: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 4,
    },
  });
