import { StyleSheet } from 'react-native';
import type { AppPalette } from '../../theme/useAppTheme';

export const createTerminalScreenStyles = (colors: AppPalette) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    flex: { flex: 1 },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      minHeight: 56,
      paddingHorizontal: 8,
      paddingVertical: 6,
      backgroundColor: colors.header,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerTitle: {
      flex: 1,
      fontSize: 17,
      fontWeight: '600',
      color: colors.text,
      textAlign: 'center',
    },
    headerActions: {
      width: 44,
      minHeight: 44,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
    },
    connectedBadge: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: colors.success + '22',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modeBar: {
      flexDirection: 'row',
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      backgroundColor: colors.surface,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    modeButton: {
      flex: 1,
      minHeight: 44,
      paddingHorizontal: 6,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.background,
    },
    modeButtonActive: { backgroundColor: colors.primary, borderColor: colors.primary },
    modeButtonText: { color: colors.text, fontWeight: '600', fontSize: 13 },
    modeButtonTextActive: { color: colors.onPrimary },
    runtimeNotice: {
      backgroundColor: colors.warning + '15',
      borderBottomColor: colors.warning,
      borderBottomWidth: 1,
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    runtimeNoticeText: {
      color: colors.text,
      fontSize: 13,
      lineHeight: 19,
    },
    sshPicker: {
      paddingHorizontal: 12,
      paddingVertical: 10,
      backgroundColor: colors.surface,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    sshSessionBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      backgroundColor: colors.surface,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    sshSessionText: { flex: 1, color: colors.text, fontSize: 13, fontFamily: 'monospace' },
    sshSessionAction: { color: colors.primary, fontSize: 13, fontWeight: '600' },
    sshSessionActionButton: {
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 44,
      paddingHorizontal: 8,
    },
    sshEmptyState: {
      alignItems: 'center',
      gap: 10,
      paddingVertical: 4,
    },
    sshPickerEmpty: {
      color: colors.textSecondary,
      fontSize: 13,
      textAlign: 'center',
      paddingVertical: 8,
    },
    sshSetupButton: {
      alignItems: 'center',
      backgroundColor: colors.primary,
      borderRadius: 999,
      justifyContent: 'center',
      minHeight: 44,
      paddingHorizontal: 16,
    },
    sshSetupButtonText: {
      color: colors.onPrimary,
      fontSize: 13,
      fontWeight: '700',
    },
    sshTargetBtn: {
      justifyContent: 'center',
      minHeight: 52,
      paddingVertical: 8,
      paddingHorizontal: 14,
      backgroundColor: colors.background,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 6,
    },
    sshTargetBtnDisabled: { opacity: 0.55 },
    sshTargetText: { color: colors.text, fontSize: 13, fontFamily: 'monospace' },
    sshTargetMeta: { color: colors.textSecondary, fontSize: 12, marginTop: 4 },
  });
