import { StyleSheet, Dimensions } from 'react-native';
import type { AppPalette } from '../../theme/useAppTheme';

const { width } = Dimensions.get('window');
const CARD_WIDTH = (width - 64) / 2;

export const createOnboardingWizardStyles = (colors: AppPalette) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    centered: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 24,
    },
    scrollContent: {
      padding: 24,
      paddingTop: 60,
    },
    logoBadge: {
      width: 112,
      height: 112,
      borderRadius: 28,
      overflow: 'hidden',
      marginBottom: 20,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.18,
      shadowRadius: 20,
      elevation: 10,
    },
    logoImage: {
      width: '100%',
      height: '100%',
    },
    title: {
      fontSize: 28,
      fontWeight: '800',
      color: colors.text,
      textAlign: 'center',
      marginBottom: 8,
    },
    subtitle: {
      fontSize: 16,
      color: colors.textSecondary,
      textAlign: 'center',
      lineHeight: 22,
      marginBottom: 24,
      maxWidth: 340,
    },
    heroCard: {
      width: '100%',
      backgroundColor: colors.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 18,
      marginBottom: 24,
      gap: 8,
    },
    heroTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
    },
    heroText: {
      fontSize: 14,
      color: colors.textSecondary,
      lineHeight: 20,
    },
    stepTitle: {
      fontSize: 22,
      fontWeight: '700',
      color: colors.text,
      textAlign: 'center',
      marginBottom: 8,
      marginTop: 16,
    },
    stepSubtitle: {
      fontSize: 14,
      color: colors.textSecondary,
      textAlign: 'center',
      lineHeight: 20,
      marginBottom: 24,
      maxWidth: 340,
      alignSelf: 'center',
    },
    stepIcon: {
      alignSelf: 'center',
      marginTop: 6,
      marginBottom: 8,
    },
    progressRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 18,
    },
    progressPill: {
      flex: 1,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
    },
    progressPillActive: {
      backgroundColor: colors.primarySoft,
      borderColor: colors.primary,
    },
    progressPillText: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    progressPillTextActive: {
      color: colors.text,
    },
    featureList: {
      alignSelf: 'flex-start',
      marginLeft: 20,
      marginBottom: 32,
    },
    featureItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 10,
    },
    featureText: {
      fontSize: 15,
      color: colors.text,
    },
    providerGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
      justifyContent: 'center',
      marginBottom: 24,
    },
    providerCard: {
      width: CARD_WIDTH,
      backgroundColor: colors.surface,
      borderRadius: 14,
      padding: 20,
      alignItems: 'flex-start',
      gap: 8,
      borderWidth: 1,
      borderColor: colors.border,
      minHeight: 220,
    },
    providerName: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
    },
    providerBadge: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.primary,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    providerSummary: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 19,
      flex: 1,
    },
    guideFooter: {
      marginTop: 'auto',
    },
    providerModel: {
      fontSize: 12,
      color: colors.textTertiary,
      lineHeight: 18,
    },
    input: {
      width: '100%',
      backgroundColor: colors.inputBackground,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingVertical: 14,
      fontSize: 16,
      color: colors.text,
      marginBottom: 20,
    },
    guideCard: {
      width: '100%',
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 16,
      padding: 18,
      marginBottom: 18,
      gap: 10,
    },
    guideTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
    },
    guideText: {
      fontSize: 14,
      color: colors.textSecondary,
      lineHeight: 20,
    },
    guideFree: {
      fontSize: 13,
      color: colors.primary,
      lineHeight: 18,
      fontWeight: '600',
    },
    primaryBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      backgroundColor: colors.primary,
      paddingVertical: 14,
      paddingHorizontal: 28,
      borderRadius: 12,
      width: '100%',
      marginBottom: 12,
    },
    primaryBtnText: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.onPrimary,
    },
    disabledBtn: {
      opacity: 0.5,
    },
    secondaryBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 12,
      width: '100%',
      marginBottom: 12,
    },
    secondaryBtnText: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.text,
    },
    skipBtn: {
      paddingVertical: 10,
    },
    skipBtnText: {
      fontSize: 14,
      color: colors.textSecondary,
    },
    infoCard: {
      width: '100%',
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      padding: 16,
      flexDirection: 'row',
      gap: 12,
      marginBottom: 18,
    },
    infoCardBody: {
      flex: 1,
      gap: 4,
    },
    infoCardTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
    },
    infoCardText: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 18,
    },
    optionWrap: {
      gap: 12,
      marginBottom: 18,
    },
    optionCard: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      padding: 16,
      gap: 6,
    },
    optionCardActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primarySoft,
    },
    optionTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.text,
    },
    optionText: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 18,
    },
    sectionIntro: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 14,
      alignItems: 'flex-start',
    },
    sectionIntroText: {
      flex: 1,
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 18,
    },
    moreServicesToggle: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingVertical: 12,
      marginBottom: 8,
    },
    moreServicesText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.primary,
    },
    serviceCard: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 16,
      padding: 16,
      marginBottom: 14,
    },
    serviceHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      marginBottom: 8,
    },
    serviceHeaderBody: {
      flex: 1,
    },
    serviceTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.text,
    },
    serviceCategory: {
      fontSize: 12,
      color: colors.primary,
      fontWeight: '600',
      marginTop: 2,
    },
    serviceGuideButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 999,
    },
    serviceGuideText: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.text,
    },
    serviceUnlocks: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 6,
      lineHeight: 18,
    },
    serviceBody: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 18,
      marginBottom: 6,
    },
    serviceFree: {
      fontSize: 12,
      color: colors.primary,
      lineHeight: 18,
      marginBottom: 12,
    },
    summaryGrid: {
      width: '100%',
      gap: 12,
      marginBottom: 20,
    },
    summaryCard: {
      backgroundColor: colors.surface,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
      gap: 6,
    },
    summaryTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.text,
    },
    summaryText: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 18,
    },
    tipBox: {
      width: '100%',
      backgroundColor: colors.surface,
      borderRadius: 12,
      padding: 16,
      marginBottom: 24,
      borderWidth: 1,
      borderColor: colors.border,
    },
    tipTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 8,
    },
    tipText: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 20,
    },
    featureDiscoveryCard: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 14,
      backgroundColor: colors.surface,
      borderRadius: 12,
      padding: 16,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: colors.border,
    },
    featureDiscoveryIcon: {
      width: 40,
      height: 40,
      borderRadius: 10,
      backgroundColor: colors.primarySoft,
      justifyContent: 'center',
      alignItems: 'center',
    },
    featureDiscoveryTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 2,
    },
    featureDiscoveryDesc: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 18,
    },
  });
