// ---------------------------------------------------------------------------
// Kavi — E2E benchmark-adapted scenarios (structural rubrics)
// ---------------------------------------------------------------------------
import * as memoryScenarios from './benchmarkMemoryScenarios';
import * as nativeScenarios from './benchmarkNativeScenarios';
import * as promptCacheScenarios from './benchmarkPromptCacheScenarios';
import * as workspaceScenarios from './benchmarkWorkspaceScenarios';
import type { E2EScenario } from './types';

export {
  BENCH_BFCL_SEQUENTIAL_MEMORY_CHAIN,
  BENCH_KNOWU_PERSONALIZED_CONTACT_MEMORY,
  BENCH_LONGMEM_ABSTENTION_EMPTY_RECALL,
  BENCH_LONGMEM_DELAYED_RECALL,
  BENCH_LONGMEM_DUAL_FACT_RECALL,
  BENCH_LONGMEM_KNOWLEDGE_UPDATE_RECALL,
  BENCH_MEMORY_STATE_3TURN_RECALL,
  BENCH_SCOPED_RECALL_GOAL_SWITCH,
  BENCH_SESSION_TOOL_CACHE,
  BENCH_TOOL_DESCRIBE_THEN_USE,
} from './benchmarkMemoryScenarios';
export {
  BENCH_ANDROIDWORLD_CALENDAR_MUTATION,
  BENCH_ANDROIDWORLD_CLIPBOARD_SHARE_NOTIFY,
  BENCH_ANDROIDWORLD_PERMISSION_DENIAL,
  BENCH_GOAL_JSON_FIELD_CRITERION,
  BENCH_MOBILEAGENT_CONTACT_MESSAGE_DRAFT,
  BENCH_MOBILEAGENT_MEDIA_STATE,
  BENCH_MOBILEWORLD_DISCOVER_CONTACT_MESSAGE,
  BENCH_TAU_CALENDAR_EVENTS_CHAIN,
  BENCH_TAU_NATIVE_JSON_OUTCOME,
} from './benchmarkNativeScenarios';
export {
  BENCH_PROMPT_CACHE_CONVERGENCE_LONG_RUN,
  BENCH_PROMPT_CACHE_LONG_HORIZON,
} from './benchmarkPromptCacheScenarios';
export {
  BENCH_AGENTBENCH_TOOL_CHAIN,
  BENCH_BFCL_MULTI_TURN_STATE_CARRY,
  BENCH_BFCL_PARALLEL_FILE_READ,
  BENCH_BFCL_PASSIVE_NO_TOOLS,
  BENCH_BOOTSTRAP_FIRST_TURN_GOALS,
  BENCH_GAIA_FILE_HOP_CHAIN,
} from './benchmarkWorkspaceScenarios';

export const E2E_BENCHMARK_SCENARIOS: ReadonlyArray<E2EScenario> = [
  workspaceScenarios.BENCH_GAIA_FILE_HOP_CHAIN,
  memoryScenarios.BENCH_SESSION_TOOL_CACHE,
  promptCacheScenarios.BENCH_PROMPT_CACHE_LONG_HORIZON,
  promptCacheScenarios.BENCH_PROMPT_CACHE_CONVERGENCE_LONG_RUN,
  memoryScenarios.BENCH_TOOL_DESCRIBE_THEN_USE,
  memoryScenarios.BENCH_MEMORY_STATE_3TURN_RECALL,
  nativeScenarios.BENCH_GOAL_JSON_FIELD_CRITERION,
  memoryScenarios.BENCH_SCOPED_RECALL_GOAL_SWITCH,
  workspaceScenarios.BENCH_BOOTSTRAP_FIRST_TURN_GOALS,
  nativeScenarios.BENCH_TAU_NATIVE_JSON_OUTCOME,
  nativeScenarios.BENCH_TAU_CALENDAR_EVENTS_CHAIN,
  workspaceScenarios.BENCH_AGENTBENCH_TOOL_CHAIN,
  workspaceScenarios.BENCH_BFCL_PARALLEL_FILE_READ,
  memoryScenarios.BENCH_BFCL_SEQUENTIAL_MEMORY_CHAIN,
  workspaceScenarios.BENCH_BFCL_MULTI_TURN_STATE_CARRY,
  workspaceScenarios.BENCH_BFCL_PASSIVE_NO_TOOLS,
  memoryScenarios.BENCH_LONGMEM_DELAYED_RECALL,
  memoryScenarios.BENCH_LONGMEM_DUAL_FACT_RECALL,
  memoryScenarios.BENCH_LONGMEM_KNOWLEDGE_UPDATE_RECALL,
  memoryScenarios.BENCH_LONGMEM_ABSTENTION_EMPTY_RECALL,
  nativeScenarios.BENCH_ANDROIDWORLD_CALENDAR_MUTATION,
  nativeScenarios.BENCH_ANDROIDWORLD_PERMISSION_DENIAL,
  nativeScenarios.BENCH_MOBILEAGENT_CONTACT_MESSAGE_DRAFT,
  nativeScenarios.BENCH_MOBILEWORLD_DISCOVER_CONTACT_MESSAGE,
  memoryScenarios.BENCH_KNOWU_PERSONALIZED_CONTACT_MEMORY,
  nativeScenarios.BENCH_ANDROIDWORLD_CLIPBOARD_SHARE_NOTIFY,
  nativeScenarios.BENCH_MOBILEAGENT_MEDIA_STATE,
];
