import {
  PYODIDE_RESULT_CACHE_LIMIT,
  PYODIDE_WEBVIEW_BASE_URL,
  PYODIDE_WEBVIEW_BRIDGE_NAME,
} from './runtimeProtocol';
import {
  MAX_PYTHON_WORKFLOW_BRIDGE_CONTENT_CHARS,
  MAX_PYTHON_WORKFLOW_BRIDGE_ENTRIES,
  PYTHON_WORKFLOW_BRIDGE_KIND_VALUES,
  PYTHON_WORKFLOW_BRIDGE_RECORDER_VALUES,
  PYTHON_WORKFLOW_BRIDGE_STATUS_VALUES,
} from './workflowBridge';

const PYODIDE_RUNTIME_HELPERS = [
  'import importlib',
  'import json as _kavi_json',
  'import os',
  'import builtins',
  'import pyodide.http as _kavi_pyodide_http',
  'import sys',
  'import types as _kavi_types',
  'import traceback',
  'from js import __kavi_native_http__, __kavi_workflow_bridge__',
  'from pyodide.code import eval_code_async',
  'from pyodide.http import pyfetch as _kavi_browser_pyfetch',
  'from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit',
  '',
  'def _kavi_stringify_result(value):',
  '    if value is None:',
  '        return None',
  '    rendered = str(value)',
  '    if not rendered or rendered == "None":',
  '        return None',
  '    return rendered',
  '',
  'def _kavi_serialize_execution(result_value=None, error=None):',
  '    return _kavi_json.dumps({',
  '        "result_text": _kavi_stringify_result(result_value),',
  '        "error": error,',
  '    }, ensure_ascii=False)',
  '',
  'def _kavi_clear_workspace_modules(workspace_root: str) -> None:',
  '    normalized_root = os.path.normpath(workspace_root)',
  '    prefix = normalized_root + os.sep',
  '    for module_name, module in list(sys.modules.items()):',
  '        module_path = getattr(module, "__file__", None)',
  '        if not module_path:',
  '            continue',
  '        try:',
  '            normalized_path = os.path.normpath(module_path)',
  '        except Exception:',
  '            continue',
  '        if normalized_path == normalized_root or normalized_path.startswith(prefix):',
  '            del sys.modules[module_name]',
  '',
  'def _kavi_prepare_execution(workspace_root: str) -> None:',
  '    _kavi_clear_workspace_modules(workspace_root)',
  '    importlib.invalidate_caches()',
  '',
  'def _kavi_prepare_sys_path(workspace_root: str, working_directory: str, script_dir: str | None = None) -> None:',
  '    for candidate in (workspace_root, working_directory, script_dir):',
  '        if not candidate:',
  '            continue',
  '        normalized = os.path.normpath(candidate)',
  '        if normalized and normalized not in sys.path:',
  '            sys.path.insert(0, normalized)',
  '',
  'def _kavi_workflow_bridge_enabled() -> bool:',
  '    try:',
  '        return bool(__kavi_workflow_bridge__.is_enabled())',
  '    except Exception:',
  '        return False',
  '',
  'def _kavi_get_workflow_evidence_snapshot() -> list[dict]:',
  '    if not _kavi_workflow_bridge_enabled():',
  '        return []',
  '    try:',
  '        payload = __kavi_workflow_bridge__.get_state_json()',
  '    except Exception:',
  '        return []',
  '    if not payload:',
  '        return []',
  '    try:',
  '        parsed = _kavi_json.loads(payload)',
  '    except Exception:',
  '        return []',
  '    return parsed if isinstance(parsed, list) else []',
  '',
  'def _kavi_normalize_str_collection(value):',
  '    if value is None:',
  '        return None',
  '    if isinstance(value, str):',
  '        normalized = value.strip()',
  '        return {normalized} if normalized else None',
  '    if isinstance(value, (list, tuple, set)):',
  '        items = {str(item).strip() for item in value if str(item).strip()}',
  '        return items or None',
  '    return None',
  '',
  'def _kavi_filter_workflow_evidence_entries(',
  '    entries: list[dict],',
  '    kinds=None,',
  '    statuses=None,',
  '    recorders=None,',
  '    query: str | None = None,',
  '    limit: int | None = 12,',
  '    include_content: bool = True,',
  '):',
  '    kind_set = _kavi_normalize_str_collection(kinds)',
  '    status_set = _kavi_normalize_str_collection(statuses)',
  '    recorder_set = _kavi_normalize_str_collection(recorders)',
  '    query_text = query.strip().lower() if isinstance(query, str) and query.strip() else None',
  '    try:',
  '        normalized_limit = max(1, min(int(limit or 12), 24))',
  '    except Exception:',
  '        normalized_limit = 12',
  '',
  '    filtered = []',
  '    for entry in entries:',
  '        if not isinstance(entry, dict):',
  '            continue',
  '        kind = str(entry.get("kind") or "").strip()',
  '        status = str(entry.get("status") or "").strip()',
  '        recorder = str(entry.get("recorder") or "").strip()',
  '        if kind_set and kind not in kind_set:',
  '            continue',
  '        if status_set and status not in status_set:',
  '            continue',
  '        if recorder_set and recorder not in recorder_set:',
  '            continue',
  '        if query_text:',
  '            haystack = "\\n".join([',
  '                str(entry.get("title") or ""),',
  '                str(entry.get("content") or ""),',
  '                str(entry.get("sourceName") or ""),',
  '                str(entry.get("sourceUri") or ""),',
  '                str(entry.get("toolName") or ""),',
  '                str(entry.get("workerSessionId") or ""),',
  '                str(entry.get("artifactWorkspacePath") or ""),',
  '                " ".join(entry.get("tags") or []),',
  '            ]).lower()',
  '            if query_text not in haystack:',
  '                continue',
  '        payload = dict(entry)',
  '        if not include_content:',
  '            payload.pop("content", None)',
  '        filtered.append(payload)',
  '',
  '    return filtered[-normalized_limit:]',
  '',
  'def _kavi_record_workflow_evidence(entries=None, **entry) -> int:',
  '    if entries is None:',
  '        entries = [entry] if entry else []',
  '    elif isinstance(entries, dict):',
  '        entries = [entries]',
  '    elif not isinstance(entries, (list, tuple)):',
  '        entries = []',
  '',
  '    normalized_entries = [candidate for candidate in entries if isinstance(candidate, dict)]',
  '    if not normalized_entries or not _kavi_workflow_bridge_enabled():',
  '        return 0',
  '',
  '    try:',
  '        return int(__kavi_workflow_bridge__.record_entries_json(_kavi_json.dumps(normalized_entries, ensure_ascii=False)) or 0)',
  '    except Exception:',
  '        return 0',
  '',
  'async def _kavi_native_pyfetch(request, /, *, fetcher=None, **kwargs):',
  '    resolved_fetcher = fetcher if fetcher is not None else getattr(__kavi_native_http__, "fetch", None)',
  '    if resolved_fetcher is None:',
  '        raise RuntimeError("Native HTTP bridge is not available.")',
  '    return await _kavi_browser_pyfetch(request, fetcher=resolved_fetcher, **kwargs)',
  '',
  'def _kavi_normalize_timeout_ms(timeout=None, timeout_ms=None, timeoutMs=None):',
  '    explicit_timeout_ms = timeout_ms if timeout_ms is not None else timeoutMs',
  '    if explicit_timeout_ms is not None:',
  '        return int(explicit_timeout_ms)',
  '    if timeout is None:',
  '        return None',
  '    return max(1, int(float(timeout) * 1000))',
  '',
  'def _kavi_normalize_query_params(params):',
  '    if params is None:',
  '        return []',
  '    if isinstance(params, dict):',
  '        items = params.items()',
  '    elif isinstance(params, (list, tuple)):',
  '        items = params',
  '    else:',
  '        raise TypeError("params must be a dict or a list of key/value pairs.")',
  '',
  '    normalized = []',
  '    for item in items:',
  '        try:',
  '            key, value = item',
  '        except Exception as exc:',
  '            raise TypeError("params must be a dict or a list of key/value pairs.") from exc',
  '        if value is None:',
  '            continue',
  '        if isinstance(value, (list, tuple)):',
  '            for inner in value:',
  '                if inner is None:',
  '                    continue',
  '                normalized.append((str(key), str(inner)))',
  '        else:',
  '            normalized.append((str(key), str(value)))',
  '    return normalized',
  '',
  'def _kavi_merge_query_params(url: str, params=None) -> str:',
  '    normalized = _kavi_normalize_query_params(params)',
  '    if not normalized:',
  '        return url',
  '    split = urlsplit(url)',
  '    combined = parse_qsl(split.query, keep_blank_values=True)',
  '    combined.extend(normalized)',
  '    return urlunsplit((split.scheme, split.netloc, split.path, urlencode(combined, doseq=True), split.fragment))',
  '',
  'class _KaviHttpResponse:',
  '    def __init__(self, response):',
  '        self._response = response',
  '',
  '    @property',
  '    def ok(self):',
  '        return bool(getattr(self._response, "ok", False))',
  '',
  '    @property',
  '    def status(self):',
  '        return int(getattr(self._response, "status", 0) or 0)',
  '',
  '    @property',
  '    def status_code(self):',
  '        return self.status',
  '',
  '    @property',
  '    def status_text(self):',
  '        return str(getattr(self._response, "statusText", "") or "")',
  '',
  '    @property',
  '    def headers(self):',
  '        return getattr(self._response, "headers", None)',
  '',
  '    @property',
  '    def url(self):',
  '        return str(getattr(self._response, "url", "") or "")',
  '',
  '    @property',
  '    def redirected(self):',
  '        return bool(getattr(self._response, "redirected", False))',
  '',
  '    async def text(self):',
  '        return await self._response.text()',
  '',
  '    async def json(self):',
  '        return await self._response.json()',
  '',
  '    async def array_buffer(self):',
  '        return await self._response.arrayBuffer()',
  '',
  '    def raise_for_status(self):',
  '        if self.ok:',
  '            return self',
  '        detail = f"HTTP {self.status_code}"',
  '        if self.status_text:',
  '            detail += f" {self.status_text}"',
  '        if self.url:',
  '            detail += f" for {self.url}"',
  '        raise RuntimeError(detail)',
  '',
  '    def require_success(self):',
  '        return self.raise_for_status()',
  '',
  'async def _kavi_http_request(',
  '    url: str,',
  '    *,',
  '    method: str = "GET",',
  '    headers=None,',
  '    data=None,',
  '    json=None,',
  '    params=None,',
  '    timeout=None,',
  '    timeout_ms: int | None = None,',
  '    timeoutMs: int | None = None,',
  '    **kwargs,',
  '):',
  '    request_url = _kavi_merge_query_params(url, params)',
  '    request_headers = {}',
  '    if headers:',
  '        request_headers = {str(key): str(value) for key, value in dict(headers).items()}',
  '    if json is not None and data is not None:',
  '        raise ValueError("Pass either data or json, not both.")',
  '    body = data',
  '    if json is not None:',
  '        body = _kavi_json.dumps(json, ensure_ascii=False)',
  '        request_headers.setdefault("Content-Type", "application/json")',
  '    request_kwargs = dict(kwargs)',
  '    request_kwargs["method"] = str(method or "GET")',
  '    if request_headers:',
  '        request_kwargs["headers"] = request_headers',
  '    if body is not None:',
  '        request_kwargs["body"] = body',
  '    timeout_value = _kavi_normalize_timeout_ms(timeout=timeout, timeout_ms=timeout_ms, timeoutMs=timeoutMs)',
  '    if timeout_value is not None:',
  '        request_kwargs["timeout_ms"] = int(timeout_value)',
  '    response = await _kavi_native_pyfetch(request_url, **request_kwargs)',
  '    return _KaviHttpResponse(response)',
  '',
  'class _KaviHttpClient:',
  '    def is_available(self) -> bool:',
  '        try:',
  '            return bool(getattr(__kavi_native_http__, "is_available", lambda: False)())',
  '        except Exception:',
  '            return False',
  '',
  '    async def fetch(self, url: str, **kwargs):',
  '        return await _kavi_http_request(url, **kwargs)',
  '',
  '    async def request(self, url: str, **kwargs):',
  '        return await _kavi_http_request(url, **kwargs)',
  '',
  '    async def get(self, url: str, **kwargs):',
  '        return await _kavi_http_request(url, method="GET", **kwargs)',
  '',
  '    async def post(self, url: str, **kwargs):',
  '        return await _kavi_http_request(url, method="POST", **kwargs)',
  '',
  '    async def put(self, url: str, **kwargs):',
  '        return await _kavi_http_request(url, method="PUT", **kwargs)',
  '',
  '    async def patch(self, url: str, **kwargs):',
  '        return await _kavi_http_request(url, method="PATCH", **kwargs)',
  '',
  '    async def delete(self, url: str, **kwargs):',
  '        return await _kavi_http_request(url, method="DELETE", **kwargs)',
  '',
  '    async def head(self, url: str, **kwargs):',
  '        return await _kavi_http_request(url, method="HEAD", **kwargs)',
  '',
  '    async def options(self, url: str, **kwargs):',
  '        return await _kavi_http_request(url, method="OPTIONS", **kwargs)',
  '',
  '    async def get_text(self, url: str, **kwargs):',
  '        response = await self.get(url, **kwargs)',
  '        response.raise_for_status()',
  '        return await response.text()',
  '',
  '    async def get_json(self, url: str, **kwargs):',
  '        response = await self.get(url, **kwargs)',
  '        response.raise_for_status()',
  '        return await response.json()',
  '',
  '    async def post_text(self, url: str, **kwargs):',
  '        response = await self.post(url, **kwargs)',
  '        response.raise_for_status()',
  '        return await response.text()',
  '',
  '    async def post_json(self, url: str, **kwargs):',
  '        response = await self.post(url, **kwargs)',
  '        response.raise_for_status()',
  '        return await response.json()',
  '',
  '    async def request_text(self, url: str, **kwargs):',
  '        response = await self.request(url, **kwargs)',
  '        response.raise_for_status()',
  '        return await response.text()',
  '',
  '    async def request_json(self, url: str, **kwargs):',
  '        response = await self.request(url, **kwargs)',
  '        response.raise_for_status()',
  '        return await response.json()',
  '',
  '_kavi_pyodide_http.pyfetch = _kavi_native_pyfetch',
  '',
  'class _KaviBridge:',
  '    def __init__(self, http_module):',
  '        self.http = http_module',
  '',
  '    def has_workflow_bridge(self) -> bool:',
  '        return _kavi_workflow_bridge_enabled()',
  '',
  '    def read_workflow_evidence(',
  '        self,',
  '        kinds=None,',
  '        statuses=None,',
  '        recorders=None,',
  '        query: str | None = None,',
  '        limit: int | None = 12,',
  '        include_content: bool = True,',
  '    ):',
  '        return _kavi_filter_workflow_evidence_entries(',
  '            _kavi_get_workflow_evidence_snapshot(),',
  '            kinds=kinds,',
  '            statuses=statuses,',
  '            recorders=recorders,',
  '            query=query,',
  '            limit=limit,',
  '            include_content=include_content,',
  '        )',
  '',
  '    def record_workflow_evidence(self, entries=None, **entry) -> int:',
  '        return _kavi_record_workflow_evidence(entries=entries, **entry)',
  '',
  '_kavi_http_client = _KaviHttpClient()',
  '_kavi_http_module = _kavi_types.ModuleType("kavi.http")',
  '_kavi_http_module.__package__ = "kavi"',
  '_kavi_http_module.__all__ = ["Response", "fetch", "request", "get", "post", "put", "patch", "delete", "head", "options", "get_text", "get_json", "post_text", "post_json", "request_text", "request_json", "is_available"]',
  '_kavi_http_module.Response = _KaviHttpResponse',
  '_kavi_http_module.fetch = _kavi_http_client.fetch',
  '_kavi_http_module.request = _kavi_http_client.request',
  '_kavi_http_module.get = _kavi_http_client.get',
  '_kavi_http_module.post = _kavi_http_client.post',
  '_kavi_http_module.put = _kavi_http_client.put',
  '_kavi_http_module.patch = _kavi_http_client.patch',
  '_kavi_http_module.delete = _kavi_http_client.delete',
  '_kavi_http_module.head = _kavi_http_client.head',
  '_kavi_http_module.options = _kavi_http_client.options',
  '_kavi_http_module.get_text = _kavi_http_client.get_text',
  '_kavi_http_module.get_json = _kavi_http_client.get_json',
  '_kavi_http_module.post_text = _kavi_http_client.post_text',
  '_kavi_http_module.post_json = _kavi_http_client.post_json',
  '_kavi_http_module.request_text = _kavi_http_client.request_text',
  '_kavi_http_module.request_json = _kavi_http_client.request_json',
  '_kavi_http_module.is_available = _kavi_http_client.is_available',
  '_kavi_bridge = _KaviBridge(_kavi_http_module)',
  '_kavi_module = _kavi_types.ModuleType("kavi")',
  '_kavi_module.__path__ = []',
  '_kavi_module.__all__ = ["http", "has_workflow_bridge", "read_workflow_evidence", "record_workflow_evidence"]',
  '_kavi_module.http = _kavi_http_module',
  '_kavi_module.has_workflow_bridge = _kavi_bridge.has_workflow_bridge',
  '_kavi_module.read_workflow_evidence = _kavi_bridge.read_workflow_evidence',
  '_kavi_module.record_workflow_evidence = _kavi_bridge.record_workflow_evidence',
  'sys.modules["kavi.http"] = _kavi_http_module',
  'sys.modules["kavi"] = _kavi_module',
  'builtins.kavi = _kavi_module',
  '',
  'async def _kavi_execute_inline(code: str, working_directory: str, workspace_root: str) -> str:',
  '    namespace = {',
  '        "__name__": "__main__",',
  '        "__file__": "<inline>",',
  '        "__package__": None,',
  '        "__builtins__": __builtins__,',
  '    }',
  '    previous_path = sys.path[:]',
  '    previous_cwd = os.getcwd()',
  '    try:',
  '        os.chdir(working_directory)',
  '        _kavi_prepare_execution(workspace_root)',
  '        _kavi_prepare_sys_path(workspace_root, working_directory)',
  '        result_value = await eval_code_async(',
  '            code,',
  '            globals=namespace,',
  '            locals=namespace,',
  '            filename="<inline>",',
  '            return_mode="last_expr",',
  '        )',
  '        return _kavi_serialize_execution(result_value=result_value)',
  '    except BaseException:',
  '        return _kavi_serialize_execution(error=traceback.format_exc())',
  '    finally:',
  '        sys.path[:] = previous_path',
  '        os.chdir(previous_cwd)',
  '',
  'async def _kavi_execute_script(script_path: str, argv: list[str], working_directory: str, workspace_root: str) -> str:',
  '    previous_argv = sys.argv[:]',
  '    previous_path = sys.path[:]',
  '    previous_cwd = os.getcwd()',
  '    script_dir = os.path.dirname(script_path) or working_directory',
  '    namespace = {',
  '        "__name__": "__main__",',
  '        "__file__": script_path,',
  '        "__package__": None,',
  '        "__builtins__": __builtins__,',
  '    }',
  '    try:',
  '        os.chdir(working_directory)',
  '        _kavi_prepare_execution(workspace_root)',
  '        _kavi_prepare_sys_path(workspace_root, working_directory, script_dir)',
  '        sys.argv = [script_path, *argv]',
  '        with open(script_path, "r", encoding="utf-8") as handle:',
  '            source = handle.read()',
  '        await eval_code_async(',
  '            source,',
  '            globals=namespace,',
  '            locals=namespace,',
  '            filename=script_path,',
  '            return_mode="none",',
  '        )',
  '        return _kavi_serialize_execution()',
  '    except BaseException:',
  '        return _kavi_serialize_execution(error=traceback.format_exc())',
  '    finally:',
  '        sys.argv = previous_argv',
  '        sys.path[:] = previous_path',
  '        os.chdir(previous_cwd)',
].join('\n');

let pyodideHtmlCache: string | null = null;

function buildPyodideWorkerSource(): string {
  return [
    'var pyodide = null;',
    'var bootError = null;',
    'var installedPackageSpecs = Object.create(null);',
    'var injectedEnvKeys = [];',
    'var activeCapture = null;',
    'var activeWorkflowBridgeState = null;',
    'var pendingNativeHttpRequests = Object.create(null);',
    'var nativeHttpRequestCounter = 0;',
    "var WORKSPACE_ROOT = '/workspace';",
    `var MAX_WORKFLOW_BRIDGE_ENTRIES = ${MAX_PYTHON_WORKFLOW_BRIDGE_ENTRIES};`,
    `var MAX_WORKFLOW_BRIDGE_CONTENT_CHARS = ${MAX_PYTHON_WORKFLOW_BRIDGE_CONTENT_CHARS};`,
    'var MAX_WORKFLOW_BRIDGE_TITLE_CHARS = 120;',
    'var MAX_WORKFLOW_BRIDGE_OPTIONAL_TEXT_CHARS = 240;',
    'var MAX_WORKFLOW_BRIDGE_TAGS = 8;',
    `var ALLOWED_WORKFLOW_BRIDGE_KINDS = ${JSON.stringify(PYTHON_WORKFLOW_BRIDGE_KIND_VALUES)};`,
    `var ALLOWED_WORKFLOW_BRIDGE_STATUSES = ${JSON.stringify(PYTHON_WORKFLOW_BRIDGE_STATUS_VALUES)};`,
    `var ALLOWED_WORKFLOW_BRIDGE_RECORDERS = ${JSON.stringify(PYTHON_WORKFLOW_BRIDGE_RECORDER_VALUES)};`,
    `var PYODIDE_RUNTIME_HELPERS = ${JSON.stringify(PYODIDE_RUNTIME_HELPERS)};`,
    '',
    'function formatError(error) {',
    '  return error && error.message ? error.message : String(error);',
    '}',
    '',
    'function appendSegment(base, segment) {',
    '  if (!segment) {',
    '    return base;',
    '  }',
    '  if (!base) {',
    '    return segment;',
    '  }',
    '  return base + (base.endsWith("\\n") ? "" : "\\n") + segment;',
    '}',
    '',
    'function beginCapture() {',
    "  activeCapture = { stdout: '', stderr: '' };",
    '  return activeCapture;',
    '}',
    '',
    'function finishCapture() {',
    "  var capture = activeCapture || { stdout: '', stderr: '' };",
    '  activeCapture = null;',
    '  return capture;',
    '}',
    '',
    'function combineExecutionOutput(capture, resultText, hasError) {',
    "  var output = '';",
    '  output = appendSegment(output, capture && capture.stdout ? capture.stdout : "");',
    '  output = appendSegment(output, capture && capture.stderr ? capture.stderr : "");',
    '  output = appendSegment(output, resultText || "");',
    '  if (!output && !hasError) {',
    '    return "(no output)";',
    '  }',
    '  return output;',
    '}',
    '',
    'function onStdout(value) {',
    '  if (!activeCapture) {',
    '    return;',
    '  }',
    '  activeCapture.stdout = appendSegment(activeCapture.stdout, String(value || ""));',
    '}',
    '',
    'function onStderr(value) {',
    '  if (!activeCapture) {',
    '    return;',
    '  }',
    '  activeCapture.stderr = appendSegment(activeCapture.stderr, String(value || ""));',
    '}',
    '',
    'function normalizeWorkspaceRelativePath(input) {',
    '  var normalized = String(input || "")',
    '    .replace(/\\\\/g, "/")',
    '    .replace(/^\\/+/, "");',
    '',
    '  var segments = [];',
    '  normalized.split("/").forEach(function(segment) {',
    '    var trimmed = segment.trim();',
    '    if (!trimmed || trimmed === ".") {',
    '      return;',
    '    }',
    '    if (trimmed === "..") {',
    '      throw new Error(\'Workspace paths must not contain ".." segments.\');',
    '    }',
    '    segments.push(trimmed);',
    '  });',
    '',
    '  return segments.join("/");',
    '}',
    '',
    'function toWorkspaceFsPath(relativePath) {',
    '  var normalized = normalizeWorkspaceRelativePath(relativePath);',
    '  return normalized ? WORKSPACE_ROOT + "/" + normalized : WORKSPACE_ROOT;',
    '}',
    '',
    'function normalizePackageSpecs(packages) {',
    '  if (!Array.isArray(packages)) {',
    '    return [];',
    '  }',
    '',
    '  var normalized = [];',
    '  var seen = Object.create(null);',
    '  for (var index = 0; index < packages.length; index++) {',
    '    var spec = typeof packages[index] === "string" ? packages[index].trim() : "";',
    '    if (!spec || seen[spec]) {',
    '      continue;',
    '    }',
    '    seen[spec] = true;',
    '    normalized.push(spec);',
    '  }',
    '',
    '  return normalized;',
    '}',
    '',
    'function normalizeIndexUrls(indexUrls) {',
    '  if (!Array.isArray(indexUrls)) {',
    '    return [];',
    '  }',
    '',
    '  var normalized = [];',
    '  var seen = Object.create(null);',
    '  for (var index = 0; index < indexUrls.length; index++) {',
    '    var candidate = typeof indexUrls[index] === "string" ? indexUrls[index].trim() : "";',
    '    if (!candidate || seen[candidate] || !/^https?:\\/\\/\\S+$/i.test(candidate)) {',
    '      continue;',
    '    }',
    '    seen[candidate] = true;',
    '    normalized.push(candidate);',
    '  }',
    '',
    '  return normalized;',
    '}',
    '',
    'function truncateBridgeText(value, maxChars) {',
    '  var normalized = typeof value === "string" ? value.trim() : "";',
    '  if (!normalized) {',
    '    return undefined;',
    '  }',
    '  if (normalized.length <= maxChars) {',
    '    return normalized;',
    '  }',
    '  return normalized.slice(0, Math.max(1, maxChars - 3)).trimEnd() + "...";',
    '}',
    '',
    'function normalizeBridgeEnum(value, allowedValues) {',
    '  var normalized = truncateBridgeText(value, 40);',
    '  if (!normalized) {',
    '    return undefined;',
    '  }',
    '  normalized = normalized.toLowerCase();',
    '  return allowedValues.indexOf(normalized) >= 0 ? normalized : undefined;',
    '}',
    '',
    'function normalizeBridgeWorkspacePath(value) {',
    '  if (typeof value !== "string") {',
    '    return undefined;',
    '  }',
    '  var normalized = String(value);',
    '  while (normalized.indexOf("\\\\") >= 0) {',
    '    normalized = normalized.replace("\\\\", "/");',
    '  }',
    '  while (normalized.charAt(0) === "/") {',
    '    normalized = normalized.slice(1);',
    '  }',
    '  var segments = [];',
    '  var invalid = false;',
    '  normalized.split("/").forEach(function(segment) {',
    '    var trimmed = segment.trim();',
    '    if (!trimmed || invalid) {',
    '      return;',
    '    }',
    '    if (trimmed === "." || trimmed === "..") {',
    '      invalid = true;',
    '      return;',
    '    }',
    '    segments.push(trimmed);',
    '  });',
    '  if (invalid || segments.length === 0) {',
    '    return undefined;',
    '  }',
    '  normalized = segments.join("/");',
    '  return normalized.length <= MAX_WORKFLOW_BRIDGE_OPTIONAL_TEXT_CHARS',
    '    ? normalized',
    '    : normalized.slice(0, Math.max(1, MAX_WORKFLOW_BRIDGE_OPTIONAL_TEXT_CHARS - 3)).trimEnd() + "...";',
    '}',
    '',
    'function normalizeBridgeTags(tags) {',
    '  if (!Array.isArray(tags)) {',
    '    return undefined;',
    '  }',
    '  var normalized = [];',
    '  var seen = Object.create(null);',
    '  for (var index = 0; index < tags.length; index++) {',
    '    var value = truncateBridgeText(tags[index], MAX_WORKFLOW_BRIDGE_OPTIONAL_TEXT_CHARS);',
    '    if (!value || seen[value]) {',
    '      continue;',
    '    }',
    '    seen[value] = true;',
    '    normalized.push(value);',
    '    if (normalized.length >= MAX_WORKFLOW_BRIDGE_TAGS) {',
    '      break;',
    '    }',
    '  }',
    '  return normalized.length > 0 ? normalized : undefined;',
    '}',
    '',
    'function normalizeWorkflowBridgeEntry(entry) {',
    '  if (!entry || typeof entry !== "object" || Array.isArray(entry)) {',
    '    return null;',
    '  }',
    '  var kind = normalizeBridgeEnum(entry.kind, ALLOWED_WORKFLOW_BRIDGE_KINDS);',
    '  var content = truncateBridgeText(entry.content, MAX_WORKFLOW_BRIDGE_CONTENT_CHARS);',
    '  if (!kind || !content) {',
    '    return null;',
    '  }',
    '  var normalized = { kind: kind, content: content };',
    '  var id = truncateBridgeText(entry.id, MAX_WORKFLOW_BRIDGE_OPTIONAL_TEXT_CHARS);',
    '  if (id) normalized.id = id;',
    '  var status = normalizeBridgeEnum(entry.status, ALLOWED_WORKFLOW_BRIDGE_STATUSES);',
    '  if (status) normalized.status = status;',
    '  var recorder = normalizeBridgeEnum(entry.recorder, ALLOWED_WORKFLOW_BRIDGE_RECORDERS);',
    '  if (recorder) normalized.recorder = recorder;',
    '  var title = truncateBridgeText(entry.title, MAX_WORKFLOW_BRIDGE_TITLE_CHARS);',
    '  if (title) normalized.title = title;',
    '  var dedupeKey = truncateBridgeText(entry.dedupeKey, MAX_WORKFLOW_BRIDGE_OPTIONAL_TEXT_CHARS);',
    '  if (dedupeKey) normalized.dedupeKey = dedupeKey;',
    '  var sourceName = truncateBridgeText(entry.sourceName, MAX_WORKFLOW_BRIDGE_OPTIONAL_TEXT_CHARS);',
    '  if (sourceName) normalized.sourceName = sourceName;',
    '  var sourceUri = truncateBridgeText(entry.sourceUri, MAX_WORKFLOW_BRIDGE_OPTIONAL_TEXT_CHARS);',
    '  if (sourceUri) normalized.sourceUri = sourceUri;',
    '  var toolName = truncateBridgeText(entry.toolName, MAX_WORKFLOW_BRIDGE_OPTIONAL_TEXT_CHARS);',
    '  if (toolName) normalized.toolName = toolName;',
    '  var workerSessionId = truncateBridgeText(entry.workerSessionId, MAX_WORKFLOW_BRIDGE_OPTIONAL_TEXT_CHARS);',
    '  if (workerSessionId) normalized.workerSessionId = workerSessionId;',
    '  var artifactWorkspacePath = normalizeBridgeWorkspacePath(entry.artifactWorkspacePath);',
    '  if (artifactWorkspacePath) normalized.artifactWorkspacePath = artifactWorkspacePath;',
    '  var tags = normalizeBridgeTags(entry.tags);',
    '  if (tags) normalized.tags = tags;',
    '  if (typeof entry.createdAt === "number" && isFinite(entry.createdAt)) normalized.createdAt = entry.createdAt;',
    '  if (typeof entry.updatedAt === "number" && isFinite(entry.updatedAt)) normalized.updatedAt = entry.updatedAt;',
    '  return normalized;',
    '}',
    '',
    'function normalizeWorkflowBridgeEntries(entries, maxEntries) {',
    '  if (!Array.isArray(entries)) {',
    '    return [];',
    '  }',
    '  return entries',
    '    .map(normalizeWorkflowBridgeEntry)',
    '    .filter(Boolean)',
    '    .slice(-Math.max(1, maxEntries || MAX_WORKFLOW_BRIDGE_ENTRIES));',
    '}',
    '',
    'function configureWorkflowBridge(config) {',
    '  var evidence = normalizeWorkflowBridgeEntries(config && Array.isArray(config.evidence) ? config.evidence : [], MAX_WORKFLOW_BRIDGE_ENTRIES);',
    '  activeWorkflowBridgeState = {',
    '    evidence: evidence.slice(),',
    '    emittedEvidence: [],',
    '  };',
    '}',
    '',
    'function collectWorkflowBridgeResult() {',
    '  if (!activeWorkflowBridgeState || activeWorkflowBridgeState.emittedEvidence.length === 0) {',
    '    return undefined;',
    '  }',
    '  return {',
    '    emittedEvidence: activeWorkflowBridgeState.emittedEvidence.slice(-MAX_WORKFLOW_BRIDGE_ENTRIES),',
    '  };',
    '}',
    '',
    'function resetWorkflowBridge() {',
    '  activeWorkflowBridgeState = null;',
    '}',
    '',
    'self.__kavi_workflow_bridge__ = {',
    '  is_enabled: function() {',
    '    return !!activeWorkflowBridgeState;',
    '  },',
    '  get_state_json: function() {',
    '    return JSON.stringify(activeWorkflowBridgeState ? activeWorkflowBridgeState.evidence : []);',
    '  },',
    '  record_entries_json: function(payload) {',
    '    if (!activeWorkflowBridgeState) {',
    '      return 0;',
    '    }',
    '    var parsed;',
    '    try {',
    '      parsed = JSON.parse(String(payload || "[]"));',
    '    } catch (error) {',
    '      return 0;',
    '    }',
    '    var entries = normalizeWorkflowBridgeEntries(Array.isArray(parsed) ? parsed : [parsed], MAX_WORKFLOW_BRIDGE_ENTRIES);',
    '    if (entries.length === 0) {',
    '      return 0;',
    '    }',
    '    Array.prototype.push.apply(activeWorkflowBridgeState.emittedEvidence, entries);',
    '    activeWorkflowBridgeState.emittedEvidence = activeWorkflowBridgeState.emittedEvidence.slice(-MAX_WORKFLOW_BRIDGE_ENTRIES);',
    '    Array.prototype.push.apply(activeWorkflowBridgeState.evidence, entries);',
    '    activeWorkflowBridgeState.evidence = activeWorkflowBridgeState.evidence.slice(-MAX_WORKFLOW_BRIDGE_ENTRIES);',
    '    return entries.length;',
    '  },',
    '};',
    '',
    'function parseExecutionResult(result) {',
    '  if (typeof result === "string") {',
    '    try {',
    '      return JSON.parse(result);',
    '    } catch (error) {',
    '      return { result_text: result || null, error: null };',
    '    }',
    '  }',
    '  return result && typeof result === "object"',
    '    ? result',
    '    : { result_text: null, error: null };',
    '}',
    '',
    'function ensureDir(fsPath) {',
    '  try {',
    '    pyodide.FS.mkdirTree(fsPath);',
    '  } catch (error) {',
    '    // mkdirTree is effectively idempotent for our usage.',
    '  }',
    '}',
    '',
    'function removeFsPath(fsPath) {',
    '  var stat;',
    '  try {',
    '    stat = pyodide.FS.stat(fsPath);',
    '  } catch (error) {',
    '    return;',
    '  }',
    '',
    '  if (pyodide.FS.isDir(stat.mode)) {',
    '    var entries = pyodide.FS.readdir(fsPath).filter(function(entry) {',
    '      return entry !== "." && entry !== "..";',
    '    });',
    '    for (var index = 0; index < entries.length; index++) {',
    '      removeFsPath(fsPath + "/" + entries[index]);',
    '    }',
    '    pyodide.FS.rmdir(fsPath);',
    '    return;',
    '  }',
    '',
    '  pyodide.FS.unlink(fsPath);',
    '}',
    '',
    'function resetWorkspaceRoot() {',
    '  ensureDir(WORKSPACE_ROOT);',
    '  var entries = pyodide.FS.readdir(WORKSPACE_ROOT).filter(function(entry) {',
    '    return entry !== "." && entry !== "..";',
    '  });',
    '  for (var index = 0; index < entries.length; index++) {',
    '    removeFsPath(WORKSPACE_ROOT + "/" + entries[index]);',
    '  }',
    '}',
    '',
    'function decodeBase64(base64) {',
    '  var normalized = String(base64 || "").replace(/\\s+/g, "");',
    '  var binary = atob(normalized);',
    '  var bytes = new Uint8Array(binary.length);',
    '  for (var index = 0; index < binary.length; index++) {',
    '    bytes[index] = binary.charCodeAt(index);',
    '  }',
    '  return bytes;',
    '}',
    '',
    'function encodeBase64(bytes) {',
    "  var binary = '';",
    '  var chunkSize = 0x8000;',
    '  for (var index = 0; index < bytes.length; index += chunkSize) {',
    '    var chunk = bytes.subarray(index, Math.min(index + chunkSize, bytes.length));',
    '    binary += String.fromCharCode.apply(null, Array.prototype.slice.call(chunk));',
    '  }',
    '  return btoa(binary);',
    '}',
    '',
    'function normalizeNativeHttpTimeout(timeoutMs) {',
    '  if (typeof timeoutMs !== "number" || !isFinite(timeoutMs) || timeoutMs <= 0) {',
    '    return 30000;',
    '  }',
    '  return Math.max(250, Math.min(120000, Math.trunc(timeoutMs)));',
    '}',
    '',
    'function wrapNativeHttpResponse(response, metadata) {',
    '  return {',
    '    get ok() { return response.ok; },',
    '    get status() { return response.status; },',
    '    get statusText() { return response.statusText; },',
    '    get headers() { return response.headers; },',
    '    get type() { return response.type; },',
    '    get body() { return response.body; },',
    '    get bodyUsed() { return response.bodyUsed; },',
    '    get url() { return metadata.url || ""; },',
    '    get redirected() { return Boolean(metadata.redirected); },',
    '    arrayBuffer: function() { return response.arrayBuffer(); },',
    '    blob: function() { return response.blob(); },',
    '    formData: function() { return response.formData(); },',
    '    json: function() { return response.json(); },',
    '    text: function() { return response.text(); },',
    '    clone: function() { return wrapNativeHttpResponse(response.clone(), metadata); },',
    '  };',
    '}',
    '',
    'function createNativeHttpResponse(message) {',
    '  var response = new Response(message.bodyBase64 ? decodeBase64(message.bodyBase64) : new Uint8Array(0), {',
    '    status: typeof message.status === "number" ? message.status : 200,',
    '    statusText: typeof message.statusText === "string" ? message.statusText : "",',
    '    headers: message.headers && typeof message.headers === "object" ? message.headers : {},',
    '  });',
    '  return wrapNativeHttpResponse(response, {',
    '    url: typeof message.url === "string" ? message.url : "",',
    '    redirected: Boolean(message.redirected),',
    '  });',
    '}',
    '',
    'function handleNativeHttpResponse(message) {',
    '  var pending = message && message.requestId ? pendingNativeHttpRequests[message.requestId] : null;',
    '  if (!pending) {',
    '    return;',
    '  }',
    '  if (message.error) {',
    '    pending.reject(new Error(String(message.error)));',
    '    return;',
    '  }',
    '  pending.resolve(message);',
    '}',
    '',
    'async function bridgeNativeHttpRequest(request, options) {',
    '  if (!request || typeof request.url !== "string" || !request.url) {',
    '    throw new Error("Native HTTP bridge expected a Request object.");',
    '  }',
    '',
    '  var headers = {};',
    '  if (request.headers && typeof request.headers.forEach === "function") {',
    '    request.headers.forEach(function(value, key) {',
    '      headers[String(key)] = String(value);',
    '    });',
    '  }',
    '',
    '  var bodyBase64;',
    '  if (request.method !== "GET" && request.method !== "HEAD") {',
    '    try {',
    '      var clonedRequest = typeof request.clone === "function" ? request.clone() : request;',
    '      var bodyBuffer = await clonedRequest.arrayBuffer();',
    '      if (bodyBuffer && bodyBuffer.byteLength > 0) {',
    '        bodyBase64 = encodeBase64(new Uint8Array(bodyBuffer));',
    '      }',
    '    } catch (error) {}',
    '  }',
    '',
    '  var signal = options && options.signal ? options.signal : (request.signal || null);',
    '  var timeoutMs = normalizeNativeHttpTimeout(options && typeof options.timeout_ms === "number" ? options.timeout_ms : undefined);',
    '  var requestId = "py-http-" + (++nativeHttpRequestCounter) + "-" + Math.random().toString(36).slice(2);',
    '',
    '  return await new Promise(function(resolve, reject) {',
    '    var abortListener = null;',
    '',
    '    function cleanup() {',
    '      if (signal && abortListener && typeof signal.removeEventListener === "function") {',
    '        signal.removeEventListener("abort", abortListener);',
    '      }',
    '      delete pendingNativeHttpRequests[requestId];',
    '    }',
    '',
    '    if (signal && signal.aborted) {',
    '      reject(new Error("Python HTTP request was aborted."));',
    '      return;',
    '    }',
    '',
    '    abortListener = function() {',
    '      cleanup();',
    '      self.postMessage({',
    '        type: "python-http-abort",',
    '        requestId: requestId,',
    '        reason: signal && "reason" in signal ? signal.reason : undefined,',
    '      });',
    '      reject(new Error("Python HTTP request was aborted."));',
    '    };',
    '',
    '    if (signal && typeof signal.addEventListener === "function") {',
    '      signal.addEventListener("abort", abortListener, { once: true });',
    '    }',
    '',
    '    pendingNativeHttpRequests[requestId] = {',
    '      resolve: function(message) {',
    '        cleanup();',
    '        resolve(createNativeHttpResponse(message));',
    '      },',
    '      reject: function(error) {',
    '        cleanup();',
    '        reject(error instanceof Error ? error : new Error(formatError(error)));',
    '      },',
    '    };',
    '',
    '    self.postMessage({',
    '      type: "python-http-request",',
    '      requestId: requestId,',
    '      url: request.url,',
    '      method: request.method || "GET",',
    '      headers: headers,',
    '      bodyBase64: bodyBase64,',
    '      timeoutMs: timeoutMs,',
    '    });',
    '  });',
    '}',
    '',
    'self.__kavi_native_http__ = {',
    '  is_available: function() {',
    '    return true;',
    '  },',
    '  fetch: bridgeNativeHttpRequest,',
    '};',
    '',
    'function mountWorkspaceFiles(files) {',
    '  resetWorkspaceRoot();',
    '',
    '  for (var index = 0; index < files.length; index++) {',
    '    var file = files[index];',
    '    var fullPath = toWorkspaceFsPath(file.path);',
    '    var lastSlash = fullPath.lastIndexOf("/");',
    '    var parent = lastSlash > 0 ? fullPath.slice(0, lastSlash) : WORKSPACE_ROOT;',
    '    ensureDir(parent);',
    '    pyodide.FS.writeFile(fullPath, decodeBase64(file.contentBase64), { encoding: "binary" });',
    '  }',
    '}',
    '',
    'function collectWorkspaceFiles(fsPath, prefix) {',
    '  var collected = [];',
    '  var entries = pyodide.FS.readdir(fsPath).filter(function(entry) {',
    '    return entry !== "." && entry !== "..";',
    '  });',
    '',
    '  for (var index = 0; index < entries.length; index++) {',
    '    var name = entries[index];',
    '    var childPath = fsPath + "/" + name;',
    '    var relativePath = prefix ? prefix + "/" + name : name;',
    '    var stat = pyodide.FS.stat(childPath);',
    '',
    '    if (pyodide.FS.isDir(stat.mode)) {',
    '      collected = collected.concat(collectWorkspaceFiles(childPath, relativePath));',
    '      continue;',
    '    }',
    '',
    '    collected.push({',
    '      path: relativePath,',
    '      contentBase64: encodeBase64(pyodide.FS.readFile(childPath, { encoding: "binary" })),',
    '    });',
    '  }',
    '',
    '  return collected;',
    '}',
    '',
    'function indexWorkspaceFiles(files) {',
    '  var indexed = {};',
    '  for (var index = 0; index < files.length; index++) {',
    '    indexed[files[index].path] = files[index].contentBase64;',
    '  }',
    '  return indexed;',
    '}',
    '',
    'function clearInjectedEnv() {',
    '  if (injectedEnvKeys.length === 0) {',
    '    return;',
    '  }',
    '',
    "  var resetLines = ['import os'];",
    '  for (var index = 0; index < injectedEnvKeys.length; index++) {',
    '    resetLines.push("os.environ.pop(" + JSON.stringify(injectedEnvKeys[index]) + ", None)");',
    '  }',
    '  pyodide.runPython(resetLines.join("\\n"));',
    '  injectedEnvKeys = [];',
    '}',
    '',
    'function buildMicropipInstallCode(packages, indexUrls) {',
    '  var call = "await micropip.install(" + JSON.stringify(packages);',
    '  if (indexUrls.length > 0) {',
    '    call += ", index_urls=" + JSON.stringify(indexUrls);',
    '  }',
    '  call += ")";',
    '  return ["import micropip", call].join("\\n");',
    '}',
    '',
    'function formatPackageInstallError(error, packages, indexUrls) {',
    '  var baseMessage = formatError(error);',
    '  var guidance = "Pyodide can install official Pyodide packages, pure-Python wheels, and wasm/emscripten-compatible wheels only.";',
    '  if (indexUrls.length > 0) {',
    '    guidance += " Custom indexes must expose compatible wheels over HTTP(S) with CORS enabled.";',
    '  } else if (packages.length > 0) {',
    '    guidance += " If PyPI does not provide a compatible wheel, supply a wheel URL or custom indexUrls.";',
    '  }',
    '  return baseMessage + " " + guidance;',
    '}',
    '',
    'async function bootPyodide() {',
    '  try {',
    `    importScripts(${JSON.stringify(`${PYODIDE_WEBVIEW_BASE_URL}pyodide.js`)});`,
    `    pyodide = await loadPyodide({ indexURL: ${JSON.stringify(PYODIDE_WEBVIEW_BASE_URL)} });`,
    '    pyodide.setStdout({ batched: onStdout });',
    '    pyodide.setStderr({ batched: onStderr });',
    '    await pyodide.loadPackage("micropip");',
    '    await pyodide.runPythonAsync(PYODIDE_RUNTIME_HELPERS);',
    '    installedPackageSpecs = Object.create(null);',
    '    self.postMessage({ type: "pyodide-ready" });',
    '  } catch (error) {',
    '    bootError = error;',
    '    self.postMessage({ type: "pyodide-ready", error: formatError(error) });',
    '    throw error;',
    '  }',
    '}',
    '',
    'var pyodideReadyPromise = bootPyodide();',
    '',
    'async function runPythonRequest(message) {',
    '  try {',
    '    await pyodideReadyPromise;',
    '  } catch (error) {',
    '    throw new Error(formatError(bootError || error));',
    '  }',
    '',
    '  var start = Date.now();',
    '  beginCapture();',
    '  try {',
    '    configureWorkflowBridge(message.workflowBridge);',
    '    var packagesToInstall = normalizePackageSpecs(message.packages).filter(function(spec) {',
    '      return !installedPackageSpecs[spec];',
    '    });',
    '    var indexUrls = normalizeIndexUrls(message.indexUrls);',
    '',
    '    mountWorkspaceFiles(Array.isArray(message.files) ? message.files : []);',
    '    var initialFiles = indexWorkspaceFiles(collectWorkspaceFiles(WORKSPACE_ROOT, ""));',
    '',
    '    if (packagesToInstall.length > 0) {',
    '      try {',
    '        await pyodide.runPythonAsync(buildMicropipInstallCode(packagesToInstall, indexUrls));',
    '      } catch (packageError) {',
    '        throw new Error(formatPackageInstallError(packageError, packagesToInstall, indexUrls));',
    '      }',
    '      for (var packageIndex = 0; packageIndex < packagesToInstall.length; packageIndex++) {',
    '        installedPackageSpecs[packagesToInstall[packageIndex]] = true;',
    '      }',
    '    }',
    '',
    "    var sourceForImports = '';",
    '    if (message.scriptPath) {',
    '      sourceForImports = pyodide.FS.readFile(toWorkspaceFsPath(message.scriptPath), { encoding: "utf8" });',
    '    } else if (typeof message.code === "string") {',
    '      sourceForImports = message.code;',
    '    }',
    '',
    '    if (sourceForImports && sourceForImports.trim()) {',
    '      await pyodide.loadPackagesFromImports(sourceForImports);',
    '    }',
    '',
    '    clearInjectedEnv();',
    '    if (message.env && Object.keys(message.env).length > 0) {',
    '      var envEntries = Object.entries(message.env)',
    '        .map(function(entry) { return JSON.stringify(entry[0]) + ": " + JSON.stringify(entry[1]); })',
    '        .join(", ");',
    '      pyodide.runPython("import os; os.environ.update({" + envEntries + "})");',
    '      injectedEnvKeys = Object.keys(message.env);',
    '    }',
    '',
    '    var workingDirectory = message.workingDirectory ? toWorkspaceFsPath(message.workingDirectory) : WORKSPACE_ROOT;',
    '    var executionResult;',
    '    if (message.scriptPath) {',
    '      var scriptPath = toWorkspaceFsPath(message.scriptPath);',
    '      var argv = Array.isArray(message.argv) ? message.argv : [];',
    '      executionResult = parseExecutionResult(await pyodide.runPythonAsync(',
    '        "await _kavi_execute_script("',
    '        + JSON.stringify(scriptPath) + ", "',
    '        + JSON.stringify(argv) + ", "',
    '        + JSON.stringify(workingDirectory) + ", "',
    '        + JSON.stringify(WORKSPACE_ROOT)',
    '        + ")"',
    '      ));',
    '    } else {',
    '      executionResult = parseExecutionResult(await pyodide.runPythonAsync(',
    '        "await _kavi_execute_inline("',
    '        + JSON.stringify(message.code || "") + ", "',
    '        + JSON.stringify(workingDirectory) + ", "',
    '        + JSON.stringify(WORKSPACE_ROOT)',
    '        + ")"',
    '      ));',
    '    }',
    '',
    '    clearInjectedEnv();',
    '    var capture = finishCapture();',
    '    var errorMessage = executionResult.error || undefined;',
    '    var workflowBridgeResult = collectWorkflowBridgeResult();',
    '    var changedFiles = collectWorkspaceFiles(WORKSPACE_ROOT, "").filter(function(file) {',
    '      return initialFiles[file.path] !== file.contentBase64;',
    '    });',
    '',
    '    var successMessage = {',
    '      type: "python-result",',
    '      id: message.id,',
    '      output: combineExecutionOutput(capture, executionResult.result_text, Boolean(errorMessage)),',
    '      error: errorMessage,',
    '      durationMs: Date.now() - start,',
    '      files: errorMessage ? [] : changedFiles,',
    '    };',
    '    if (workflowBridgeResult) {',
    '      successMessage.workflowBridge = workflowBridgeResult;',
    '    }',
    '    resetWorkflowBridge();',
    '    self.postMessage(successMessage);',
    '  } catch (error) {',
    '    try { clearInjectedEnv(); } catch (cleanupError) {}',
    '    var capture = finishCapture();',
    '    var workflowBridgeResult = collectWorkflowBridgeResult();',
    '    var errorMessage = {',
    '      type: "python-result",',
    '      id: message.id,',
    '      output: combineExecutionOutput(capture, null, true),',
    '      error: formatError(error),',
    '      durationMs: Date.now() - start,',
    '    };',
    '    if (workflowBridgeResult) {',
    '      errorMessage.workflowBridge = workflowBridgeResult;',
    '    }',
    '    resetWorkflowBridge();',
    '    self.postMessage(errorMessage);',
    '  }',
    '}',
    '',
    'self.onmessage = function(event) {',
    '  var message = event && event.data ? event.data : {};',
    '  if (message.type === "python-http-response" && message.requestId) {',
    '    handleNativeHttpResponse(message);',
    '    return;',
    '  }',
    '  if (message.type !== "run-python" || !message.id) {',
    '    return;',
    '  }',
    '  void runPythonRequest(message);',
    '};',
  ].join('\n');
}

export function getPyodideWorkerSource(): string {
  return buildPyodideWorkerSource();
}

export function getPyodideHtml(): string {
  if (pyodideHtmlCache) {
    return pyodideHtmlCache;
  }

  const workerSource = getPyodideWorkerSource();
  pyodideHtmlCache = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body>
<script>
(function() {
  var runtimeId = 'py-runtime-' + Math.random().toString(36).slice(2);
  var completedResultsById = Object.create(null);
  var completedResultIds = [];
  var activeRequestIds = Object.create(null);
  var pendingNativeMessages = [];
  var nativeMessageFlushTimer = null;
  var worker = null;

  function canPostMessageToNative() {
    return !!(window.ReactNativeWebView && typeof window.ReactNativeWebView.postMessage === 'function');
  }

  function decorateMessage(msg) {
    var base = msg && typeof msg === 'object' ? msg : { type: 'python-runtime-error', error: 'Invalid runtime message.' };
    if (!base.runtimeId) {
      base.runtimeId = runtimeId;
    }
    return base;
  }

  function flushPendingNativeMessages() {
    if (!canPostMessageToNative()) {
      return false;
    }

    while (pendingNativeMessages.length > 0) {
      window.ReactNativeWebView.postMessage(pendingNativeMessages.shift());
    }

    if (nativeMessageFlushTimer != null) {
      clearInterval(nativeMessageFlushTimer);
      nativeMessageFlushTimer = null;
    }

    return true;
  }

  function scheduleNativeMessageFlush() {
    if (nativeMessageFlushTimer != null) {
      return;
    }

    nativeMessageFlushTimer = setInterval(function() {
      flushPendingNativeMessages();
    }, 50);
  }

  function sendMessage(msg) {
    var serialized = JSON.stringify(decorateMessage(msg));
    if (canPostMessageToNative()) {
      window.ReactNativeWebView.postMessage(serialized);
      return;
    }

    pendingNativeMessages.push(serialized);
    scheduleNativeMessageFlush();
  }

  function cacheCompletedResult(resultMessage) {
    if (!resultMessage || !resultMessage.id) {
      return;
    }

    completedResultsById[resultMessage.id] = resultMessage;
    completedResultIds.push(resultMessage.id);
    if (completedResultIds.length > ${PYODIDE_RESULT_CACHE_LIMIT}) {
      var evictedId = completedResultIds.shift();
      if (evictedId) {
        delete completedResultsById[evictedId];
      }
    }
  }

  function sendPythonResult(resultMessage) {
    cacheCompletedResult(resultMessage);
    sendMessage(resultMessage);
  }

  function formatError(error) {
    return error && error.message ? error.message : String(error);
  }

  function clearActiveRequest(id) {
    if (id && activeRequestIds[id]) {
      delete activeRequestIds[id];
    }
  }

  function handleWorkerMessage(event) {
    var message = event && event.data ? event.data : null;
    if (!message || typeof message !== 'object') {
      return;
    }

    if (message.type === 'python-result' && message.id) {
      clearActiveRequest(message.id);
      sendPythonResult(message);
      return;
    }

    if (message.type === 'pyodide-ready') {
      sendMessage(message);
      return;
    }

    sendMessage(message);
  }

  function handleWorkerFailure(prefix, error) {
    sendMessage({
      type: 'python-runtime-error',
      error: prefix + ': ' + formatError(error),
    });
  }

  function createWorker() {
    try {
      var sourceUrl = URL.createObjectURL(new Blob([${JSON.stringify(workerSource)}], { type: 'text/javascript' }));
      worker = new Worker(sourceUrl);
      URL.revokeObjectURL(sourceUrl);
      worker.onmessage = handleWorkerMessage;
      worker.onerror = function(event) {
        handleWorkerFailure('Pyodide worker failed', event && event.message ? event.message : event);
      };
      worker.onmessageerror = function(event) {
        handleWorkerFailure('Pyodide worker message error', event && event.data ? event.data : 'messageerror');
      };
    } catch (error) {
      sendMessage({ type: 'pyodide-ready', error: 'Pyodide worker could not be created: ' + formatError(error) });
    }
  }

  function forwardRunMessage(message) {
    if (completedResultsById[message.id]) {
      sendMessage({ type: 'python-dispatch-ack', id: message.id, duplicate: true });
      sendMessage(completedResultsById[message.id]);
      return;
    }

    if (activeRequestIds[message.id]) {
      sendMessage({ type: 'python-dispatch-ack', id: message.id, duplicate: true });
      return;
    }

    activeRequestIds[message.id] = true;
    sendMessage({ type: 'python-dispatch-ack', id: message.id });
    if (!worker) {
      clearActiveRequest(message.id);
      sendPythonResult({
        type: 'python-result',
        id: message.id,
        output: '',
        error: 'Pyodide worker is not available.',
      });
      return;
    }

    worker.postMessage(message);
  }

  function handleMessage(data) {
    try {
      var message = typeof data === 'string' ? JSON.parse(data) : data;
      if (message.type === 'run-python' && message.id) {
        forwardRunMessage(message);
        return;
      }
      if (message.type === 'python-http-response' && message.requestId && worker) {
        worker.postMessage(message);
      }
    } catch (error) {
      // Ignore malformed bridge messages.
    }
  }

  window[${JSON.stringify(PYODIDE_WEBVIEW_BRIDGE_NAME)}] = {
    receive: handleMessage,
  };

  document.addEventListener('message', function(event) { handleMessage(event.data); });
  window.addEventListener('message', function(event) { handleMessage(event.data); });
  window.addEventListener('load', function() { flushPendingNativeMessages(); });
  window.addEventListener('pageshow', function() { flushPendingNativeMessages(); });
  window.addEventListener('error', function(event) {
    handleWorkerFailure('Pyodide page error', event && event.message ? event.message : event);
  });
  window.addEventListener('unhandledrejection', function(event) {
    var reason = event && 'reason' in event ? event.reason : event;
    handleWorkerFailure('Pyodide page unhandled rejection', reason);
  });
  document.addEventListener('visibilitychange', function() {
    if (document.visibilityState === 'visible') {
      flushPendingNativeMessages();
    }
  });

  createWorker();
  sendMessage({ type: 'bridge-ready' });
})();
</script>
</body>
</html>`;

  return pyodideHtmlCache;
}
