import { StyleSheet } from 'react-native';
import type { AppPalette } from '../../theme/useAppTheme';

export function createMemoryScreenStyles(colors: AppPalette) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 12,
      gap: 12,
    },
    title: { fontSize: 20, fontWeight: '700', color: colors.text, flex: 1 },
    headerActions: { flexDirection: 'row', alignItems: 'center', gap: 16 },
    headerButton: {
      width: 44,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 22,
    },
    tabsScroll: {
      marginHorizontal: 16,
      flexGrow: 0,
      flexShrink: 0,
    },
    tabs: {
      flexDirection: 'row',
      borderRadius: 8,
      backgroundColor: colors.surface,
      overflow: 'hidden',
    },
    tab: {
      minWidth: 92,
      minHeight: 44,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 10,
      gap: 6,
    },
    tabActive: { backgroundColor: colors.primarySoft },
    tabText: { fontSize: 14, color: colors.textSecondary },
    tabTextActive: { color: colors.primary, fontWeight: '600' },
    editorContainer: { flex: 1, paddingHorizontal: 16, paddingTop: 8 },
    attributionFooter: {
      fontSize: 11,
      color: colors.textTertiary,
      textAlign: 'center',
      paddingHorizontal: 16,
      paddingVertical: 10,
      backgroundColor: colors.background,
    },
    statusLine: {
      fontSize: 12,
      color: colors.textTertiary,
      marginBottom: 10,
    },
    overviewSectionTitle: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
      marginTop: 8,
      marginBottom: 4,
    },
    overviewBody: {
      fontSize: 14,
      color: colors.text,
      lineHeight: 20,
      marginBottom: 8,
    },
    overviewContent: { paddingBottom: 24 },
    overviewHero: { gap: 5, paddingBottom: 14, paddingTop: 8 },
    overviewHeading: { color: colors.text, fontSize: 21, fontWeight: '700' },
    overviewIntro: { color: colors.textSecondary, fontSize: 14, lineHeight: 20 },
    overviewSummaryCard: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 14,
      borderWidth: StyleSheet.hairlineWidth,
      gap: 10,
      marginBottom: 10,
      padding: 14,
    },
    overviewSummaryHeader: { alignItems: 'center', flexDirection: 'row', gap: 10 },
    overviewSummaryIcon: {
      alignItems: 'center',
      backgroundColor: colors.primarySoft,
      borderRadius: 10,
      height: 36,
      justifyContent: 'center',
      width: 36,
    },
    overviewSummaryTitle: { color: colors.text, flex: 1, fontSize: 15, fontWeight: '700' },
    overviewSummaryValue: { color: colors.text, fontSize: 16, lineHeight: 23 },
    overviewSummaryEmpty: { color: colors.textSecondary, fontSize: 14, lineHeight: 20 },
    overviewPrimaryAction: {
      alignItems: 'center',
      alignSelf: 'flex-start',
      backgroundColor: colors.primary,
      borderRadius: 12,
      flexDirection: 'row',
      gap: 7,
      justifyContent: 'center',
      minHeight: 48,
      paddingHorizontal: 16,
    },
    overviewPrimaryActionText: { color: colors.onPrimary, fontSize: 14, fontWeight: '700' },
    overviewSearchLabel: {
      color: colors.textSecondary,
      fontSize: 13,
      fontWeight: '600',
      marginBottom: 6,
      marginTop: 6,
    },
    overviewRecentTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 10,
      marginTop: 18,
    },
    overviewRecentEmpty: {
      color: colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      paddingBottom: 24,
      textAlign: 'center',
    },
    overviewUnavailableCard: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 14,
      borderWidth: StyleSheet.hairlineWidth,
      gap: 14,
      marginTop: 24,
      padding: 20,
    },
    overviewUnavailableText: {
      color: colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      textAlign: 'center',
    },
    overviewSecondaryAction: {
      alignItems: 'center',
      borderColor: colors.border,
      borderRadius: 12,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 7,
      justifyContent: 'center',
      minHeight: 48,
      paddingHorizontal: 16,
    },
    overviewSecondaryActionText: { color: colors.primary, fontSize: 14, fontWeight: '700' },
    editorScroll: { flex: 1 },
    editor: {
      fontSize: 14,
      color: colors.text,
      fontFamily: 'monospace',
      lineHeight: 20,
      padding: 12,
      backgroundColor: colors.surface,
      borderRadius: 8,
      minHeight: 400,
    },
    emptyText: {
      fontSize: 14,
      color: colors.textSecondary,
      textAlign: 'center',
      marginTop: 40,
    },
    factsToolbar: {
      gap: 8,
      marginBottom: 8,
    },
    factsSearch: {
      borderColor: colors.inputBorder,
      borderWidth: 1,
      fontSize: 16,
      color: colors.text,
      paddingHorizontal: 12,
      paddingVertical: 10,
      backgroundColor: colors.inputBackground,
      borderRadius: 12,
      minHeight: 48,
    },
    factsToggleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 4,
    },
    factRow: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      padding: 12,
      marginBottom: 8,
      gap: 4,
    },
    factSubject: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.text,
    },
    factValue: {
      fontSize: 14,
      color: colors.text,
    },
    factMeta: {
      fontSize: 12,
      color: colors.textTertiary,
    },
    factActions: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: 16,
      marginTop: 6,
    },
    advancedContent: {
      paddingBottom: 16,
    },
    advancedCard: {
      marginTop: 12,
      padding: 12,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      backgroundColor: colors.surface,
    },
    advancedToggle: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      marginTop: 4,
      paddingHorizontal: 12,
      borderRadius: 12,
      backgroundColor: colors.surfaceAlt,
    },
    advancedToggleText: {
      flex: 1,
      color: colors.text,
      fontSize: 14,
      fontWeight: '600',
    },
    advancedDetails: {
      marginTop: 8,
    },
    advancedLoadingRow: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    emptyInline: {
      color: colors.textSecondary,
      fontSize: 13,
      lineHeight: 18,
    },
    advancedCardTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 8,
    },
    advancedCardTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '700',
    },
    clearMemoryButton: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingHorizontal: 16,
      borderWidth: 1,
      borderColor: colors.danger,
      borderRadius: 12,
    },
    clearMemoryButtonText: {
      color: colors.danger,
      fontSize: 14,
      fontWeight: '700',
    },
    blockCard: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      padding: 12,
      marginBottom: 12,
      gap: 6,
    },
    blockEditor: {
      minHeight: 120,
      marginTop: 4,
    },
    episodesTitle: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.6,
      marginTop: 16,
      marginBottom: 8,
    },
  });
}
