import { StyleSheet } from 'react-native';
import type { AppPalette } from '../../theme/useAppTheme';

export function createMemoryScreenStyles(colors: AppPalette) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 12,
      gap: 12,
    },
    title: { fontSize: 20, fontWeight: '700', color: colors.text, flex: 1 },
    headerActions: { flexDirection: 'row', alignItems: 'center', gap: 16 },
    dangerBtn: { padding: 4 },
    tabsScroll: {
      marginHorizontal: 16,
      flexGrow: 0,
      flexShrink: 0,
    },
    tabs: {
      flexDirection: 'row',
      borderRadius: 8,
      backgroundColor: colors.surface,
      overflow: 'hidden',
    },
    tab: {
      minWidth: 92,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 10,
      gap: 6,
    },
    tabActive: { backgroundColor: colors.primarySoft },
    tabText: { fontSize: 14, color: colors.textSecondary },
    tabTextActive: { color: colors.primary, fontWeight: '600' },
    editorContainer: { flex: 1, paddingHorizontal: 16, paddingTop: 8 },
    attributionFooter: {
      fontSize: 11,
      color: colors.textTertiary,
      textAlign: 'center',
      paddingHorizontal: 16,
      paddingVertical: 10,
      backgroundColor: colors.background,
    },
    statsLine: {
      fontSize: 12,
      color: colors.textSecondary,
      marginBottom: 6,
    },
    statusLine: {
      fontSize: 12,
      color: colors.textTertiary,
      marginBottom: 10,
    },
    overviewSectionTitle: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
      marginTop: 8,
      marginBottom: 4,
    },
    overviewBody: {
      fontSize: 14,
      color: colors.text,
      lineHeight: 20,
      marginBottom: 8,
    },
    noticeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      marginBottom: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 8,
      backgroundColor: colors.warningBackground,
    },
    noticeText: {
      flex: 1,
      fontSize: 13,
      color: colors.warning,
    },
    noticeAction: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.primary,
    },
    editorScroll: { flex: 1 },
    editor: {
      fontSize: 14,
      color: colors.text,
      fontFamily: 'monospace',
      lineHeight: 20,
      padding: 12,
      backgroundColor: colors.surface,
      borderRadius: 8,
      minHeight: 400,
    },
    dailyContainer: { flex: 1, paddingHorizontal: 16, paddingTop: 8 },
    dateList: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 12,
    },
    dateChip: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
      backgroundColor: colors.surface,
    },
    dateChipActive: { backgroundColor: colors.primary },
    dateChipText: { fontSize: 13, color: colors.text },
    dateChipTextActive: { color: '#fff' },
    dailyViewer: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      padding: 12,
    },
    dailyHeader: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 8,
    },
    dailyBody: {
      fontSize: 14,
      color: colors.text,
      fontFamily: 'monospace',
      lineHeight: 20,
    },
    emptyText: {
      fontSize: 14,
      color: colors.textSecondary,
      textAlign: 'center',
      marginTop: 40,
    },
    factsToolbar: {
      gap: 8,
      marginBottom: 8,
    },
    factsSearch: {
      fontSize: 14,
      color: colors.text,
      paddingHorizontal: 12,
      paddingVertical: 8,
      backgroundColor: colors.surface,
      borderRadius: 8,
    },
    factsToggleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 4,
    },
    factRow: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      padding: 12,
      marginBottom: 8,
      gap: 4,
    },
    factSubject: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.text,
    },
    factValue: {
      fontSize: 14,
      color: colors.text,
    },
    factMeta: {
      fontSize: 12,
      color: colors.textTertiary,
    },
    factActions: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: 16,
      marginTop: 6,
    },
    blockCard: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      padding: 12,
      marginBottom: 12,
      gap: 6,
    },
    blockEditor: {
      minHeight: 120,
      marginTop: 4,
    },
    episodesTitle: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.6,
      marginTop: 16,
      marginBottom: 8,
    },
  });
}
